"""Executable specification for US-13: Backend verifier."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'spec_guard_must_support', 'statement': 'Spec Guard must support:', 'target': 'Spec Guard must support:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'http_endpoint_adapter_optional_unless_implemented_and_exposed', 'statement': 'HTTP endpoint adapter, optional unless implemented and exposed.', 'target': 'HTTP endpoint adapter, optional unless implemented and exposed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'provider_model_adapter_optional_unless_implemented_and_exposed', 'statement': 'Provider/model adapter, optional unless implemented and exposed.', 'target': 'Provider/model adapter, optional unless implemented and exposed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'test_fixture_adapter_for_spec_guard_s_own_tests_only', 'statement': "Test fixture adapter for Spec Guard's own tests only.", 'target': "Test fixture adapter for Spec Guard's own tests only", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_local_command_adapter_is_the_minimum_required_executable_adapter', 'statement': 'The local command adapter is the minimum required executable adapter.', 'target': 'The local command adapter is the minimum required executable adapter', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_first_required_concrete_local_command_adapter_is_the_pi_headless_rpc_command_adapter', 'statement': 'The first required concrete local command adapter is the Pi headless RPC command adapter.', 'target': 'The first required concrete local command adapter is the Pi headless RPC command adapter', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_an_adapter_mode_is_selectable_configurable_it_must_actually_execute_verification_tasks', 'statement': 'If an adapter mode is selectable/configurable, it must actually execute verification tasks and pass health checks.', 'target': 'If an adapter mode is selectable/configurable, it must actually execute verification tasks and pass health checks', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_must_not_collect_http_or_provider_model_configuration_as_usable_when_that_adapt', 'statement': 'Spec Guard must not collect HTTP or provider/model configuration as usable when that adapter cannot be invoked.', 'target': 'Spec Guard must not collect HTTP or provider/model configuration as usable when that adapter cannot be invoked', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'required_semantic_verification_blocks_if_no_healthy_executable_adapter_is_configured', 'statement': 'Required semantic verification blocks if no healthy executable adapter is configured.', 'target': 'Required semantic verification blocks if no healthy executable adapter is configured', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'required_backend_verification_operates_on_registered_claims', 'statement': 'Required backend verification operates on registered claims.', 'target': 'Required backend verification operates on registered claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_must_create_or_derive_stable_claim_ids_before_calling_the_verifier', 'statement': 'Spec Guard must create or derive stable claim IDs before calling the verifier.', 'target': 'Spec Guard must create or derive stable claim IDs before calling the verifier', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'review_claims_is_only_the_review_final_subset_or_references_into_that_registry', 'statement': '`review.claims` is only the review/final subset or references into that registry.', 'target': '`review.claims` is only the review/final subset or references into that registry', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'docs_evidence_actions_register_docs_to_ac_mapping_claims_when_docs_are_required', 'statement': 'Docs evidence actions register docs-to-AC mapping claims when docs are required.', 'target': 'Docs evidence actions register docs-to-AC mapping claims when docs are required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_evidence_actions_register_docs_updated_semantic_claims_when_docs_are_required_docs_po', 'statement': 'Docs evidence actions register docs-updated semantic claims when docs are required, docs policy is `changed`, docs policy changes, docs evidence is added or updated, or docs files are changed.', 'target': 'Docs evidence actions register docs-updated semantic claims when docs are required, docs policy is `changed`, docs policy changes, docs evidence is added or upd', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_docs_add_work_docs_update_and_docs_policy_changes_through_work_update_must_register_o', 'statement': '`work.docs.add`, `work.docs.update`, and docs-policy changes through `work.update` must register or update stable pending `docs_updated` claims for affected docs/ACs.', 'target': '`work.docs.add`, `work.docs.update`, and docs-policy changes through `work.update` must register or update stable pending `docs_updated` claims for affected doc', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_preimplementation_validate_work_review_validate_and_work_review_complete_must_determi', 'statement': '`work.preimplementation.validate`, `work.review.validate`, and `work.review.complete` must deterministically detect docs/content file changes and docs policy triggers.', 'target': '`work.preimplementation.validate`, `work.review.validate`, and `work.review.complete` must deterministically detect docs/content file changes and docs policy tr', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_a_required_docs_updated_claim_is_missing_mutating_actions_may_register_a_stable_pending', 'statement': 'If a required `docs_updated` claim is missing, mutating actions may register a stable pending claim', 'target': 'If a required `docs_updated` claim is missing, mutating actions may register a stable pending claim', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'non_mutating_actions_must_return_the_derived_pending_claim_data_and_a_blocking_next_action', 'statement': 'non-mutating actions must return the derived pending claim data and a blocking next action.', 'target': 'non-mutating actions must return the derived pending claim data and a blocking next action', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'direct_docs_content_file_changes_without_docs_evidence_do_not_satisfy_docs_updated_require', 'statement': 'Direct docs/content file changes without docs evidence do not satisfy docs-updated requirements.', 'target': 'Direct docs/content file changes without docs evidence do not satisfy docs-updated requirements', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'test_failure_pass_evidence_actions_register_tests_to_ac_claims_and_when_docs_are_required', 'statement': 'Test failure/pass evidence actions register tests-to-AC claims and, when docs are required, behavior-tests-to-documented-contract claims.', 'target': 'Test failure/pass evidence actions register tests-to-AC claims and, when docs are required, behavior-tests-to-documented-contract claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'failure_evidence_actions_register_failure_evidence_semantic_claims_when_failure_first_evid', 'statement': 'Failure evidence actions register failure-evidence semantic claims when failure-first evidence is required.', 'target': 'Failure evidence actions register failure-evidence semantic claims when failure-first evidence is required', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'review_submission_records_register_implementation_summary_claims', 'statement': 'Review submission records register implementation summary claims.', 'target': 'Review submission records register implementation summary claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'registered_claims_must_include_claim_id_text_claim_type_related_acceptance_item_refs_related_docs_ids_wh', 'statement': 'Registered claims must include claim id, text, claim type, related AC IDs, related docs IDs when applicable, and evidence refs.', 'target': 'Registered claims must include claim id, text, claim type, related AC IDs, related docs IDs when applicable, and evidence refs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_backend_verify_must_reject_unknown_claim_ids', 'statement': '`work.backend.verify` must reject unknown claim IDs.', 'target': '`work.backend.verify` must reject unknown claim IDs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'behavior_tests_to_documented_contract_verification_means_semantic_verification_that_retain', 'statement': 'Behavior-tests-to-documented-contract verification means semantic verification that retained behavior tests exercise the product/API/runtime contract described by the docs.', 'target': 'Behavior-tests-to-documented-contract verification means semantic verification that retained behavior tests exercise the product/API/runtime contract described ', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_never_means_testing_documentation_files_documentation_text_headings_links_formatting_ex', 'statement': 'It never means testing documentation files, documentation text, headings, links, formatting, examples, or other documentation content directly.', 'target': 'It never means testing documentation files, documentation text, headings, links, formatting, examples, or other documentation content directly', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'optional_advisory_verification_may_exist_but_optional_verification_must_not_block_or_pass', 'statement': 'Optional advisory verification may exist, but optional verification must not block or pass gates unless a requirement in this table applies.', 'target': 'Optional advisory verification may exist, but optional verification must not block or pass gates unless a requirement in this table applies', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'only_executable_adapters_may_be_presented_as_normal_choices', 'statement': 'Only executable adapters may be presented as normal choices.', 'target': 'Only executable adapters may be presented as normal choices', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'command_adapter_config_must_collect', 'statement': 'Command adapter config must collect:', 'target': 'Command adapter config must collect:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_required_first_command_adapter_kind_is_pi_headless_rpc', 'statement': 'The required first command adapter kind is `pi_headless_rpc`.', 'target': 'The required first command adapter kind is `pi_headless_rpc`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implementations_must_allow_provider_model_override', 'statement': 'Implementations must allow provider/model override.', 'target': 'Implementations must allow provider/model override', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_non_thinking_authenticated_model_such_as_github_copilot_gpt_4_1_may_be_configured_but_th', 'statement': 'A non-thinking authenticated model such as `github-copilot` / `gpt-4.1` may be configured, but the adapter must work with thinking-capable models by filtering RPC events rather than relying on model choice.', 'target': 'A non-thinking authenticated model such as `github-copilot` / `gpt-4.1` may be configured, but the adapter must work with thinking-capable models by filtering R', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implemented_http_adapter_config_must_collect', 'statement': 'Implemented HTTP adapter config must collect:', 'target': 'Implemented HTTP adapter config must collect:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implemented_provider_model_adapter_config_must_collect', 'statement': 'Implemented provider/model adapter config must collect:', 'target': 'Implemented provider/model adapter config must collect:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'secrets_must_not_be_stored_directly', 'statement': 'Secrets must not be stored directly.', 'target': 'Secrets must not be stored directly', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'validates_response_shape', 'statement': 'validates response shape.', 'target': 'validates response shape', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'health_failure_blocks_required_semantic_verification', 'statement': 'Health failure blocks required semantic verification.', 'target': 'Health failure blocks required semantic verification', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'stderr_is_diagnostic_only', 'statement': 'Stderr is diagnostic-only', 'target': 'Stderr is diagnostic-only', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'must_not_be_parsed_as_verifier_output', 'statement': 'must not be parsed as verifier output.', 'target': 'must not be parsed as verifier output', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'must_still_pass_schema_validation', 'statement': 'must still pass schema validation.', 'target': 'must still pass schema validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'timeout_terminates_the_adapter_process_records_verifier_health_failure_for_that_run_and_sa', 'statement': 'Timeout terminates the adapter process, records verifier health failure for that run, and satisfies no gate.', 'target': 'Timeout terminates the adapter process, records verifier health failure for that run, and satisfies no gate', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_task_json_must_include_task_id_schema_version_submitted_claim_ids_text_deterministic_e', 'statement': 'The task JSON must include task id, schema version, submitted claim ids/text, deterministic evidence refs, human-approved refs, and prohibited judgment rules.', 'target': 'The task JSON must include task id, schema version, submitted claim ids/text, deterministic evidence refs, human-approved refs, and prohibited judgment rules', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_response_json_must_use_the_schema_in_section_13_5', 'statement': 'The response JSON must use the schema in section 13.5.', 'target': 'The response JSON must use the schema in section 13.5', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'start_pi_as_a_managed_child_process_with_pi_mode_rpc_no_session_no_tools_provider_provider', 'statement': 'Start Pi as a managed child process with `pi --mode rpc --no-session --no-tools --provider <provider> --model <model>`.', 'target': 'Start Pi as a managed child process with `pi --mode rpc --no-session --no-tools --provider <provider> --model <model>`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'record_process_metadata_under_spec_guard_runtime_storage', 'statement': 'Record process metadata under Spec Guard runtime storage', 'target': 'Record process metadata under Spec Guard runtime storage', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'expose_deterministic_start_status_prompt_stop_lifecycle_controls', 'statement': 'expose deterministic start/status/prompt/stop lifecycle controls.', 'target': 'expose deterministic start/status/prompt/stop lifecycle controls', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'concurrent_prompts_must_fail_with_a_deterministic_busy_error', 'statement': 'Concurrent prompts must fail with a deterministic busy error.', 'target': 'Concurrent prompts must fail with a deterministic busy error', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'collect_only_message_update_events_where_assistantmessageevent_type_is_text_delta', 'statement': 'Collect only `message_update` events where `assistantMessageEvent.type` is `text_delta`', 'target': 'Collect only `message_update` events where `assistantMessageEvent.type` is `text_delta`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'ignore_and_never_expose_thinking_start_thinking_delta_thinking_end_encrypted_thinking_sign', 'statement': 'Ignore and never expose `thinking_start`, `thinking_delta`, `thinking_end`, encrypted thinking signatures, partial thinking content, raw event streams, or tool events in adapter output.', 'target': 'Ignore and never expose `thinking_start`, `thinking_delta`, `thinking_end`, encrypted thinking signatures, partial thinking content, raw event streams, or tool ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'return_a_compact_json_envelope_with_adapter_id_pi_provider_model_final_text_optional_parse', 'statement': 'Return a compact JSON envelope with adapter id, Pi provider/model, final text, optional parsed JSON, diagnostics, and no hidden reasoning.', 'target': 'Return a compact JSON envelope with adapter id, Pi provider/model, final text, optional parsed JSON, diagnostics, and no hidden reasoning', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'health_check_sends_a_minimal_prompt_such_as_reply_with_only_the_answer_no_explanation_1_1', 'statement': 'Health check sends a minimal prompt such as `Reply with only the answer, no explanation: 1+1?` and expects final text `2` before `agent_end`.', 'target': 'Health check sends a minimal prompt such as `Reply with only the answer, no explanation: 1+1?` and expects final text `2` before `agent_end`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_adapter_is_advisory_verification_infrastructure_only', 'statement': 'The adapter is advisory verification infrastructure only', 'target': 'The adapter is advisory verification infrastructure only', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_must_not_bypass_spec_guard_human_gates_deterministic_checks_or_approval_semantics', 'statement': 'it must not bypass Spec Guard human gates, deterministic checks, or approval semantics.', 'target': 'it must not bypass Spec Guard human gates, deterministic checks, or approval semantics', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'verifier_task_input_must_separate', 'statement': 'Verifier task input must separate:', 'target': 'Verifier task input must separate:', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'verifier_response_must_include', 'statement': 'Verifier response must include:', 'target': 'Verifier response must include:', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'each_finding_must_target_one_of', 'statement': 'Each finding must target one of:', 'target': 'Each finding must target one of:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_finding_targeting_human_approved_reference_is_valid_only_when_it_says_an_agent_claim_con', 'statement': 'A finding targeting `human_approved_reference` is valid only when it says an agent claim conflicts with, exceeds, or lacks support from that reference.', 'target': 'A finding targeting `human_approved_reference` is valid only when it says an agent claim conflicts with, exceeds, or lacks support from that reference', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'failed_means_at_least_one_submitted_claim_id_is_in_contradicted_claim_ids_or_an_error_find', 'statement': '`failed` means at least one submitted claim id is in `contradicted_claim_ids`, or an error finding reports that a required claim is false or unsupported by the provided deterministic evidence.', 'target': '`failed` means at least one submitted claim id is in `contradicted_claim_ids`, or an error finding reports that a required claim is false or unsupported by the ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_kernel_must_not_parse_free_text_message_to_infer_prohibited_judgment', 'statement': 'The kernel must not parse free-text `message` to infer prohibited judgment.', 'target': 'The kernel must not parse free-text `message` to infer prohibited judgment', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'instead_it_validates_finding_kind_target_type_and_prohibited_human_intent_judgment_a_findi', 'statement': 'Instead, it validates `finding_kind`, `target_type`, and `prohibited_human_intent_judgment`: a finding targeting `human_approved_reference` is valid only with finding kind `claim_conflicts_with_reference`, `claim_exceeds_reference`, or `claim_unsupported_by_reference`', 'target': 'Instead, it validates `finding_kind`, `target_type`, and `prohibited_human_intent_judgment`: a finding targeting `human_approved_reference` is valid only with f', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_deterministic_kernel_must_mark_a_verifier_response_invalid_when', 'statement': 'The deterministic kernel must mark a verifier response invalid when:', 'target': 'The deterministic kernel must mark a verifier response invalid when:', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_fields_are_missing', 'statement': 'required fields are missing,', 'target': 'required fields are missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'verified_unverified_contradicted_claim_id_sets_are_not_pairwise_disjoint', 'statement': 'verified/unverified/contradicted claim ID sets are not pairwise disjoint,', 'target': 'verified/unverified/contradicted claim ID sets are not pairwise disjoint', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'for_passed_failed_or_inconclusive_responses_the_union_of_verified_unverified_and_contradic', 'statement': 'for `passed`, `failed`, or `inconclusive` responses, the union of verified, unverified, and contradicted claim IDs is not exactly the submitted claim ID set,', 'target': 'for `passed`, `failed`, or `inconclusive` responses, the union of verified, unverified, and contradicted claim IDs is not exactly the submitted claim ID set', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'invalid_responses_include_verified_unverified_or_contradicted_claim_ids_outside_the_submit', 'statement': 'invalid responses include verified, unverified, or contradicted claim IDs outside the submitted set,', 'target': 'invalid responses include verified, unverified, or contradicted claim IDs outside the submitted set', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'a_claim_is_omitted_from_all_three_sets_on_a_non_invalid_response', 'statement': 'a claim is omitted from all three sets on a non-invalid response,', 'target': 'a claim is omitted from all three sets on a non-invalid response', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'response_attempts_to_approve_reject_defer_change_or_reinterpret_human_intent', 'statement': 'response attempts to approve, reject, defer, change, or reinterpret human intent.', 'target': 'response attempts to approve, reject, defer, change, or reinterpret human intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_disabled', 'statement': 'Ordered requirement is supported/enforced: Disabled.', 'target': 'Ordered requirement is supported/enforced: Disabled', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_local_command_adapter', 'statement': 'Ordered requirement is supported/enforced: Local command adapter.', 'target': 'Ordered requirement is supported/enforced: Local command adapter', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_http_endpoint_adapter_optional_unless_implemente', 'statement': 'Ordered requirement is supported/enforced: HTTP endpoint adapter, optional unless implemented and exposed.', 'target': 'Ordered requirement is supported/enforced: HTTP endpoint adapter, optional unless implemented and exposed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_provider_model_adapter_optional_unless_implement', 'statement': 'Ordered requirement is supported/enforced: Provider/model adapter, optional unless implemented and exposed.', 'target': 'Ordered requirement is supported/enforced: Provider/model adapter, optional unless implemented and exposed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_test_fixture_adapter_for_spec_guard_s_own_tests', 'statement': "Ordered requirement is supported/enforced: Test fixture adapter for Spec Guard's own tests only.", 'target': "Ordered requirement is supported/enforced: Test fixture adapter for Spec Guard's own tests only", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_evidence_actions_register_docs_to_ac_mapping_cl', 'statement': 'Enumerated item is supported/enforced: Docs evidence actions register docs-to-AC mapping claims when docs are required.', 'target': 'Docs evidence actions register docs-to-AC mapping claims when docs are required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_evidence_actions_register_docs_updated_semantic', 'statement': 'Enumerated item is supported/enforced: Docs evidence actions register docs-updated semantic claims when docs are required, docs policy is `changed`, docs policy changes, docs evidence is added or updated, or docs files are changed.', 'target': 'Docs evidence actions register docs-updated semantic claims when docs are required, docs policy is `changed`, docs policy changes, docs evidence is added or upd', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_work_docs_add_work_docs_update_and_docs_policy_chang', 'statement': 'Enumerated item is supported/enforced: `work.docs.add`, `work.docs.update`, and docs-policy changes through `work.update` must register or update stable pending `docs_updated` claims for affected docs/ACs.', 'target': '`work.docs.add`, `work.docs.update`, and docs-policy changes through `work.update` must register or update stable pending `docs_updated` claims for affected doc', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_work_preimplementation_validate_work_review_validate', 'statement': 'Enumerated item is supported/enforced: `work.preimplementation.validate`, `work.review.validate`, and `work.review.complete` must deterministically detect docs/content file changes and docs policy triggers. If a required `docs_updated` claim is missing, mutating actions may register a stable pending claim; non-mutating actions must return the derived pending claim data and a blocking next action. Direct docs/content file changes without docs evidence do not satisfy docs-updated requirements.', 'target': '`work.preimplementation.validate`, `work.review.validate`, and `work.review.complete` must deterministically detect docs/content file changes and docs policy tr', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_test_failure_pass_evidence_actions_register_tests_to', 'statement': 'Enumerated item is supported/enforced: Test failure/pass evidence actions register tests-to-AC claims and, when docs are required, behavior-tests-to-documented-contract claims.', 'target': 'Test failure/pass evidence actions register tests-to-AC claims and, when docs are required, behavior-tests-to-documented-contract claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failure_evidence_actions_register_failure_evidence_s', 'statement': 'Enumerated item is supported/enforced: Failure evidence actions register failure-evidence semantic claims when failure-first evidence is required.', 'target': 'Failure evidence actions register failure-evidence semantic claims when failure-first evidence is required', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_evidence_actions_register_runtime_claims_for', 'statement': 'Enumerated item is supported/enforced: Runtime evidence actions register runtime claims for any semantic runtime assertion beyond exact command/path/status existence.', 'target': 'Runtime evidence actions register runtime claims for any semantic runtime assertion beyond exact command/path/status existence', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_submission_records_register_implementation_su', 'statement': 'Enumerated item is supported/enforced: Review submission records register implementation summary claims.', 'target': 'Review submission records register implementation summary claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_final_claim_validation_registers_final_user_facing_c', 'statement': 'Enumerated item is supported/enforced: Final claim validation registers final user-facing claims, including whether each is presented as verified or explicitly unverified.', 'target': 'Final claim validation registers final user-facing claims, including whether each is presented as verified or explicitly unverified', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_configure_backend_verifier_now', 'statement': 'Ordered requirement is supported/enforced: Configure backend verifier now', 'target': 'Ordered requirement is supported/enforced: Configure backend verifier now', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_leave_disabled_for_now', 'statement': 'Ordered requirement is supported/enforced: Leave disabled for now', 'target': 'Ordered requirement is supported/enforced: Leave disabled for now', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_discuss', 'statement': 'Ordered requirement is supported/enforced: Discuss', 'target': 'Ordered requirement is supported/enforced: Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_adapter_kind', 'statement': 'Enumerated item is supported/enforced: adapter kind,', 'target': 'adapter kind', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command', 'statement': 'Enumerated item is supported/enforced: command,', 'target': 'command', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_arguments', 'statement': 'Enumerated item is supported/enforced: arguments,', 'target': 'arguments', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_working_directory_behavior', 'statement': 'Enumerated item is supported/enforced: working directory behavior,', 'target': 'working directory behavior', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_timeout', 'statement': 'Enumerated item is supported/enforced: timeout,', 'target': 'timeout', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_environment_secret_setup_confirmation', 'statement': 'Enumerated item is supported/enforced: environment/secret setup confirmation,', 'target': 'environment/secret setup confirmation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_provider_model_fields_when_the_adapter_kind_manages', 'statement': 'Enumerated item is supported/enforced: provider/model fields when the adapter kind manages a model process.', 'target': 'provider/model fields when the adapter kind manages a model process', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_endpoint', 'statement': 'Enumerated item is supported/enforced: endpoint,', 'target': 'endpoint', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_auth_mechanism_or_credential_environment_variable_na', 'statement': 'Enumerated item is supported/enforced: auth mechanism or credential environment variable names,', 'target': 'auth mechanism or credential environment variable names', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_data_sharing_policy', 'statement': 'Enumerated item is supported/enforced: data-sharing policy.', 'target': 'data-sharing policy', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_provider_name', 'statement': 'Enumerated item is supported/enforced: provider name,', 'target': 'provider name', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_model_name', 'statement': 'Enumerated item is supported/enforced: model name,', 'target': 'model name', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_credential_environment_variable_name', 'statement': 'Enumerated item is supported/enforced: credential environment variable name,', 'target': 'credential environment variable name', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_spec_guard_executes_the_configured_command_with', 'statement': 'Ordered requirement is supported/enforced: Spec Guard executes the configured command with configured arguments and working directory.', 'target': 'Ordered requirement is supported/enforced: Spec Guard executes the configured command with configured arguments and working directory', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_the_verifier_task_is_written_as_one_utf_8_json_o', 'statement': 'Ordered requirement is supported/enforced: The verifier task is written as one UTF-8 JSON object to stdin, followed by LF.', 'target': 'Ordered requirement is supported/enforced: The verifier task is written as one UTF-8 JSON object to stdin, followed by LF', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_the_adapter_writes_exactly_one_utf_8_json_verifi', 'statement': 'Ordered requirement is supported/enforced: The adapter writes exactly one UTF-8 JSON verifier response object to stdout. Additional stdout after the first complete JSON object is invalid.', 'target': 'Ordered requirement is supported/enforced: The adapter writes exactly one UTF-8 JSON verifier response object to stdout. Additional stdout after the first compl', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_stderr_is_diagnostic_only_and_must_not_be_parsed', 'statement': 'Ordered requirement is supported/enforced: Stderr is diagnostic-only and must not be parsed as verifier output.', 'target': 'Ordered requirement is supported/enforced: Stderr is diagnostic-only and must not be parsed as verifier output', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_exit_code_0_means_a_response_was_produced_and_mu', 'statement': 'Ordered requirement is supported/enforced: Exit code `0` means a response was produced and must still pass schema validation. Non-zero exit code means adapter failure and no gate is satisfied, even if stdout contains JSON.', 'target': 'Ordered requirement is supported/enforced: Exit code `0` means a response was produced and must still pass schema validation. Non-zero exit code means adapter f', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_timeout_terminates_the_adapter_process_records_v', 'statement': 'Ordered requirement is supported/enforced: Timeout terminates the adapter process, records verifier health failure for that run, and satisfies no gate.', 'target': 'Ordered requirement is supported/enforced: Timeout terminates the adapter process, records verifier health failure for that run, and satisfies no gate', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_the_task_json_must_include_task_id_schema_versio', 'statement': 'Ordered requirement is supported/enforced: The task JSON must include task id, schema version, submitted claim ids/text, deterministic evidence refs, human-approved refs, and prohibited judgment rules. The response JSON must use the schema in section 13.5.', 'target': 'Ordered requirement is supported/enforced: The task JSON must include task id, schema version, submitted claim ids/text, deterministic evidence refs, human-appr', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_start_pi_as_a_managed_child_process_with_pi_mode', 'statement': 'Ordered requirement is supported/enforced: Start Pi as a managed child process with `pi --mode rpc --no-session --no-tools --provider <provider> --model <model>`.', 'target': 'Ordered requirement is supported/enforced: Start Pi as a managed child process with `pi --mode rpc --no-session --no-tools --provider <provider> --model <model>', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_default_provider_is_openai_codex_default_model_i', 'statement': 'Ordered requirement is supported/enforced: Default `provider` is `openai-codex`; default `model` is `gpt-5.4-mini`.', 'target': 'Ordered requirement is supported/enforced: Default `provider` is `openai-codex`; default `model` is `gpt-5.4-mini`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_record_process_metadata_under_spec_guard_runtime', 'statement': 'Ordered requirement is supported/enforced: Record process metadata under Spec Guard runtime storage and expose deterministic start/status/prompt/stop lifecycle controls.', 'target': 'Ordered requirement is supported/enforced: Record process metadata under Spec Guard runtime storage and expose deterministic start/status/prompt/stop lifecycle ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_accept_one_prompt_at_a_time_concurrent_prompts_m', 'statement': 'Ordered requirement is supported/enforced: Accept one prompt at a time. Concurrent prompts must fail with a deterministic busy error.', 'target': 'Ordered requirement is supported/enforced: Accept one prompt at a time. Concurrent prompts must fail with a deterministic busy error', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_send_prompts_to_pi_rpc_as_strict_jsonl_using_lf', 'statement': 'Ordered requirement is supported/enforced: Send prompts to Pi RPC as strict JSONL using LF framing: `{ "type": "prompt", "message": "..." }`.', 'target': 'Ordered requirement is supported/enforced: Send prompts to Pi RPC as strict JSONL using LF framing: `{ "type": "prompt", "message": "..." }`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_collect_only_message_update_events_where_assista', 'statement': 'Ordered requirement is supported/enforced: Collect only `message_update` events where `assistantMessageEvent.type` is `text_delta`; concatenate their `delta` strings until `agent_end`.', 'target': 'Ordered requirement is supported/enforced: Collect only `message_update` events where `assistantMessageEvent.type` is `text_delta`; concatenate their `delta` st', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_ignore_and_never_expose_thinking_start_thinking', 'statement': 'Ordered requirement is supported/enforced: Ignore and never expose `thinking_start`, `thinking_delta`, `thinking_end`, encrypted thinking signatures, partial thinking content, raw event streams, or tool events in adapter output.', 'target': 'Ordered requirement is supported/enforced: Ignore and never expose `thinking_start`, `thinking_delta`, `thinking_end`, encrypted thinking signatures, partial th', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_return_a_compact_json_envelope_with_adapter_id_p', 'statement': 'Ordered requirement is supported/enforced: Return a compact JSON envelope with adapter id, Pi provider/model, final text, optional parsed JSON, diagnostics, and no hidden reasoning.', 'target': 'Ordered requirement is supported/enforced: Return a compact JSON envelope with adapter id, Pi provider/model, final text, optional parsed JSON, diagnostics, and', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_health_check_sends_a_minimal_prompt_such_as_repl', 'statement': 'Ordered requirement is supported/enforced: Health check sends a minimal prompt such as `Reply with only the answer, no explanation: 1+1?` and expects final text `2` before `agent_end`.', 'target': 'Ordered requirement is supported/enforced: Health check sends a minimal prompt such as `Reply with only the answer, no explanation: 1+1?` and expects final text', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_the_adapter_is_advisory_verification_infrastruct', 'statement': 'Ordered requirement is supported/enforced: The adapter is advisory verification infrastructure only; it must not bypass Spec Guard human gates, deterministic checks, or approval semantics.', 'target': 'Ordered requirement is supported/enforced: The adapter is advisory verification infrastructure only; it must not bypass Spec Guard human gates, deterministic ch', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_claim_ids_and_claim_text', 'statement': 'Enumerated item is supported/enforced: claim IDs and claim text,', 'target': 'claim IDs and claim text', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_deterministic_evidence', 'statement': 'Enumerated item is supported/enforced: deterministic evidence,', 'target': 'deterministic evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_human_approved_references_as_immutable_constraints', 'statement': 'Enumerated item is supported/enforced: human-approved references as immutable constraints,', 'target': 'human-approved references as immutable constraints', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_prohibited_judgment_rules', 'statement': 'Enumerated item is supported/enforced: prohibited judgment rules.', 'target': 'prohibited judgment rules', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_task_id', 'statement': 'Enumerated item is supported/enforced: task id,', 'target': 'task id', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_schema_version', 'statement': 'Enumerated item is supported/enforced: schema version,', 'target': 'schema version', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_status_passed_failed_or_inconclusive', 'statement': 'Enumerated item is supported/enforced: status: `passed`, `failed`, or `inconclusive`,', 'target': 'status: `passed`, `failed`, or `inconclusive`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_findings', 'statement': 'Enumerated item is supported/enforced: findings,', 'target': 'findings', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verified_claim_ids', 'statement': 'Enumerated item is supported/enforced: verified claim IDs,', 'target': 'verified claim IDs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_unverified_claim_ids', 'statement': 'Enumerated item is supported/enforced: unverified claim IDs,', 'target': 'unverified claim IDs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_contradicted_claim_ids', 'statement': 'Enumerated item is supported/enforced: contradicted claim IDs,', 'target': 'contradicted claim IDs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_prohibited_human_intent_judgment_detected_boolean', 'statement': 'Enumerated item is supported/enforced: `prohibited_human_intent_judgment_detected` boolean.', 'target': '`prohibited_human_intent_judgment_detected` boolean', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_agent_claim', 'statement': 'Enumerated item is supported/enforced: `agent_claim`,', 'target': '`agent_claim`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_evidence_mapping', 'statement': 'Enumerated item is supported/enforced: `evidence_mapping`,', 'target': '`evidence_mapping`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_deterministic_reference', 'statement': 'Enumerated item is supported/enforced: `deterministic_reference`,', 'target': '`deterministic_reference`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_human_approved_reference', 'statement': 'Enumerated item is supported/enforced: `human_approved_reference`.', 'target': '`human_approved_reference`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_passed_means_every_submitted_claim_id_is_in_verified', 'statement': 'Enumerated item is supported/enforced: `passed` means every submitted claim id is in `verified_claim_ids`, `unverified_claim_ids` and `contradicted_claim_ids` are empty, and no finding has severity `error`.', 'target': '`passed` means every submitted claim id is in `verified_claim_ids`, `unverified_claim_ids` and `contradicted_claim_ids` are empty, and no finding has severity `', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failed_means_at_least_one_submitted_claim_id_is_in_c', 'statement': 'Enumerated item is supported/enforced: `failed` means at least one submitted claim id is in `contradicted_claim_ids`, or an error finding reports that a required claim is false or unsupported by the provided deterministic evidence.', 'target': '`failed` means at least one submitted claim id is in `contradicted_claim_ids`, or an error finding reports that a required claim is false or unsupported by the ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_inconclusive_means_at_least_one_submitted_claim_id_i', 'statement': 'Enumerated item is supported/enforced: `inconclusive` means at least one submitted claim id is in `unverified_claim_ids` and no submitted claim id is contradicted.', 'target': '`inconclusive` means at least one submitted claim id is in `unverified_claim_ids` and no submitted claim id is contradicted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_fields_are_missing', 'statement': 'Enumerated item is supported/enforced: required fields are missing,', 'target': 'required fields are missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verified_unverified_contradicted_claim_id_sets_are_n', 'statement': 'Enumerated item is supported/enforced: verified/unverified/contradicted claim ID sets are not pairwise disjoint,', 'target': 'verified/unverified/contradicted claim ID sets are not pairwise disjoint', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_for_passed_failed_or_inconclusive_responses_the_unio', 'statement': 'Enumerated item is supported/enforced: for `passed`, `failed`, or `inconclusive` responses, the union of verified, unverified, and contradicted claim IDs is not exactly the submitted claim ID set,', 'target': 'for `passed`, `failed`, or `inconclusive` responses, the union of verified, unverified, and contradicted claim IDs is not exactly the submitted claim ID set', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_invalid_responses_include_verified_unverified_or_con', 'statement': 'Enumerated item is supported/enforced: invalid responses include verified, unverified, or contradicted claim IDs outside the submitted set,', 'target': 'invalid responses include verified, unverified, or contradicted claim IDs outside the submitted set', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_a_claim_is_omitted_from_all_three_sets_on_a_non_inva', 'statement': 'Enumerated item is supported/enforced: a claim is omitted from all three sets on a non-invalid response,', 'target': 'a claim is omitted from all three sets on a non-invalid response', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_an_inconclusive_claim_is_not_listed_in_unverified_cl', 'statement': 'Enumerated item is supported/enforced: an inconclusive claim is not listed in `unverified_claim_ids`,', 'target': 'an inconclusive claim is not listed in `unverified_claim_ids`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_findings_judge_human_approved_intent', 'statement': 'Enumerated item is supported/enforced: findings judge human-approved intent,', 'target': 'findings judge human-approved intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_response_attempts_to_approve_reject_defer_change_or', 'statement': 'Enumerated item is supported/enforced: response attempts to approve, reject, defer, change, or reinterpret human intent.', 'target': 'response attempts to approve, reject, defer, change, or reinterpret human intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_docs_to_ac_mapping_for_api_contract_surface_packets', 'statement': 'Table row is implemented: Claim or fact: Docs-to-AC mapping for API/contract-surface packets; Backend verification: Required', 'target': 'Claim or fact: Docs-to-AC mapping for API/contract-surface packets; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_behavior_tests_to_documented_contract_mapping_for_a', 'statement': 'Table row is implemented: Claim or fact: Behavior-tests-to-documented-contract mapping for API/contract-surface packets; Backend verification: Required', 'target': 'Claim or fact: Behavior-tests-to-documented-contract mapping for API/contract-surface packets; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_docs_to_ac_mapping_for_non_api_docs_required_packet', 'statement': 'Table row is implemented: Claim or fact: Docs-to-AC mapping for non-API docs-required packets; Backend verification: Required', 'target': 'Claim or fact: Docs-to-AC mapping for non-API docs-required packets; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_behavior_tests_to_documented_contract_mapping_for_n', 'statement': 'Table row is implemented: Claim or fact: Behavior-tests-to-documented-contract mapping for non-API docs-required packets; Backend verification: Required', 'target': 'Claim or fact: Behavior-tests-to-documented-contract mapping for non-API docs-required packets; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_tests_to_ac_mapping_for_non_api_packets_backend_ver', 'statement': 'Table row is implemented: Claim or fact: Tests-to-AC mapping for non-API packets; Backend verification: Required when tests are required', 'target': 'Claim or fact: Tests-to-AC mapping for non-API packets; Backend verification: Required when tests are required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_failure_evidence_semantic_claim_used_to_prove_missi', 'statement': 'Table row is implemented: Claim or fact: Failure evidence semantic claim used to prove missing approved behavior; Backend verification: Required when failure-first evidence is required', 'target': 'Claim or fact: Failure evidence semantic claim used to prove missing approved behavior; Backend verification: Required when failure-first evidence is required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_retained_test_is_not_documentation_targeting_retain', 'statement': 'Table row is implemented: Claim or fact: Retained test is not documentation-targeting (`retained_test_not_docs`); Backend verification: Required when retained-doc-test detection is inconclusive', 'target': 'Claim or fact: Retained test is not documentation-targeting (`retained_test_not_docs`); Backend verification: Required when retained-doc-test detection is incon', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_runtime_claim_beyond_exact_command_path_status_exis', 'statement': 'Table row is implemented: Claim or fact: Runtime claim beyond exact command/path/status existence; Backend verification: Required', 'target': 'Claim or fact: Runtime claim beyond exact command/path/status existence; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_final_user_facing_claim_presented_as_verified_compl', 'statement': 'Table row is implemented: Claim or fact: Final user-facing claim presented as verified/completed; Backend verification: Required', 'target': 'Claim or fact: Final user-facing claim presented as verified/completed; Backend verification: Required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_final_user_facing_claim_explicitly_marked_unverifie', 'statement': 'Table row is implemented: Claim or fact: Final user-facing claim explicitly marked unverified; Backend verification: No semantic support verification; deterministic label validation required', 'target': 'Claim or fact: Final user-facing claim explicitly marked unverified; Backend verification: No semantic support verification; deterministic label validation requ', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_implementation_summary_claim_backend_verification_r', 'statement': 'Table row is implemented: Claim or fact: Implementation summary claim; Backend verification: Required for review completion', 'target': 'Claim or fact: Implementation summary claim; Backend verification: Required for review completion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_docs_updated_semantic_claim_backend_verification_re', 'statement': 'Table row is implemented: Claim or fact: Docs-updated semantic claim; Backend verification: Required when docs are required or changed', 'target': 'Claim or fact: Docs-updated semantic claim; Backend verification: Required when docs are required or changed', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_file_existence_backend_verification_never_determini', 'statement': 'Table row is implemented: Claim or fact: File existence; Backend verification: Never; deterministic', 'target': 'Claim or fact: File existence; Backend verification: Never; deterministic', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_path_safety_backend_verification_never_deterministi', 'statement': 'Table row is implemented: Claim or fact: Path safety; Backend verification: Never; deterministic', 'target': 'Claim or fact: Path safety; Backend verification: Never; deterministic', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_changed_file_list_backend_verification_never_determ', 'statement': 'Table row is implemented: Claim or fact: Changed-file list; Backend verification: Never; deterministic', 'target': 'Claim or fact: Changed-file list; Backend verification: Never; deterministic', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_command_exit_code_status_existence_backend_verifica', 'statement': 'Table row is implemented: Claim or fact: Command exit code/status existence; Backend verification: Never; deterministic', 'target': 'Claim or fact: Command exit code/status existence; Backend verification: Never; deterministic', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_package_script_existence_backend_verification_never', 'statement': 'Table row is implemented: Claim or fact: Package script existence; Backend verification: Never; deterministic', 'target': 'Claim or fact: Package script existence; Backend verification: Never; deterministic', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_approval_hash_freshness_backend_verification_never', 'statement': 'Table row is implemented: Claim or fact: Approval hash freshness; Backend verification: Never; deterministic', 'target': 'Claim or fact: Approval hash freshness; Backend verification: Never; deterministic', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_claim_or_fact_human_approved_intent_quality_completeness_correctn', 'statement': 'Table row is implemented: Claim or fact: Human-approved intent quality/completeness/correctness; Backend verification: Never; prohibited', 'target': 'Claim or fact: Human-approved intent quality/completeness/correctness; Backend verification: Never; prohibited', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
