"""Executable specification for US-11: Plan lifecycle and batch acceleration."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'before_asking_whether_work_should_be_a_single_packet_or_a_plan_the_frontend_agent_must_pre', 'statement': 'Before asking whether work should be a single packet or a Plan, the frontend agent must present relevant ACs unless already in a valid Plan flow.', 'target': 'Before asking whether work should be a single packet or a Plan, the frontend agent must present relevant ACs unless already in a valid Plan flow', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'create_a_plan', 'statement': 'Create a Plan', 'target': 'Create a Plan', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'option_1_records_single_packet_decision_and_leaves_the_source_work_packet_active', 'statement': 'Option 1 records single-packet decision and leaves the source Work Packet active.', 'target': 'Option 1 records single-packet decision and leaves the source Work Packet active', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'option_2_records_plan_decision_sets_the_source_work_packet_to_deferred_with_diagnostics_po', 'statement': 'Option 2 records Plan decision, sets the source Work Packet to `deferred` with diagnostics pointing to the Plan flow, and later Plan approval records `source_work_id` on the Plan.', 'target': 'Option 2 records Plan decision, sets the source Work Packet to `deferred` with diagnostics pointing to the Plan flow, and later Plan approval records `source_wo', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'if_plan_approval_is_declined_or_no_plan_is_created_spec_guard_restores_the_source_work_pac', 'statement': 'If Plan approval is declined or no Plan is created, Spec Guard restores the source Work Packet to its pre-deferral status', 'target': 'If Plan approval is declined or no Plan is created, Spec Guard restores the source Work Packet to its pre-deferral status', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'records_diagnostics_linking_the_declined_plan_attempt', 'statement': 'records diagnostics linking the declined Plan attempt.', 'target': 'records diagnostics linking the declined Plan attempt', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'option_3_mutates_nothing_creates_no_humandecision_and_re_prompts_later', 'statement': 'Option 3 mutates nothing, creates no HumanDecision, and re-prompts later.', 'target': 'Option 3 mutates nothing, creates no HumanDecision, and re-prompts later', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'no_something_else_custom_option_is_allowed', 'statement': 'No Something else/custom option is allowed.', 'target': 'No Something else/custom option is allowed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_decision_must_be_recorded_through_work_plan_choice_answer', 'statement': 'The decision must be recorded through `work.plan_choice.answer`.', 'target': 'The decision must be recorded through `work.plan_choice.answer`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_not_be_recorded_through_generic_decision_create_because_option_2_has_the_side_effe', 'statement': 'It must not be recorded through generic `decision.create`, because option 2 has the side effect of deferring the source Work Packet.', 'target': 'It must not be recorded through generic `decision.create`, because option 2 has the side effect of deferring the source Work Packet', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_recorded_humandecision_must_store_a_canonical_planvssingledecisionpayload_in_approved', 'statement': 'The recorded HumanDecision must store a canonical PlanVsSingleDecisionPayload in `approved_payload` with the work id, selected option, the exact AC payload presented before the decision, and its hash.', 'target': 'The recorded HumanDecision must store a canonical PlanVsSingleDecisionPayload in `approved_payload` with the work id, selected option, the exact AC payload pres', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_returns_a_proposed_plan_review_snapshot_for_that_exact_payload', 'statement': 'It returns a proposed Plan review snapshot for that exact payload.', 'target': 'It returns a proposed Plan review snapshot for that exact payload', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_does_not_create_a_plan', 'statement': 'It does not create a Plan', 'target': 'It does not create a Plan', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'does_not_create_children', 'statement': 'does not create children.', 'target': 'does not create children', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'every_slice_proposed_id_must_match_a_za_z0_9', 'statement': 'Every slice `proposed_id` must match `^[A-Za-z0-9._-]+$`', 'target': 'Every slice `proposed_id` must match `^[A-Za-z0-9._-]+$`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_propose_and_plan_approve_must_reject_plan_proposals_with_proposed_ids_that_cannot_be', 'statement': '`plan.propose` and `plan.approve` must reject Plan proposals with proposed ids that cannot be used safely in batch child snapshot revisions.', 'target': '`plan.propose` and `plan.approve` must reject Plan proposals with proposed ids that cannot be used safely in batch child snapshot revisions', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'every_plan_slice_must_include_at_least_one_full_acceptancecriterion_payload', 'statement': 'Every Plan slice must include at least one full AcceptanceCriterion payload.', 'target': 'Every Plan slice must include at least one full AcceptanceCriterion payload', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'any_plan_slice_containing_source_derived_acs_must_include_full_ac_payloads_not_only_acceptance_item_refs', 'statement': 'Any Plan slice containing source-derived ACs must include full AC payloads, not only AC ids, and each source-derived AC must include SourceEvidence with non-empty canonical `source_artifact_refs` and `evidence_hash`.', 'target': 'Any Plan slice containing source-derived ACs must include full AC payloads, not only AC ids, and each source-derived AC must include SourceEvidence with non-emp', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_plan_proposal_is_shown_to_the_human_with', 'statement': 'The Plan proposal is shown to the human with:', 'target': 'The Plan proposal is shown to the human with:', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'spec_guard_validates_that_the_submitted_payload_hashes_to_the_supplied_snapshot_hash', 'statement': 'Spec Guard validates that the submitted payload hashes to the supplied snapshot hash.', 'target': 'Spec Guard validates that the submitted payload hashes to the supplied snapshot hash', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'any_top_level_source_work_id_action_input_must_equal_the_payload_field', 'statement': 'any top-level `source_work_id` action input must equal the payload field.', 'target': 'any top-level `source_work_id` action input must equal the payload field', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'numbered_yes_records_plan_approval', 'statement': 'Numbered Yes records Plan approval', 'target': 'Numbered Yes records Plan approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'creates_a_non_implementable_plan_containing_the_approved_slices_source_work_id_and_metadat', 'statement': 'creates a non-implementable Plan containing the approved slices, `source_work_id`, and metadata.', 'target': 'creates a non-implementable Plan containing the approved slices, `source_work_id`, and metadata', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'plan_approval_does_not_create_child_work_packets', 'statement': 'Plan approval does not create child Work Packets.', 'target': 'Plan approval does not create child Work Packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_created_plan_stores_the_approved_planproposalpayload_as_plan_proposal', 'statement': 'The created Plan stores the approved PlanProposalPayload as `plan_proposal`', 'target': 'The created Plan stores the approved PlanProposalPayload as `plan_proposal`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'stores_the_plan_approval_humandecision_outside_plan_proposal', 'statement': 'stores the Plan approval HumanDecision outside `plan_proposal`.', 'target': 'stores the Plan approval HumanDecision outside `plan_proposal`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'numbered_no_records_a_standalone_decline_humandecision_or_project_level_decision_log_entry', 'statement': 'Numbered No records a standalone decline HumanDecision or project-level decision-log entry', 'target': 'Numbered No records a standalone decline HumanDecision or project-level decision-log entry', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'creates_no_plan', 'statement': 'creates no Plan.', 'target': 'creates no Plan', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'discuss_records_no_mutation_and_later_re_presents_the_same_gate_for_the_current_or_revised', 'statement': 'Discuss records no mutation and later re-presents the same gate for the current or revised proposal.', 'target': 'Discuss records no mutation and later re-presents the same gate for the current or revised proposal', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'after_plan_approval_batch_proceed_or_one_at_a_time_child_creation_creates_child_work_packe', 'statement': 'After Plan approval, batch proceed or one-at-a-time child creation creates child Work Packets from the approved Plan.', 'target': 'After Plan approval, batch proceed or one-at-a-time child creation creates child Work Packets from the approved Plan', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'one_at_a_time_child_creation_uses_plan_child_create', 'statement': 'One-at-a-time child creation uses `plan.child.create`.', 'target': 'One-at-a-time child creation uses `plan.child.create`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_action_must_reference_the_approved_plan_id_the_approved_plan_proposal_hash_snapshot_re', 'statement': 'The action must reference the approved Plan id, the approved Plan proposal hash/snapshot revision, a `plan_slice_id` from the approved Plan, and the proposed child payload.', 'target': 'The action must reference the approved Plan id, the approved Plan proposal hash/snapshot revision, a `plan_slice_id` from the approved Plan, and the proposed ch', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_must_validate_that_the_child_payload_corresponds_to_the_approved_plan_slice_bef', 'statement': 'Spec Guard must validate that the child payload corresponds to the approved Plan slice before creating the Work Packet.', 'target': 'Spec Guard must validate that the child payload corresponds to the approved Plan slice before creating the Work Packet', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'proposed_child_id_must_equal_plan_slice_id', 'statement': '`proposed_child_id` must equal `plan_slice_id`', 'target': '`proposed_child_id` must equal `plan_slice_id`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'alternate_child_id_mappings_are_not_supported_by_this_specification', 'statement': 'alternate child id mappings are not supported by this specification.', 'target': 'alternate child id mappings are not supported by this specification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'child_payload_correspondence_requires_exact_match_between_plan_slice_id_and_an_approved_pl', 'statement': 'Child payload correspondence requires exact match between `plan_slice_id` and an approved Plan slice `proposed_id`, requires `proposed_work_payload.id` to equal `plan_slice_id`,', 'target': 'Child payload correspondence requires exact match between `plan_slice_id` and an approved Plan slice `proposed_id`, requires `proposed_work_payload.id` to equal', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'requires_exact_match_for_title_goal_classification_docs_policy_allowed_globs_source_derive', 'statement': 'requires exact match for title, goal, classification, docs policy, allowed globs, source-derived flag, source evidence summary, and full AcceptanceCriterion payloads recorded in the approved Plan proposal.', 'target': 'requires exact match for title, goal, classification, docs policy, allowed globs, source-derived flag, source evidence summary, and full AcceptanceCriterion pay', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'desired_outcomes_in_scope_out_of_scope_users_actors_edge_cases_and_open_questions_in_propo', 'statement': 'Desired outcomes, in-scope, out-of-scope, users/actors, edge cases, and open questions in ProposedWorkPacketPayload must exactly match the corresponding approved Plan slice arrays.', 'target': 'Desired outcomes, in-scope, out-of-scope, users/actors, edge cases, and open questions in ProposedWorkPacketPayload must exactly match the corresponding approve', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'platform_and_architecture_may_be_copied_from_approved_plan_product_context_only_when_that', 'statement': 'Platform and architecture may be copied from approved Plan product context only when that context contains prior platform/architecture HumanDecision ids', 'target': 'Platform and architecture may be copied from approved Plan product context only when that context contains prior platform/architecture HumanDecision ids', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'otherwise_they_must_remain_unset_until_the_child_records_its_own_platform_architecture_dec', 'statement': 'otherwise they must remain unset until the child records its own platform/architecture decisions.', 'target': 'otherwise they must remain unset until the child records its own platform/architecture decisions', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'runtime_baseline_ref_may_be_null_at_create_only_child_creation_time', 'statement': '`runtime_baseline_ref` may be null at create-only child creation time', 'target': '`runtime_baseline_ref` may be null at create-only child creation time', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'any_non_null_runtime_baseline_ref_must_reference_an_accepted_baseline_and_packet_approval', 'statement': 'any non-null runtime baseline ref must reference an accepted baseline, and packet approval or authorization readiness requires an accepted runtime baseline ref.', 'target': 'any non-null runtime baseline ref must reference an accepted baseline, and packet approval or authorization readiness requires an accepted runtime baseline ref', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_created_workpacket_must_durably_store_parent_plan_id_and_plan_slice_id', 'statement': 'The created WorkPacket must durably store `parent_plan_id` and `plan_slice_id`.', 'target': 'The created WorkPacket must durably store `parent_plan_id` and `plan_slice_id`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implementations_must_not_create_a_child_with_broader_scope_different_classification_differ', 'statement': 'Implementations must not create a child with broader scope, different classification, different docs policy, or additional ACs through `plan.child.create`', 'target': 'Implementations must not create a child with broader scope, different classification, different docs policy, or additional ACs through `plan.child.create`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'such_changes_require_plan_amendment_or_a_separate_work_packet_approval_path', 'statement': 'such changes require Plan amendment or a separate Work Packet approval path.', 'target': 'such changes require Plan amendment or a separate Work Packet approval path', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_backend_verifier_must_not_judge_whether_the_plan_proposal_is_good_complete_or_optimal', 'statement': 'The backend verifier must not judge whether the Plan proposal is good, complete, or optimal.', 'target': 'The backend verifier must not judge whether the Plan proposal is good, complete, or optimal', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'before_a_batch_proceed_decision_plan_batch_snapshot_create_must_receive_a_proposed_childre', 'statement': 'Before a batch proceed decision, `plan.batch_snapshot.create` must receive a `proposed_children_payload` that expands approved Plan slices into proposed child Work Packet payloads.', 'target': 'Before a batch proceed decision, `plan.batch_snapshot.create` must receive a `proposed_children_payload` that expands approved Plan slices into proposed child W', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'each_proposed_child_entry_must_include_plan_slice_id_proposed_child_id_expected_created_wo', 'statement': 'Each proposed child entry must include `plan_slice_id`, `proposed_child_id`, `expected_created_work_packet_revision`, canonical `proposed_work_payload`, and caller-proposed readiness diagnostics.', 'target': 'Each proposed child entry must include `plan_slice_id`, `proposed_child_id`, `expected_created_work_packet_revision`, canonical `proposed_work_payload`, and cal', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_batch_snapshot_create_must_recompute_readiness_and_eligibility_through_the_determinis', 'statement': '`plan.batch_snapshot.create` must recompute readiness and eligibility through the deterministic kernel, replace caller-proposed readiness fields with kernel-computed values in the persisted BatchReviewSnapshot,', 'target': '`plan.batch_snapshot.create` must recompute readiness and eligibility through the deterministic kernel, replace caller-proposed readiness fields with kernel-com', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'reject_only_when_the_proposed_child_payload_itself_is_invalid', 'statement': 'reject only when the proposed child payload itself is invalid', 'target': 'reject only when the proposed child payload itself is invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'plan_slice_id_must_match_an_approved_plan_slice_proposed_id_proposed_child_id_must_equal_p', 'statement': '`plan_slice_id` must match an approved Plan slice `proposed_id`, `proposed_child_id` must equal `plan_slice_id`, `proposed_work_payload.id` must equal `proposed_child_id`, and `proposed_work_payload.title` must match the approved Plan slice title.', 'target': '`plan_slice_id` must match an approved Plan slice `proposed_id`, `proposed_child_id` must equal `plan_slice_id`, `proposed_work_payload.id` must equal `proposed', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'batch_child_correspondence_must_enforce_the_same_approved_plan_slice_constraints_as_plan_c', 'statement': 'Batch child correspondence must enforce the same approved Plan slice constraints as `plan.child.create`: title, goal, classification, docs policy, allowed globs, source-derived flag, source evidence summary, and full AcceptanceCriterion payloads must match the approved Plan slice.', 'target': 'Batch child correspondence must enforce the same approved Plan slice constraints as `plan.child.create`: title, goal, classification, docs policy, allowed globs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_batch_snapshot_create_must_reject_a_proposed_child_that_broadens_scope_changes_classi', 'statement': '`plan.batch_snapshot.create` must reject a proposed child that broadens scope, changes classification, changes docs policy, changes source-derived status, changes source evidence summary, adds ACs, or otherwise fails correspondence with the approved Plan slice.', 'target': '`plan.batch_snapshot.create` must reject a proposed child that broadens scope, changes classification, changes docs policy, changes source-derived status, chang', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'plan_batch_snapshot_create_derives_source_artifact_refs_deterministically_as_a_canonical_s', 'statement': '`plan.batch_snapshot.create` derives `source_artifact_refs` deterministically as a canonical set.', 'target': '`plan.batch_snapshot.create` derives `source_artifact_refs` deterministically as a canonical set', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_set_is_the_union_of_the_approved_plan_artifact_ref_top_level_proposed_children_payload', 'statement': "The set is the union of: the approved Plan artifact ref, top-level `proposed_children_payload.source_artifact_refs`, each proposed child's provenance refs, and each proposed source-derived AC SourceEvidence `source_artifact_refs`.", 'target': "The set is the union of: the approved Plan artifact ref, top-level `proposed_children_payload.source_artifact_refs`, each proposed child's provenance refs, and ", 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'duplicate_refs_are_removed_by_exact_tuple_identity_artifact_type_id_revision', 'statement': 'Duplicate refs are removed by exact tuple identity `(artifact_type, id, revision)`.', 'target': 'Duplicate refs are removed by exact tuple identity `(artifact_type, id, revision)`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'plan_batch_snapshot_create_must_apply_appendix_a_canonical_sourceartifactref_ordering_when', 'statement': '`plan.batch_snapshot.create` must apply Appendix A canonical SourceArtifactRef ordering when deriving source artifact refs.', 'target': '`plan.batch_snapshot.create` must apply Appendix A canonical SourceArtifactRef ordering when deriving source artifact refs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'snapshot_hashing_must_use_this_canonical_array', 'statement': 'Snapshot hashing must use this canonical array.', 'target': 'Snapshot hashing must use this canonical array', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'at_snapshot_creation_and_decision_validation_every_listed_ref_must_resolve_and_any_supplie', 'statement': 'At snapshot creation and decision validation, every listed ref must resolve and any supplied content hash must match.', 'target': 'At snapshot creation and decision validation, every listed ref must resolve and any supplied content hash must match', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'later_approval_invalidation_treats_only_refs_that_also_appear_in_approved_source_derived_a', 'statement': 'Later approval invalidation treats only refs that also appear in approved source-derived AC SourceEvidence as governed source dependencies.', 'target': 'Later approval invalidation treats only refs that also appear in approved source-derived AC SourceEvidence as governed source dependencies', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'top_level_and_child_level_provenance_only_refs_becoming_unavailable_after_approval_create', 'statement': 'Top-level and child-level provenance-only refs becoming unavailable after approval create replay diagnostics but do not stale AC approval, Work Packet approval, Plan approval, or batch decisions by themselves.', 'target': 'Top-level and child-level provenance-only refs becoming unavailable after approval create replay diagnostics but do not stale AC approval, Work Packet approval,', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'a_proposed_child_has_a_governed_source_dependency_only_when_a_source_derived_ac_sourceevid', 'statement': 'A proposed child has a governed source dependency only when a source-derived AC SourceEvidence record includes that SourceArtifactRef.', 'target': 'A proposed child has a governed source dependency only when a source-derived AC SourceEvidence record includes that SourceArtifactRef', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'child_level_and_top_level_source_refs_in_proposedchildrenpayload_are_provenance_only_unles', 'statement': 'Child-level and top-level source refs in ProposedChildrenPayload are provenance-only unless also present on SourceEvidence for a source-derived AC.', 'target': 'Child-level and top-level source refs in ProposedChildrenPayload are provenance-only unless also present on SourceEvidence for a source-derived AC', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'spec_guard_must_not_infer_dependencies_from_free_form_descriptions_paths_filenames_media_t', 'statement': 'Spec Guard must not infer dependencies from free-form descriptions, paths, filenames, media types, extensions, or prose.', 'target': 'Spec Guard must not infer dependencies from free-form descriptions, paths, filenames, media types, extensions, or prose', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'source_derived_ac_sourceevidence_must_declare_at_least_one_sourceartifactref', 'statement': 'Source-derived AC SourceEvidence must declare at least one SourceArtifactRef.', 'target': 'Source-derived AC SourceEvidence must declare at least one SourceArtifactRef', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_source_derived_ac_evidence_omits_required_refs_declared_refs_cannot_be_canonicalized_or', 'statement': 'If source-derived AC evidence omits required refs, declared refs cannot be canonicalized, or declared refs do not resolve to immutable SourceArtifact revisions or other known immutable top-level artifact revisions, the action must reject the batch snapshot request with diagnostics.', 'target': 'If source-derived AC evidence omits required refs, declared refs cannot be canonicalized, or declared refs do not resolve to immutable SourceArtifact revisions ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'spec_guard_must_not_restrict_source_derived_evidence_to_a_finite_list_of_file_types_extens', 'statement': 'Spec Guard must not restrict source-derived evidence to a finite list of file types, extensions, media types, or artifact kinds.', 'target': 'Spec Guard must not restrict source-derived evidence to a finite list of file types, extensions, media types, or artifact kinds', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'it_does_not_validate_whether_the_kind_or_file_type_is_acceptable_source_material', 'statement': 'it does not validate whether the kind or file type is acceptable source material.', 'target': 'it does not validate whether the kind or file type is acceptable source material', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'plan_batch_snapshot_create_persists_a_batch_review_snapshot_as_an_audit_only_mutation', 'statement': '`plan.batch_snapshot.create` persists a batch review snapshot as an audit-only mutation.', 'target': '`plan.batch_snapshot.create` persists a batch review snapshot as an audit-only mutation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_does_not_create_children_approve_acs_approve_work_packets_authorize_implementation_chan', 'statement': 'It does not create children, approve ACs, approve Work Packets, authorize implementation, change Plan intent, or increment the governed Plan revision.', 'target': 'It does not create children, approve ACs, approve Work Packets, authorize implementation, change Plan intent, or increment the governed Plan revision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'its_snapshot_hash_is_computed_over_batchreviewsnapshotpayload_which_excludes_the_enclosing', 'statement': "Its `snapshot_hash` is computed over `BatchReviewSnapshotPayload`, which excludes the enclosing record's `id`, `snapshot_hash`, `snapshot_revision`, `audit_revision`, `created_at`, and nested child `ReviewSnapshot` records", 'target': "Its `snapshot_hash` is computed over `BatchReviewSnapshotPayload`, which excludes the enclosing record's `id`, `snapshot_hash`, `snapshot_revision`, `audit_revi", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'this_prevents_circular_or_volatile_hashing', 'statement': 'this prevents circular or volatile hashing.', 'target': 'this prevents circular or volatile hashing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_plan_batch_proceed_shared_action_records_the_human_s_batch_proceed_selection_after_pla', 'statement': "The `plan.batch_proceed` shared action records the human's batch proceed selection after Plan approval for selected options 1 through 4.", 'target': "The `plan.batch_proceed` shared action records the human's batch proceed selection after Plan approval for selected options 1 through 4", 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_option_5_discuss_it_records_no_humandecision_creates_no_batchproceedrecord_and_perform', 'statement': 'For option 5 Discuss, it records no HumanDecision, creates no BatchProceedRecord, and performs no mutation.', 'target': 'For option 5 Discuss, it records no HumanDecision, creates no BatchProceedRecord, and performs no mutation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'before_creating_children_approvals_authorizations_or_baselines_for_options_1_through_4_the', 'statement': 'Before creating children, approvals, authorizations, or baselines for options 1 through 4, the action must construct', 'target': 'Before creating children, approvals, authorizations, or baselines for options 1 through 4, the action must construct', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'validate_a_canonical_batchproceedselectionpayload_from_the_selected_option_and_persisted_b', 'statement': 'validate a canonical `BatchProceedSelectionPayload` from the selected option and persisted batch snapshot.', 'target': 'validate a canonical `BatchProceedSelectionPayload` from the selected option and persisted batch snapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'if_this_preflight_validation_fails_the_action_must_perform_no_child_mutation', 'statement': 'If this preflight validation fails, the action must perform no child mutation', 'target': 'If this preflight validation fails, the action must perform no child mutation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'record_no_humandecision_or_batchproceedrecord', 'statement': 'record no HumanDecision or BatchProceedRecord.', 'target': 'record no HumanDecision or BatchProceedRecord', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_human_decision_approves_only_this_pre_decision_selection_payload', 'statement': 'The human decision approves only this pre-decision selection payload.', 'target': 'The human decision approves only this pre-decision selection payload', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_action_must_then_construct_a_separate_canonical_batchproceedresult_containing_created', 'statement': 'The action must then construct a separate canonical `BatchProceedResult` containing created child ids, approval results, authorization results, packet change baseline refs, and diagnostics for every proposed child, including failed or skipped child operations.', 'target': 'The action must then construct a separate canonical `BatchProceedResult` containing created child ids, approval results, authorization results, packet change ba', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_store_both_records_in_a_plan_batchproceedrecord_together_with_their_hashes_revisio', 'statement': 'It must store both records in a Plan `BatchProceedRecord` together with their hashes/revisions and the human decision, even when some child operations failed after earlier child mutations succeeded.', 'target': 'It must store both records in a Plan `BatchProceedRecord` together with their hashes/revisions and the human decision, even when some child operations failed af', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_not_roll_back_already_committed_successful_child_mutations_unless_the_implementati', 'statement': 'It must not roll back already committed successful child mutations unless the implementation provides a real transaction that rolls back all child and Plan writes.', 'target': 'It must not roll back already committed successful child mutations unless the implementation provides a real transaction that rolls back all child and Plan writ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'selection_revision_must_be_batch_selection_batch_snapshot_revision_selection_hash', 'statement': '`selection_revision` must be `batch-selection:<batch_snapshot_revision>:<selection_hash>`.', 'target': '`selection_revision` must be `batch-selection:<batch_snapshot_revision>:<selection_hash>`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'result_revision_must_be_batch_result_batch_snapshot_revision_result_hash', 'statement': '`result_revision` must be `batch-result:<batch_snapshot_revision>:<result_hash>`.', 'target': '`result_revision` must be `batch-result:<batch_snapshot_revision>:<result_hash>`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_plan_batch_proceed_approved_fields_are_json_pointers_into_the_stored_batchproceedselec', 'statement': 'The `plan_batch_proceed` approved fields are JSON pointers into the stored `BatchProceedSelectionPayload`, not the post-action result.', 'target': 'The `plan_batch_proceed` approved fields are JSON pointers into the stored `BatchProceedSelectionPayload`, not the post-action result', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_plan_batch_proceed_humandecision_must_populate_review_snapshot_hash_and_review_snapsho', 'statement': 'The `plan_batch_proceed` HumanDecision must populate `review_snapshot_hash` and `review_snapshot_revision` with the batch snapshot hash and revision, must populate `parent_batch_snapshot_hash` and `parent_batch_snapshot_revision` with the same values, must copy `source_artifact_refs` from the BatchReviewSnapshot, must set `approved_payload_ref` to the BatchProceedRecord selection hash and revision,', 'target': 'The `plan_batch_proceed` HumanDecision must populate `review_snapshot_hash` and `review_snapshot_revision` with the batch snapshot hash and revision, must popul', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'must_leave_approved_payload_approved_payload_hash_and_approved_payload_revision_null_unles', 'statement': 'must leave `approved_payload`, `approved_payload_hash`, and `approved_payload_revision` null unless an implementation intentionally duplicates the selection payload in addition to keeping the BatchProceedRecord as canonical.', 'target': 'must leave `approved_payload`, `approved_payload_hash`, and `approved_payload_revision` null unless an implementation intentionally duplicates the selection pay', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'create_all_suggested_child_slices_then_stop_for_review', 'statement': 'Create all suggested child slices, then stop for review', 'target': 'Create all suggested child slices, then stop for review', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'create_all_suggested_child_slices_and_approve_eligible_displayed_non_source_derived_child', 'statement': 'Create all suggested child slices and approve eligible displayed non-source-derived child ACs and Work Packets', 'target': 'Create all suggested child slices and approve eligible displayed non-source-derived child ACs and Work Packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'create_all_suggested_child_slices_approve_eligible_displayed_non_source_derived_child_acs', 'statement': 'Create all suggested child slices, approve eligible displayed non-source-derived child ACs and Work Packets, and authorize eligible child Work Packets', 'target': 'Create all suggested child slices, approve eligible displayed non-source-derived child ACs and Work Packets, and authorize eligible child Work Packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'option_1_records_a_batchproceedrecord_and_humandecision_for_the_selected_one_at_a_time_pat', 'statement': 'Option 1 records a BatchProceedRecord and HumanDecision for the selected one-at-a-time path, creates no children, records no child AC approval, records no Work Packet approval, records no authorization,', 'target': 'Option 1 records a BatchProceedRecord and HumanDecision for the selected one-at-a-time path, creates no children, records no child AC approval, records no Work ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'returns_plan_child_create_as_the_next_action', 'statement': 'returns `plan.child.create` as the next action.', 'target': 'returns `plan.child.create` as the next action', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'its_batchproceedselectionpayload_must_include_each_proposed_child_with_selected_for_creati', 'statement': 'Its BatchProceedSelectionPayload must include each proposed child with `selected_for_creation: false`, `requested_ac_batch_approval: false`, `requested_packet_batch_approval: false`, and `requested_batch_authorization: false`.', 'target': 'Its BatchProceedSelectionPayload must include each proposed child with `selected_for_creation: false`, `requested_ac_batch_approval: false`, `requested_packet_b', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'its_batchproceedresult_must_include_one_row_for_each_proposed_child_with_created_work_pack', 'statement': 'Its BatchProceedResult must include one row for each proposed child with `created_work_packet_id: null`, approval and authorization booleans false, `packet_change_baseline_ref: null`, and diagnostics empty or informational.', 'target': 'Its BatchProceedResult must include one row for each proposed child with `created_work_packet_id: null`, approval and authorization booleans false, `packet_chan', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'option_2_creates_children_only', 'statement': 'Option 2 creates children only.', 'target': 'Option 2 creates children only', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'its_batchproceedselectionpayload_must_include_every_proposed_child_with_selected_for_creat', 'statement': 'Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`, `requested_ac_batch_approval: false`, `requested_packet_batch_approval: false`, and `requested_batch_authorization: false`.', 'target': 'Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`, `requested_ac_batch_approval: false`, `requested_packet_b', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'created_children_start_pending_ac_approval_when_acs_exist_and_no_batch_approvals_are_recor', 'statement': 'Created children start `pending_ac_approval` when ACs exist and no batch approvals are recorded, including all source-derived children.', 'target': 'Created children start `pending_ac_approval` when ACs exist and no batch approvals are recorded, including all source-derived children', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'option_3_creates_all_suggested_child_work_packets_and_approves_only_children_packet_approv', 'statement': 'Option 3 creates all suggested child Work Packets and approves only children packet-approval-ready under batch rules.', 'target': 'Option 3 creates all suggested child Work Packets and approves only children packet-approval-ready under batch rules', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'its_batchproceedselectionpayload_must_include_every_proposed_child_with_selected_for_creat_2', 'statement': 'Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`', 'target': 'Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_each_child_requested_ac_batch_approval_and_requested_packet_batch_approval_are_true_on', 'statement': 'for each child, `requested_ac_batch_approval` and `requested_packet_batch_approval` are true only when `batch_approval_eligible` and readiness diagnostics are clean, and false otherwise', 'target': 'for each child, `requested_ac_batch_approval` and `requested_packet_batch_approval` are true only when `batch_approval_eligible` and readiness diagnostics are c', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'children_with_batch_ac_and_packet_approval_recorded_start_approved', 'statement': 'Children with batch AC and packet approval recorded start `approved`', 'target': 'Children with batch AC and packet approval recorded start `approved`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'created_children_without_both_approvals_start_pending_ac_approval', 'statement': 'created children without both approvals start `pending_ac_approval`.', 'target': 'created children without both approvals start `pending_ac_approval`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'option_4_creates_all_suggested_child_work_packets_approves_children_packet_approval_ready', 'statement': 'Option 4 creates all suggested child Work Packets, approves children packet-approval-ready under batch rules, and authorizes only children batch-authorization-ready.', 'target': 'Option 4 creates all suggested child Work Packets, approves children packet-approval-ready under batch rules, and authorizes only children batch-authorization-r', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'requested_batch_authorization_is_true_only_when_batch_authorization_eligible_and_readiness', 'statement': '`requested_batch_authorization` is true only when `batch_authorization_eligible` and readiness diagnostics are clean, and false otherwise.', 'target': '`requested_batch_authorization` is true only when `batch_authorization_eligible` and readiness diagnostics are clean, and false otherwise', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'children_with_authorization_recorded_start_authorized', 'statement': 'Children with authorization recorded start `authorized`', 'target': 'Children with authorization recorded start `authorized`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'children_with_approvals_but_no_authorization_start_approved', 'statement': 'children with approvals but no authorization start `approved`', 'target': 'children with approvals but no authorization start `approved`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'other_created_children_start_pending_ac_approval', 'statement': 'other created children start `pending_ac_approval`.', 'target': 'other created children start `pending_ac_approval`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'in_batchproceedselectionpayload_child_ac_snapshot_hash_ac_snapshot_revision_are_populated', 'statement': 'In BatchProceedSelectionPayload, child `ac_snapshot_hash`/`ac_snapshot_revision` are populated only when `requested_ac_batch_approval` is true', 'target': 'In BatchProceedSelectionPayload, child `ac_snapshot_hash`/`ac_snapshot_revision` are populated only when `requested_ac_batch_approval` is true', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'packet_snapshot_hash_packet_snapshot_revision_are_populated_only_when_requested_packet_bat', 'statement': '`packet_snapshot_hash`/`packet_snapshot_revision` are populated only when `requested_packet_batch_approval` is true', 'target': '`packet_snapshot_hash`/`packet_snapshot_revision` are populated only when `requested_packet_batch_approval` is true', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'and_authorization_snapshot_hash_authorization_snapshot_revision_are_populated_only_when_re', 'statement': 'and `authorization_snapshot_hash`/`authorization_snapshot_revision` are populated only when `requested_batch_authorization` is true.', 'target': 'and `authorization_snapshot_hash`/`authorization_snapshot_revision` are populated only when `requested_batch_authorization` is true', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'for_every_child_authorized_by_option_4_spec_guard_must_capture', 'statement': 'For every child authorized by option 4, Spec Guard must capture', 'target': 'For every child authorized by option 4, Spec Guard must capture', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'store_that_child_s_packetchangebaseline_atomically_with_the_child_authorization_decision', 'statement': "store that child's PacketChangeBaseline atomically with the child authorization decision.", 'target': "store that child's PacketChangeBaseline atomically with the child authorization decision", 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'if_packetchangebaseline_capture_is_blocked_for_a_child_that_child_must_not_be_authorized', 'statement': 'If PacketChangeBaseline capture is blocked for a child, that child must not be authorized.', 'target': 'If PacketChangeBaseline capture is blocked for a child, that child must not be authorized', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_batch_result_may_partially_succeed_for_other_eligible_children_but_it_must_report_per', 'statement': 'The batch result may partially succeed for other eligible children, but it must report per-child authorization failure diagnostics and next actions.', 'target': 'The batch result may partially succeed for other eligible children, but it must report per-child authorization failure diagnostics and next actions', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'runtime_baseline_must_be_accepted_before_options_3_or_4_can_be_selected_as_mutating_option', 'statement': 'Runtime baseline must be accepted before options 3 or 4 can be selected as mutating options.', 'target': 'Runtime baseline must be accepted before options 3 or 4 can be selected as mutating options', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'batch_proceed_prompt_numbering_is_fixed_options_1_through_5_always_keep_their_numbers', 'statement': 'Batch proceed prompt numbering is fixed: options 1 through 5 always keep their numbers.', 'target': 'Batch proceed prompt numbering is fixed: options 1 through 5 always keep their numbers', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'if_the_baseline_is_not_accepted_options_3_and_4_must_be_shown_as_unavailable_diagnostics_u', 'statement': 'If the baseline is not accepted, options 3 and 4 must be shown as unavailable diagnostics under their fixed numbers', 'target': 'If the baseline is not accepted, options 3 and 4 must be shown as unavailable diagnostics under their fixed numbers', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'selecting_an_unavailable_option_records_no_humandecision', 'statement': 'selecting an unavailable option records no HumanDecision', 'target': 'selecting an unavailable option records no HumanDecision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'returns_blocking_diagnostics', 'statement': 'returns blocking diagnostics.', 'target': 'returns blocking diagnostics', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'batch_review_must_display_each_affected_child_packet_s_acs_source_derived_ac_evidence_scop', 'statement': "Batch review must display each affected child packet's ACs, source-derived AC evidence, scope, classification, docs policy, allowed globs, platform, architecture, and diagnostics from the persisted batch review snapshot.", 'target': "Batch review must display each affected child packet's ACs, source-derived AC evidence, scope, classification, docs policy, allowed globs, platform, architectur", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'batch_approval_and_batch_authorization_must_exclude_any_child_containing_source_derived_ac', 'statement': 'Batch approval and batch authorization must exclude any child containing source-derived ACs.', 'target': 'Batch approval and batch authorization must exclude any child containing source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'batch_must_not_choose_platform_architecture_runtime_baseline_acceptance_plan_vs_single_or', 'statement': 'Batch must not choose platform, architecture, runtime baseline acceptance, Plan-vs-single, or Plan approval.', 'target': 'Batch must not choose platform, architecture, runtime baseline acceptance, Plan-vs-single, or Plan approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'batch_must_not_skip_deterministic_gates_or_required_backend_verification', 'statement': 'Batch must not skip deterministic gates or required backend verification.', 'target': 'Batch must not skip deterministic gates or required backend verification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'batch_approvals_and_authorizations_must_bind_per_child_according_to_section_4_7', 'statement': 'Batch approvals and authorizations must bind per child according to section 4.7.', 'target': 'Batch approvals and authorizations must bind per child according to section 4.7', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_single_packet_is_sufficient', 'statement': 'Ordered requirement is supported/enforced: Single packet is sufficient', 'target': 'Ordered requirement is supported/enforced: Single packet is sufficient', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_create_a_plan', 'statement': 'Ordered requirement is supported/enforced: Create a Plan', 'target': 'Ordered requirement is supported/enforced: Create a Plan', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_discuss', 'statement': 'Ordered requirement is supported/enforced: Discuss', 'target': 'Ordered requirement is supported/enforced: Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_yes', 'statement': 'Ordered requirement is supported/enforced: Yes', 'target': 'Ordered requirement is supported/enforced: Yes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_no', 'statement': 'Ordered requirement is supported/enforced: No', 'target': 'Ordered requirement is supported/enforced: No', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_work_through_one_child_slice_at_a_time', 'statement': 'Ordered requirement is supported/enforced: Work through one child slice at a time', 'target': 'Ordered requirement is supported/enforced: Work through one child slice at a time', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_create_all_suggested_child_slices_then_stop_for', 'statement': 'Ordered requirement is supported/enforced: Create all suggested child slices, then stop for review', 'target': 'Ordered requirement is supported/enforced: Create all suggested child slices, then stop for review', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_create_all_suggested_child_slices_and_approve_el', 'statement': 'Ordered requirement is supported/enforced: Create all suggested child slices and approve eligible displayed non-source-derived child ACs and Work Packets', 'target': 'Ordered requirement is supported/enforced: Create all suggested child slices and approve eligible displayed non-source-derived child ACs and Work Packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_create_all_suggested_child_slices_approve_eligib', 'statement': 'Ordered requirement is supported/enforced: Create all suggested child slices, approve eligible displayed non-source-derived child ACs and Work Packets, and authorize eligible child Work Packets', 'target': 'Ordered requirement is supported/enforced: Create all suggested child slices, approve eligible displayed non-source-derived child ACs and Work Packets, and auth', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_option_1_records_a_batchproceedrecord_and_humandecis', 'statement': 'Enumerated item is supported/enforced: Option 1 records a BatchProceedRecord and HumanDecision for the selected one-at-a-time path, creates no children, records no child AC approval, records no Work Packet approval, records no authorization, and returns `plan.child.create` as the next action. Its BatchProceedSelectionPayload must include each proposed child with `selected_for_creation: false`, `requested_ac_batch_approval: false`, `requested_packet_batch_approval: false`, and `requested_batch_authorization: false`. Its BatchProceedResult must include one row for each proposed child with `created_work_packet_id: null`, approval and authorization booleans false, `packet_change_baseline_ref: null`, and diagnostics empty or informational.', 'target': 'Option 1 records a BatchProceedRecord and HumanDecision for the selected one-at-a-time path, creates no children, records no child AC approval, records no Work ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_option_2_creates_children_only_its_batchproceedselec', 'statement': 'Enumerated item is supported/enforced: Option 2 creates children only. Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`, `requested_ac_batch_approval: false`, `requested_packet_batch_approval: false`, and `requested_batch_authorization: false`. Created children start `pending_ac_approval` when ACs exist and no batch approvals are recorded, including all source-derived children.', 'target': 'Option 2 creates children only. Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`, `requested_ac_batch_appro', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_option_3_creates_all_suggested_child_work_packets_an', 'statement': 'Enumerated item is supported/enforced: Option 3 creates all suggested child Work Packets and approves only children packet-approval-ready under batch rules. Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`; for each child, `requested_ac_batch_approval` and `requested_packet_batch_approval` are true only when `batch_approval_eligible` and readiness diagnostics are clean, and false otherwise; `requested_batch_authorization` is always false. Children with batch AC and packet approval recorded start `approved`; created children without both approvals start `pending_ac_approval`.', 'target': 'Option 3 creates all suggested child Work Packets and approves only children packet-approval-ready under batch rules. Its BatchProceedSelectionPayload must incl', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_option_4_creates_all_suggested_child_work_packets_ap', 'statement': 'Enumerated item is supported/enforced: Option 4 creates all suggested child Work Packets, approves children packet-approval-ready under batch rules, and authorizes only children batch-authorization-ready. Its BatchProceedSelectionPayload must include every proposed child with `selected_for_creation: true`; for each child, `requested_ac_batch_approval` and `requested_packet_batch_approval` are true when `batch_approval_eligible` and readiness diagnostics are clean, and false otherwise; `requested_batch_authorization` is true only when `batch_authorization_eligible` and readiness diagnostics are clean, and false otherwise. Children with authorization recorded start `authorized`; children with approvals but no authorization start `approved`; other created children start `pending_ac_approval`.', 'target': 'Option 4 creates all suggested child Work Packets, approves children packet-approval-ready under batch rules, and authorizes only children batch-authorization-r', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_in_batchproceedselectionpayload_child_ac_snapshot_ha', 'statement': 'Enumerated item is supported/enforced: In BatchProceedSelectionPayload, child `ac_snapshot_hash`/`ac_snapshot_revision` are populated only when `requested_ac_batch_approval` is true; `packet_snapshot_hash`/`packet_snapshot_revision` are populated only when `requested_packet_batch_approval` is true; and `authorization_snapshot_hash`/`authorization_snapshot_revision` are populated only when `requested_batch_authorization` is true. All unrequested, ineligible, unavailable, or option-1/option-2 child snapshot fields are null.', 'target': 'In BatchProceedSelectionPayload, child `ac_snapshot_hash`/`ac_snapshot_revision` are populated only when `requested_ac_batch_approval` is true; `packet_snapshot', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_for_every_child_authorized_by_option_4_spec_guard_mu', 'statement': "Enumerated item is supported/enforced: For every child authorized by option 4, Spec Guard must capture and store that child's PacketChangeBaseline atomically with the child authorization decision.", 'target': "For every child authorized by option 4, Spec Guard must capture and store that child's PacketChangeBaseline atomically with the child authorization decision", 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_if_packetchangebaseline_capture_is_blocked_for_a_chi', 'statement': 'Enumerated item is supported/enforced: If PacketChangeBaseline capture is blocked for a child, that child must not be authorized. The batch result may partially succeed for other eligible children, but it must report per-child authorization failure diagnostics and next actions.', 'target': 'If PacketChangeBaseline capture is blocked for a child, that child must not be authorized. The batch result may partially succeed for other eligible children, b', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_option_5_mutates_nothing', 'statement': 'Enumerated item is supported/enforced: Option 5 mutates nothing.', 'target': 'Option 5 mutates nothing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_must_be_accepted_before_options_3_o', 'statement': 'Enumerated item is supported/enforced: Runtime baseline must be accepted before options 3 or 4 can be selected as mutating options. Batch proceed prompt numbering is fixed: options 1 through 5 always keep their numbers. If the baseline is not accepted, options 3 and 4 must be shown as unavailable diagnostics under their fixed numbers; selecting an unavailable option records no HumanDecision and returns blocking diagnostics.', 'target': 'Runtime baseline must be accepted before options 3 or 4 can be selected as mutating options. Batch proceed prompt numbering is fixed: options 1 through 5 always', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_review_must_display_each_affected_child_packet', 'statement': "Enumerated item is supported/enforced: Batch review must display each affected child packet's ACs, source-derived AC evidence, scope, classification, docs policy, allowed globs, platform, architecture, and diagnostics from the persisted batch review snapshot.", 'target': "Batch review must display each affected child packet's ACs, source-derived AC evidence, scope, classification, docs policy, allowed globs, platform, architectur", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_approval_and_batch_authorization_must_exclude', 'statement': 'Enumerated item is supported/enforced: Batch approval and batch authorization must exclude any child containing source-derived ACs.', 'target': 'Batch approval and batch authorization must exclude any child containing source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_must_not_choose_platform_architecture_runtime', 'statement': 'Enumerated item is supported/enforced: Batch must not choose platform, architecture, runtime baseline acceptance, Plan-vs-single, or Plan approval.', 'target': 'Batch must not choose platform, architecture, runtime baseline acceptance, Plan-vs-single, or Plan approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_must_not_skip_deterministic_gates_or_required', 'statement': 'Enumerated item is supported/enforced: Batch must not skip deterministic gates or required backend verification.', 'target': 'Batch must not skip deterministic gates or required backend verification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_approvals_and_authorizations_must_bind_per_chi', 'statement': 'Enumerated item is supported/enforced: Batch approvals and authorizations must bind per child according to section 4.7.', 'target': 'Batch approvals and authorizations must bind per child according to section 4.7', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
