"""Executable specification for US-10: Single packet approval and authorization."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'if_work_is_not_under_an_approved_plan_batch_flow_spec_guard_must_use_sequential_gates', 'statement': 'If work is not under an approved Plan batch flow, Spec Guard must use sequential gates:', 'target': 'If work is not under an approved Plan batch flow, Spec Guard must use sequential gates:', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'no_combined_ac_packet_approval_gate_is_allowed_for_a_single_work_packet_path', 'statement': 'No combined AC+packet approval gate is allowed for a single Work Packet path.', 'target': 'No combined AC+packet approval gate is allowed for a single Work Packet path', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'source_derived_acs_include_source_evidence', 'statement': 'source-derived ACs include source/evidence,', 'target': 'source-derived ACs include source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_ac_approval_blocking_diagnostics_exist', 'statement': 'no AC-approval-blocking diagnostics exist.', 'target': 'no AC-approval-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'acs_are_approved_except_for_eligible_plan_child_batch_approval_where_the_same_batch_select', 'statement': 'ACs are approved, except for eligible Plan-child batch approval where the same batch selection explicitly approves displayed non-source-derived ACs,', 'target': 'ACs are approved, except for eligible Plan-child batch approval where the same batch selection explicitly approves displayed non-source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_packet_contains_no_unapproved_source_derived_acs', 'statement': 'the packet contains no unapproved source-derived ACs,', 'target': 'the packet contains no unapproved source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'allowed_file_globs_are_present', 'statement': 'allowed file globs are present,', 'target': 'allowed file globs are present', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'required_platform_choice_is_recorded', 'statement': 'required platform choice is recorded,', 'target': 'required platform choice is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_architecture_choice_is_recorded', 'statement': 'required architecture choice is recorded,', 'target': 'required architecture choice is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'no_required_human_decision_is_pending', 'statement': 'no required human decision is pending,', 'target': 'no required human decision is pending', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'no_packet_approval_blocking_diagnostics_exist', 'statement': 'no packet-approval-blocking diagnostics exist.', 'target': 'no packet-approval-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'allowed_scope_is_known', 'statement': 'allowed scope is known,', 'target': 'allowed scope is known', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'packet_change_baseline_can_be_captured', 'statement': 'packet change baseline can be captured,', 'target': 'packet change baseline can be captured', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_authorization_blocking_diagnostics_exist', 'statement': 'no authorization-blocking diagnostics exist.', 'target': 'no authorization-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_proposed_child_payload_is_included_in_a_persisted_batch_review_snapshot', 'statement': 'the proposed child payload is included in a persisted batch review snapshot,', 'target': 'the proposed child payload is included in a persisted batch review snapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_proposed_child_contains_no_source_derived_acs', 'statement': 'the proposed child contains no source-derived ACs,', 'target': 'the proposed child contains no source-derived ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'allowed_scope_is_known_in_the_proposed_child_payload', 'statement': 'allowed scope is known in the proposed child payload,', 'target': 'allowed scope is known in the proposed child payload', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'packet_change_baseline_capture_is_expected_to_succeed_after_child_artifact_creation', 'statement': 'packet change baseline capture is expected to succeed after child artifact creation,', 'target': 'packet change baseline capture is expected to succeed after child artifact creation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_batch_authorization_blocking_diagnostics_exist', 'statement': 'no batch-authorization-blocking diagnostics exist.', 'target': 'no batch-authorization-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'authorization_is_recorded', 'statement': 'authorization is recorded,', 'target': 'authorization is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'packet_change_baseline_is_captured', 'statement': 'packet change baseline is captured,', 'target': 'packet change baseline is captured', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'required_pre_implementation_docs_tests_failure_first_chain_is_complete_required_docs_exist', 'statement': 'required pre-implementation docs/tests/failure-first chain is complete: required docs exist', 'target': 'required pre-implementation docs/tests/failure-first chain is complete: required docs exist', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'are_linked_retained_test_files_exist_when_tests_are_required_and_failure_first_evidence_is', 'statement': 'are linked, retained test files exist when tests are required, and failure-first evidence is recorded', 'target': 'are linked, retained test files exist when tests are required, and failure-first evidence is recorded', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'passing_test_evidence_is_not_required_until_review_completion', 'statement': 'passing-test evidence is not required until review completion,', 'target': 'passing-test evidence is not required until review completion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_backend_verification_for_pre_implementation_has_passed_excluding_docs_updated_ver', 'statement': 'required backend verification for pre-implementation has passed, excluding `docs_updated` verification that section 12.8 explicitly permits to remain pending until review completion,', 'target': 'required backend verification for pre-implementation has passed, excluding `docs_updated` verification that section 12.8 explicitly permits to remain pending un', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'no_implementation_blocking_diagnostics_exist', 'statement': 'no implementation-blocking diagnostics exist.', 'target': 'no implementation-blocking diagnostics exist', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'implementation_source_changes_must_not_occur_before_implementation_ready_state', 'statement': 'Implementation source changes must not occur before implementation-ready state.', 'target': 'Implementation source changes must not occur before implementation-ready state', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'do_you_approve_this_work_packet_as_shown', 'statement': '`Do you approve this Work Packet as shown?`', 'target': '`Do you approve this Work Packet as shown?`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'yes_records_packet_approval_bound_to_the_displayed_packet_review_snapshot_hash', 'statement': 'Yes records packet approval bound to the displayed packet review snapshot hash.', 'target': 'Yes records packet approval bound to the displayed packet review snapshot hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_records_decline_or_blocks_as_appropriate', 'statement': 'No records decline or blocks as appropriate.', 'target': 'No records decline or blocks as appropriate', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'discuss_records_no_mutation_and_later_re_presents_the_same_gate', 'statement': 'Discuss records no mutation and later re-presents the same gate.', 'target': 'Discuss records no mutation and later re-presents the same gate', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'yes_records_authorization_captures_packet_change_baseline_and_binds_authorization_to_the_a', 'statement': 'Yes records authorization, captures packet change baseline, and binds authorization to the authorization review snapshot hash.', 'target': 'Yes records authorization, captures packet change baseline, and binds authorization to the authorization review snapshot hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_authorization_review_snapshot_must_include_the_approved_packet_snapshot_hash_and_revis', 'statement': 'The authorization review snapshot must include the approved packet snapshot hash and revision.', 'target': 'The authorization review snapshot must include the approved packet snapshot hash and revision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_ac_approval_gate', 'statement': 'Ordered requirement is supported/enforced: AC approval gate.', 'target': 'Ordered requirement is supported/enforced: AC approval gate', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_work_packet_approval_gate', 'statement': 'Ordered requirement is supported/enforced: Work Packet approval gate.', 'target': 'Ordered requirement is supported/enforced: Work Packet approval gate', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_implementation_authorization_gate', 'statement': 'Ordered requirement is supported/enforced: Implementation authorization gate.', 'target': 'Ordered requirement is supported/enforced: Implementation authorization gate', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_goal_exists', 'statement': 'Enumerated item is supported/enforced: goal exists,', 'target': 'goal exists', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_at_least_one_ac_exists', 'statement': 'Enumerated item is supported/enforced: at least one AC exists,', 'target': 'at least one AC exists', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_derived_acs_include_source_evidence', 'statement': 'Enumerated item is supported/enforced: source-derived ACs include source/evidence,', 'target': 'source-derived ACs include source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_review_snapshot_can_be_rendered', 'statement': 'Enumerated item is supported/enforced: AC review snapshot can be rendered,', 'target': 'AC review snapshot can be rendered', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_ac_approval_blocking_diagnostics_exist', 'statement': 'Enumerated item is supported/enforced: no AC-approval-blocking diagnostics exist.', 'target': 'no AC-approval-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acs_are_approved_except_for_eligible_plan_child_batc', 'statement': 'Enumerated item is supported/enforced: ACs are approved, except for eligible Plan-child batch approval where the same batch selection explicitly approves displayed non-source-derived ACs,', 'target': 'ACs are approved, except for eligible Plan-child batch approval where the same batch selection explicitly approves displayed non-source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_packet_contains_no_unapproved_source_derived_acs', 'statement': 'Enumerated item is supported/enforced: the packet contains no unapproved source-derived ACs,', 'target': 'the packet contains no unapproved source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_is_accepted', 'statement': 'Enumerated item is supported/enforced: runtime baseline is accepted,', 'target': 'runtime baseline is accepted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_classification_is_valid', 'statement': 'Enumerated item is supported/enforced: classification is valid,', 'target': 'classification is valid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy_is_valid', 'statement': 'Enumerated item is supported/enforced: docs policy is valid,', 'target': 'docs policy is valid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_file_globs_are_present', 'statement': 'Enumerated item is supported/enforced: allowed file globs are present,', 'target': 'allowed file globs are present', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_platform_choice_is_recorded', 'statement': 'Enumerated item is supported/enforced: required platform choice is recorded,', 'target': 'required platform choice is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_architecture_choice_is_recorded', 'statement': 'Enumerated item is supported/enforced: required architecture choice is recorded,', 'target': 'required architecture choice is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_required_human_decision_is_pending', 'statement': 'Enumerated item is supported/enforced: no required human decision is pending,', 'target': 'no required human decision is pending', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_packet_approval_blocking_diagnostics_exist', 'statement': 'Enumerated item is supported/enforced: no packet-approval-blocking diagnostics exist.', 'target': 'no packet-approval-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_is_approved_at_current_review_snapshot_hash', 'statement': 'Enumerated item is supported/enforced: packet is approved at current review snapshot hash,', 'target': 'packet is approved at current review snapshot hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_remains_accepted', 'statement': 'Enumerated item is supported/enforced: runtime baseline remains accepted,', 'target': 'runtime baseline remains accepted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approval_is_not_stale', 'statement': 'Enumerated item is supported/enforced: approval is not stale,', 'target': 'approval is not stale', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_scope_is_known', 'statement': 'Enumerated item is supported/enforced: allowed scope is known,', 'target': 'allowed scope is known', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_parent_plan_relationship_is_valid_when_applicable', 'statement': 'Enumerated item is supported/enforced: parent Plan relationship is valid when applicable,', 'target': 'parent Plan relationship is valid when applicable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline_can_be_captured', 'statement': 'Enumerated item is supported/enforced: packet change baseline can be captured,', 'target': 'packet change baseline can be captured', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_authorization_blocking_diagnostics_exist', 'statement': 'Enumerated item is supported/enforced: no authorization-blocking diagnostics exist.', 'target': 'no authorization-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_proposed_child_payload_is_included_in_a_persiste', 'statement': 'Enumerated item is supported/enforced: the proposed child payload is included in a persisted batch review snapshot,', 'target': 'the proposed child payload is included in a persisted batch review snapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_proposed_child_contains_no_source_derived_acs', 'statement': 'Enumerated item is supported/enforced: the proposed child contains no source-derived ACs,', 'target': 'the proposed child contains no source-derived ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_proposed_child_is_batch_packet_approval_eligible', 'statement': 'Enumerated item is supported/enforced: the proposed child is batch packet-approval eligible,', 'target': 'the proposed child is batch packet-approval eligible', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_proposed_child_packet_review_snapshot_is_present', 'statement': 'Enumerated item is supported/enforced: the proposed child packet review snapshot is present,', 'target': 'the proposed child packet review snapshot is present', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_proposed_child_authorization_review_snapshot_is', 'statement': 'Enumerated item is supported/enforced: the proposed child authorization review snapshot is present,', 'target': 'the proposed child authorization review snapshot is present', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_scope_is_known_in_the_proposed_child_payload', 'statement': 'Enumerated item is supported/enforced: allowed scope is known in the proposed child payload,', 'target': 'allowed scope is known in the proposed child payload', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline_capture_is_expected_to_succee', 'statement': 'Enumerated item is supported/enforced: packet change baseline capture is expected to succeed after child artifact creation,', 'target': 'packet change baseline capture is expected to succeed after child artifact creation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_batch_authorization_blocking_diagnostics_exist', 'statement': 'Enumerated item is supported/enforced: no batch-authorization-blocking diagnostics exist.', 'target': 'no batch-authorization-blocking diagnostics exist', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_authorization_is_recorded', 'statement': 'Enumerated item is supported/enforced: authorization is recorded,', 'target': 'authorization is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline_is_captured', 'statement': 'Enumerated item is supported/enforced: packet change baseline is captured,', 'target': 'packet change baseline is captured', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pre_implementation_validation_passes', 'statement': 'Enumerated item is supported/enforced: pre-implementation validation passes,', 'target': 'pre-implementation validation passes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_pre_implementation_docs_tests_failure_first', 'statement': 'Enumerated item is supported/enforced: required pre-implementation docs/tests/failure-first chain is complete: required docs exist and are linked, retained test files exist when tests are required, and failure-first evidence is recorded; passing-test evidence is not required until review completion,', 'target': 'required pre-implementation docs/tests/failure-first chain is complete: required docs exist and are linked, retained test files exist when tests are required, a', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_backend_verification_for_pre_implementation', 'statement': 'Enumerated item is supported/enforced: required backend verification for pre-implementation has passed, excluding `docs_updated` verification that section 12.8 explicitly permits to remain pending until review completion,', 'target': 'required backend verification for pre-implementation has passed, excluding `docs_updated` verification that section 12.8 explicitly permits to remain pending un', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_implementation_blocking_diagnostics_exist', 'statement': 'Enumerated item is supported/enforced: no implementation-blocking diagnostics exist.', 'target': 'no implementation-blocking diagnostics exist', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_yes', 'statement': 'Ordered requirement is supported/enforced: Yes', 'target': 'Ordered requirement is supported/enforced: Yes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_no', 'statement': 'Ordered requirement is supported/enforced: No', 'target': 'Ordered requirement is supported/enforced: No', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_discuss', 'statement': 'Ordered requirement is supported/enforced: Discuss', 'target': 'Ordered requirement is supported/enforced: Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
