"""Executable specification for US-07: Work packets, plans, and classification."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'blocked', 'statement': '`blocked`,', 'target': '`blocked`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'a_work_packet_must_support', 'statement': 'A Work Packet must support:', 'target': 'A Work Packet must support:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'source_evidence_metadata_for_source_derived_acs', 'statement': 'source/evidence metadata for source-derived ACs,', 'target': 'source/evidence metadata for source-derived ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'allowed_file_globs', 'statement': 'allowed file globs,', 'target': 'allowed file globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'backend_verification_records', 'statement': 'backend verification records,', 'target': 'backend verification records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'work_intake_creates_a_valid_draft_work_packet_from_an_intakerequest_and_classification', 'statement': '`work.intake` creates a valid draft Work Packet from an IntakeRequest and classification.', 'target': '`work.intake` creates a valid draft Work Packet from an IntakeRequest and classification', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_must_reject_parent_plan_ids_or_plan_slice_ids', 'statement': 'It must reject parent Plan ids or Plan slice ids', 'target': 'It must reject parent Plan ids or Plan slice ids', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'plan_children_must_be_created_only_through_plan_child_create_or_plan_batch_proceed', 'statement': 'Plan children must be created only through `plan.child.create` or `plan.batch_proceed`.', 'target': 'Plan children must be created only through `plan.child.create` or `plan.batch_proceed`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'intakerequest_must_include_title_and_goal', 'statement': 'IntakeRequest must include `title` and `goal`.', 'target': 'IntakeRequest must include `title` and `goal`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_policy_is_required_for_api_contract_surface_and_operational_document_classifications', 'statement': 'docs policy is `required` for API/contract-surface and `operational_document` classifications and `none_required` otherwise unless supplied with a classification-compatible policy.', 'target': 'docs policy is `required` for API/contract-surface and `operational_document` classifications and `none_required` otherwise unless supplied with a classificatio', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'classification_compatible_supplied_policies_are_api_contract_surface_requires_required', 'statement': 'Classification-compatible supplied policies are: API/contract-surface requires `required`', 'target': 'Classification-compatible supplied policies are: API/contract-surface requires `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'operational_document_requires_required', 'statement': '`operational_document` requires `required`', 'target': '`operational_document` requires `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'other_classifications_allow_required_changed_none_required_or_not_applicable', 'statement': 'other classifications allow `required`, `changed`, `none_required`, or `not_applicable`.', 'target': 'other classifications allow `required`, `changed`, `none_required`, or `not_applicable`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_supplied_docs_policy_is_not_applicable_request_docs_not_applicable_reason_must_be_non_e', 'statement': 'If supplied docs policy is `not_applicable`, `request.docs_not_applicable_reason` must be non-empty', 'target': 'If supplied docs policy is `not_applicable`, `request.docs_not_applicable_reason` must be non-empty', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_supplied_docs_policy_is_none_required_docs_none_required_reason_is_set_from_request_doc', 'statement': 'if supplied docs policy is `none_required`, `docs.none_required_reason` is set from `request.docs_none_required_reason` when supplied or to `classification_default_none_required`', 'target': 'if supplied docs policy is `none_required`, `docs.none_required_reason` is set from `request.docs_none_required_reason` when supplied or to `classification_defa', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'otherwise_docs_reason_fields_are_null_unless_later_set_by_a_docs_action', 'statement': 'otherwise docs reason fields are null unless later set by a docs action.', 'target': 'otherwise docs reason fields are null unless later set by a docs action', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'docs_requirements_records_are_empty', 'statement': 'Docs requirements/records are empty', 'target': 'Docs requirements/records are empty', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'platform_architecture_requiredness_fields_are_computed_by_sections_8_1_and_8_2', 'statement': 'platform/architecture requiredness fields are computed by sections 8.1 and 8.2', 'target': 'platform/architecture requiredness fields are computed by sections 8.1 and 8.2', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'goal_and_acs_are_required_before_ac_approval', 'statement': 'Goal and ACs are required before AC approval.', 'target': 'Goal and ACs are required before AC approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ac_approval_is_required_before_work_packet_approval_except_for_explicit_eligible_plan_chil', 'statement': 'AC approval is required before Work Packet approval except for explicit eligible Plan-child batch approval of non-source-derived ACs.', 'target': 'AC approval is required before Work Packet approval except for explicit eligible Plan-child batch approval of non-source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_packet_approval_is_required_before_implementation_authorization', 'statement': 'Work Packet approval is required before implementation authorization.', 'target': 'Work Packet approval is required before implementation authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implementation_authorization_and_packet_change_baseline_capture_are_one_atomic_governed_ac', 'statement': 'Implementation authorization and packet change baseline capture are one atomic governed action', 'target': 'Implementation authorization and packet change baseline capture are one atomic governed action', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'packetchangebaseline_capture_must_succeed_before_the_authorization_humandecision_is_record', 'statement': 'PacketChangeBaseline capture must succeed before the authorization HumanDecision is recorded.', 'target': 'PacketChangeBaseline capture must succeed before the authorization HumanDecision is recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'pre_implementation_validation_is_required_before_implementation_source_changes', 'statement': 'Pre-implementation validation is required before implementation source changes.', 'target': 'Pre-implementation validation is required before implementation source changes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'approval_is_invalidated_when_approved_title_parent_plan_linkage_plan_slice_linkage_intent', 'statement': 'Approval is invalidated when approved title, parent Plan linkage, Plan slice linkage, intent, ACs, source evidence, approved scope fields such as allowed globs, classification, docs policy, platform, architecture, or runtime baseline reference changes.', 'target': 'Approval is invalidated when approved title, parent Plan linkage, Plan slice linkage, intent, ACs, source evidence, approved scope fields such as allowed globs,', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'scope_deviations_and_docs_requirements_are_review_context_unless_included_in_an_approved_f', 'statement': 'Scope deviations and docs requirements are review context unless included in an approved-field set.', 'target': 'Scope deviations and docs requirements are review context unless included in an approved-field set', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'generic_update_actions_must_not_silently_change_approved_fields', 'statement': 'Generic update actions must not silently change approved fields.', 'target': 'Generic update actions must not silently change approved fields', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'if_an_update_touches_approved_fields_spec_guard_must_either_reject_it_as_a_protected_appro', 'statement': 'If an update touches approved fields, Spec Guard must either reject it as a protected approved-field update or apply it and deterministically invalidate every dependent approval/authorization with diagnostics and next actions.', 'target': 'If an update touches approved fields, Spec Guard must either reject it as a protected approved-field update or apply it and deterministically invalidate every d', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_action_result_must_list_every_invalidated_decision', 'statement': 'The action result must list every invalidated decision.', 'target': 'The action result must list every invalidated decision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_update_must_reject_changes_to_plan_approved_fields', 'statement': '`plan.update` must reject changes to Plan-approved fields.', 'target': '`plan.update` must reject changes to Plan-approved fields', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'because_there_is_no_persisted_draft_plan_state_an_approved_plan_cannot_be_moved_back_to_dr', 'statement': 'Because there is no persisted draft Plan state, an approved Plan cannot be moved back to draft by mutation.', 'target': 'Because there is no persisted draft Plan state, an approved Plan cannot be moved back to draft by mutation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'changing_approved_plan_intent_requires_a_new_plan_or_a_registered_plan_amendment_action_wi', 'statement': 'Changing approved Plan intent requires a new Plan or a registered Plan amendment action with its own review snapshot and Plan approval decision.', 'target': 'Changing approved Plan intent requires a new Plan or a registered Plan amendment action with its own review snapshot and Plan approval decision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'validation_actions_may_update_diagnostics_without_changing_status_unless_listed_above', 'statement': 'Validation actions may update diagnostics without changing status unless listed above.', 'target': 'Validation actions may update diagnostics without changing status unless listed above', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'records_blocking_diagnostics_and_next_actions', 'statement': 'records blocking diagnostics and next actions.', 'target': 'records blocking diagnostics and next actions', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'a_plan_must_include', 'statement': 'A Plan must include:', 'target': 'A Plan must include:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'approved_plan_proposal_record', 'statement': 'approved Plan proposal record,', 'target': 'approved Plan proposal record', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'a_plan_never_authorizes_implementation', 'statement': 'A Plan never authorizes implementation.', 'target': 'A Plan never authorizes implementation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'only_child_work_packets_can_be_authorized', 'statement': 'Only child Work Packets can be authorized.', 'target': 'Only child Work Packets can be authorized', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'therefore_there_is_no_persisted_proposal_only_plan_status_and_no_valid_persisted_draft_pla', 'statement': 'Therefore there is no persisted proposal-only Plan status and no valid persisted draft Plan.', 'target': 'Therefore there is no persisted proposal-only Plan status and no valid persisted draft Plan', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'a_plan_artifact_is_created_only_by_plan_approval', 'statement': 'A Plan artifact is created only by Plan approval', 'target': 'A Plan artifact is created only by Plan approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'must_have_an_approval_decision_when_created', 'statement': 'must have an approval decision when created.', 'target': 'must have an approval decision when created', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_update_may_mutate_only_non_approved_operational_metadata_status_among_non_archival_ru', 'statement': '`plan.update` may mutate only non-approved operational metadata: status among non-archival runtime statuses, diagnostics, child_work_ids after validated child creation, and archive metadata through archive actions.', 'target': '`plan.update` may mutate only non-approved operational metadata: status among non-archival runtime statuses, diagnostics, child_work_ids after validated child c', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_must_reject_changes_to_title_goal_product_context_plan_proposal_approval_and_any_plan_a', 'statement': 'It must reject changes to title, goal, product_context, plan_proposal, approval, and any Plan-approved path.', 'target': 'It must reject changes to title, goal, product_context, plan_proposal, approval, and any Plan-approved path', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'each_work_packet_must_have_exactly_one_classification', 'statement': 'Each Work Packet must have exactly one classification:', 'target': 'Each Work Packet must have exactly one classification:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_intake_must_receive_a_valid_classification', 'statement': '`work.intake` must receive a valid classification', 'target': '`work.intake` must receive a valid classification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_deterministic_kernel_validates_enum_membership', 'statement': 'The deterministic kernel validates enum membership.', 'target': 'The deterministic kernel validates enum membership', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_backend_verifier_must_not_judge_classification_quality', 'statement': 'The backend verifier must not judge classification quality.', 'target': 'The backend verifier must not judge classification quality', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'api_contract_surface_packets_always_require_human_facing_docs', 'statement': 'API/contract-surface packets always require human-facing docs.', 'target': 'API/contract-surface packets always require human-facing docs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_chain', 'statement': 'Required chain:', 'target': 'Required chain:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'all_other_classifications_follow_the_non_api_chain_unless_docs_policy_requires_docs', 'statement': 'All other classifications follow the non-API chain unless docs policy requires docs.', 'target': 'All other classifications follow the non-API chain unless docs policy requires docs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'their_docs_content_policy_must_be_required', 'statement': 'Their docs/content policy must be `required`.', 'target': 'Their docs/content policy must be `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'they_may_have_tests_and_failure_first_evidence_marked_not_applicable_only_when_the_approve', 'statement': 'They may have tests and failure-first evidence marked not applicable only when the approved scope changes documentation/operational content', 'target': 'They may have tests and failure-first evidence marked not applicable only when the approved scope changes documentation/operational content', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'if_an_operational_document_packet_changes_product_behavior_it_must_be_reclassified_or_foll', 'statement': 'If an operational-document packet changes product behavior, it must be reclassified or follow the applicable product validation chain.', 'target': 'If an operational-document packet changes product behavior, it must be reclassified or follow the applicable product validation chain', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_docs_must_exist_and_be_linked_to_approved_acs_before_pre_implementation_validatio', 'statement': '`required`: docs must exist and be linked to approved ACs before pre-implementation validation passes,', 'target': '`required`: docs must exist and be linked to approved ACs before pre-implementation validation passes', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'changed_docs_are_not_required_before_pre_implementation_validation_but_docs_must_be_update', 'statement': '`changed`: docs are not required before pre-implementation validation, but docs must be updated and a `docs_updated` claim must pass backend verification before review completion,', 'target': '`changed`: docs are not required before pre-implementation validation, but docs must be updated and a `docs_updated` claim must pass backend verification before', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'none_required_docs_are_not_required_and_docs_none_required_reason_records_why', 'statement': '`none_required`: docs are not required and `docs.none_required_reason` records why,', 'target': '`none_required`: docs are not required and `docs.none_required_reason` records why', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'not_applicable_docs_do_not_apply_and_docs_not_applicable_reason_records_why', 'statement': '`not_applicable`: docs do not apply and `docs.not_applicable_reason` records why.', 'target': '`not_applicable`: docs do not apply and `docs.not_applicable_reason` records why', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'for_api_contract_surface_packets_docs_policy_must_be_required', 'statement': 'For API/contract-surface packets, docs policy must be `required`.', 'target': 'For API/contract-surface packets, docs policy must be `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_operational_document_packets_docs_content_policy_must_be_required', 'statement': 'For `operational_document` packets, docs/content policy must be `required`', 'target': 'For `operational_document` packets, docs/content policy must be `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'when_docs_are_required_spec_guard_must_validate', 'statement': 'When docs are required, Spec Guard must validate:', 'target': 'When docs are required, Spec Guard must validate:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_backend_verification_for_docs_to_ac_mapping_passed', 'statement': 'required backend verification for docs-to-AC mapping passed.', 'target': 'required backend verification for docs-to-AC mapping passed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'when_docs_policy_is_required_or_changed_when_docs_policy_changes_during_the_packet_lifecyc', 'statement': 'When docs policy is `required` or `changed`, when docs policy changes during the packet lifecycle, or when docs files are changed, Spec Guard must require a registered `docs_updated` claim and passed backend verification for that claim before review completion.', 'target': 'When docs policy is `required` or `changed`, when docs policy changes during the packet lifecycle, or when docs files are changed, Spec Guard must require a reg', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_required_docs_this_requirement_is_in_addition_to_docs_existence_and_docs_to_ac_mapping', 'statement': 'For `required` docs, this requirement is in addition to docs existence and docs-to-AC mapping checks.', 'target': 'For `required` docs, this requirement is in addition to docs existence and docs-to-AC mapping checks', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'documentation_itself_must_never_be_the_target_of_retained_tests', 'statement': 'Documentation itself must never be the target of retained tests.', 'target': 'Documentation itself must never be the target of retained tests', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'tests_must_validate_product_behavior_api_behavior_runtime_behavior_or_other_approved_non_d', 'statement': 'Tests must validate product behavior, API behavior, runtime behavior, or other approved non-document behavior.', 'target': 'Tests must validate product behavior, API behavior, runtime behavior, or other approved non-document behavior', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_must_not_require_or_accept_retained_tests_that_assert_documentation_text_format', 'statement': 'Spec Guard must not require or accept retained tests that assert documentation text, formatting, files, headings, examples, or links as governed evidence.', 'target': 'Spec Guard must not require or accept retained tests that assert documentation text, formatting, files, headings, examples, or links as governed evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'temporary_scripts_or_tests_that_an_agent_uses_to_aid_documentation_work_are_permitted_only', 'statement': 'Temporary scripts or tests that an agent uses to aid documentation work are permitted only if removed before review completion.', 'target': 'Temporary scripts or tests that an agent uses to aid documentation work are permitted only if removed before review completion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_draft', 'statement': 'Enumerated item is supported/enforced: `draft`,', 'target': '`draft`', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pending_ac_approval', 'statement': 'Enumerated item is supported/enforced: `pending_ac_approval`,', 'target': '`pending_ac_approval`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pending_packet_approval', 'statement': 'Enumerated item is supported/enforced: `pending_packet_approval`,', 'target': '`pending_packet_approval`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approved', 'statement': 'Enumerated item is supported/enforced: `approved`,', 'target': '`approved`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_authorized', 'statement': 'Enumerated item is supported/enforced: `authorized`,', 'target': '`authorized`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_preimplementation_validated', 'statement': 'Enumerated item is supported/enforced: `preimplementation_validated`,', 'target': '`preimplementation_validated`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_active', 'statement': 'Enumerated item is supported/enforced: `implementation_active`,', 'target': '`implementation_active`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implemented', 'statement': 'Enumerated item is supported/enforced: `implemented`,', 'target': '`implemented`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_complete', 'statement': 'Enumerated item is supported/enforced: `review_complete`,', 'target': '`review_complete`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_blocked', 'statement': 'Enumerated item is supported/enforced: `blocked`,', 'target': '`blocked`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_deferred', 'statement': 'Enumerated item is supported/enforced: `deferred`,', 'target': '`deferred`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_archived', 'statement': 'Enumerated item is supported/enforced: `archived`.', 'target': '`archived`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_title', 'statement': 'Enumerated item is supported/enforced: title,', 'target': 'title', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_classification', 'statement': 'Enumerated item is supported/enforced: classification,', 'target': 'classification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_parent_plan_reference_and_plan_slice_reference_when', 'statement': 'Enumerated item is supported/enforced: parent Plan reference and Plan slice reference when applicable,', 'target': 'parent Plan reference and Plan slice reference when applicable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_intent_fields', 'statement': 'Enumerated item is supported/enforced: intent fields,', 'target': 'intent fields', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acs', 'statement': 'Enumerated item is supported/enforced: ACs,', 'target': 'ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_evidence_metadata_for_source_derived_acs', 'statement': 'Enumerated item is supported/enforced: source/evidence metadata for source-derived ACs,', 'target': 'source/evidence metadata for source-derived ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy', 'statement': 'Enumerated item is supported/enforced: docs policy,', 'target': 'docs policy', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_file_globs', 'statement': 'Enumerated item is supported/enforced: allowed file globs,', 'target': 'allowed file globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_platform_choice', 'statement': 'Enumerated item is supported/enforced: platform choice,', 'target': 'platform choice', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_architecture_decision_references', 'statement': 'Enumerated item is supported/enforced: architecture decision references,', 'target': 'architecture decision references', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_reference', 'statement': 'Enumerated item is supported/enforced: runtime baseline reference,', 'target': 'runtime baseline reference', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline', 'statement': 'Enumerated item is supported/enforced: packet change baseline,', 'target': 'packet change baseline', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_lifecycle_approvals_and_authorization', 'statement': 'Enumerated item is supported/enforced: lifecycle approvals and authorization,', 'target': 'lifecycle approvals and authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_evidence', 'statement': 'Enumerated item is supported/enforced: evidence,', 'target': 'evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_backend_verification_records', 'statement': 'Enumerated item is supported/enforced: backend verification records,', 'target': 'backend verification records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_traceability', 'statement': 'Enumerated item is supported/enforced: review traceability,', 'target': 'review traceability', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_final_claim_audit', 'statement': 'Enumerated item is supported/enforced: final claim audit.', 'target': 'final claim audit', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_goal_and_acs_are_required_before_ac_approval', 'statement': 'Enumerated item is supported/enforced: Goal and ACs are required before AC approval.', 'target': 'Goal and ACs are required before AC approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_approval_is_required_before_work_packet_approval', 'statement': 'Enumerated item is supported/enforced: AC approval is required before Work Packet approval except for explicit eligible Plan-child batch approval of non-source-derived ACs.', 'target': 'AC approval is required before Work Packet approval except for explicit eligible Plan-child batch approval of non-source-derived ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_work_packet_approval_is_required_before_implementati', 'statement': 'Enumerated item is supported/enforced: Work Packet approval is required before implementation authorization.', 'target': 'Work Packet approval is required before implementation authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_authorization_and_packet_change_basel', 'statement': 'Enumerated item is supported/enforced: Implementation authorization and packet change baseline capture are one atomic governed action; PacketChangeBaseline capture must succeed before the authorization HumanDecision is recorded.', 'target': 'Implementation authorization and packet change baseline capture are one atomic governed action; PacketChangeBaseline capture must succeed before the authorizati', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pre_implementation_validation_is_required_before_imp', 'statement': 'Enumerated item is supported/enforced: Pre-implementation validation is required before implementation source changes.', 'target': 'Pre-implementation validation is required before implementation source changes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approval_is_invalidated_when_approved_title_parent_p', 'statement': 'Enumerated item is supported/enforced: Approval is invalidated when approved title, parent Plan linkage, Plan slice linkage, intent, ACs, source evidence, approved scope fields such as allowed globs, classification, docs policy, platform, architecture, or runtime baseline reference changes. Scope deviations and docs requirements are review context unless included in an approved-field set.', 'target': 'Approval is invalidated when approved title, parent Plan linkage, Plan slice linkage, intent, ACs, source evidence, approved scope fields such as allowed globs,', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_generic_update_actions_must_not_silently_change_appr', 'statement': 'Enumerated item is supported/enforced: Generic update actions must not silently change approved fields. If an update touches approved fields, Spec Guard must either reject it as a protected approved-field update or apply it and deterministically invalidate every dependent approval/authorization with diagnostics and next actions. The action result must list every invalidated decision.', 'target': 'Generic update actions must not silently change approved fields. If an update touches approved fields, Spec Guard must either reject it as a protected approved-', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_update_must_reject_changes_to_plan_approved_fie', 'statement': 'Enumerated item is supported/enforced: `plan.update` must reject changes to Plan-approved fields. Because there is no persisted draft Plan state, an approved Plan cannot be moved back to draft by mutation. Changing approved Plan intent requires a new Plan or a registered Plan amendment action with its own review snapshot and Plan approval decision.', 'target': '`plan.update` must reject changes to Plan-approved fields. Because there is no persisted draft Plan state, an approved Plan cannot be moved back to draft by mut', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_children_created', 'statement': 'Enumerated item is supported/enforced: `children_created`,', 'target': '`children_created`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_in_progress', 'statement': 'Enumerated item is supported/enforced: `in_progress`,', 'target': '`in_progress`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_complete', 'statement': 'Enumerated item is supported/enforced: `complete`,', 'target': '`complete`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_id', 'statement': 'Enumerated item is supported/enforced: id,', 'target': 'id', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_goal', 'statement': 'Enumerated item is supported/enforced: goal,', 'target': 'goal', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approved_plan_proposal_record', 'statement': 'Enumerated item is supported/enforced: approved Plan proposal record,', 'target': 'approved Plan proposal record', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_child_work_packet_references', 'statement': 'Enumerated item is supported/enforced: child Work Packet references,', 'target': 'child Work Packet references', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_product_platform_context', 'statement': 'Enumerated item is supported/enforced: product/platform context,', 'target': 'product/platform context', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_status', 'statement': 'Enumerated item is supported/enforced: status,', 'target': 'status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_diagnostics', 'statement': 'Enumerated item is supported/enforced: diagnostics.', 'target': 'diagnostics', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_reusable_api_reusable_public_api_sdk_library_api_or', 'statement': 'Enumerated item is supported/enforced: `reusable_api`: reusable public API, SDK, library API, or stable callable contract,', 'target': '`reusable_api`: reusable public API, SDK, library API, or stable callable contract', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_rest_api_route_endpoint_service_boundary_or_network', 'statement': 'Enumerated item is supported/enforced: `rest_api`: route, endpoint, service boundary, or network API,', 'target': '`rest_api`: route, endpoint, service boundary, or network API', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_reusable_ui_reusable_ui_component_ui_package_public', 'statement': 'Enumerated item is supported/enforced: `reusable_ui`: reusable UI component, UI package, public props/events/slots/styling/accessibility contract, or importable UI surface,', 'target': '`reusable_ui`: reusable UI component, UI package, public props/events/slots/styling/accessibility contract, or importable UI surface', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_one_off_application_ui_application_specific_ui_behav', 'statement': 'Enumerated item is supported/enforced: `one_off_application_ui`: application-specific UI behavior that is not reusable,', 'target': '`one_off_application_ui`: application-specific UI behavior that is not reusable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_direct_behavior_non_api_product_behavior_scripts_int', 'statement': 'Enumerated item is supported/enforced: `direct_behavior`: non-API product behavior, scripts, internal behavior, or localized implementation behavior,', 'target': '`direct_behavior`: non-API product behavior, scripts, internal behavior, or localized implementation behavior', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_operational_document_documentation_or_operational_co', 'statement': 'Enumerated item is supported/enforced: `operational_document`: documentation or operational content as the primary deliverable,', 'target': '`operational_document`: documentation or operational content as the primary deliverable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_bugfix_correction_of_reported_behavior', 'statement': 'Enumerated item is supported/enforced: `bugfix`: correction of reported behavior.', 'target': '`bugfix`: correction of reported behavior', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_reusable_api', 'statement': 'Enumerated item is supported/enforced: `reusable_api`,', 'target': '`reusable_api`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_rest_api', 'statement': 'Enumerated item is supported/enforced: `rest_api`,', 'target': '`rest_api`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_reusable_ui', 'statement': 'Enumerated item is supported/enforced: `reusable_ui`.', 'target': '`reusable_ui`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_docs_must_exist_and_be_linked_to_approved_a', 'statement': 'Enumerated item is supported/enforced: `required`: docs must exist and be linked to approved ACs before pre-implementation validation passes,', 'target': '`required`: docs must exist and be linked to approved ACs before pre-implementation validation passes', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_changed_docs_are_not_required_before_pre_implementat', 'statement': 'Enumerated item is supported/enforced: `changed`: docs are not required before pre-implementation validation, but docs must be updated and a `docs_updated` claim must pass backend verification before review completion,', 'target': '`changed`: docs are not required before pre-implementation validation, but docs must be updated and a `docs_updated` claim must pass backend verification before', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_none_required_docs_are_not_required_and_docs_none_re', 'statement': 'Enumerated item is supported/enforced: `none_required`: docs are not required and `docs.none_required_reason` records why,', 'target': '`none_required`: docs are not required and `docs.none_required_reason` records why', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_not_applicable_docs_do_not_apply_and_docs_not_applic', 'statement': 'Enumerated item is supported/enforced: `not_applicable`: docs do not apply and `docs.not_applicable_reason` records why.', 'target': '`not_applicable`: docs do not apply and `docs.not_applicable_reason` records why', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_path_is_inside_project', 'statement': 'Enumerated item is supported/enforced: docs path is inside project,', 'target': 'docs path is inside project', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_exist', 'statement': 'Enumerated item is supported/enforced: docs exist,', 'target': 'docs exist', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_link_to_approved_acceptance_item_refs', 'statement': 'Enumerated item is supported/enforced: docs link to approved AC IDs,', 'target': 'docs link to approved AC IDs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_backend_verification_for_docs_to_ac_mapping', 'statement': 'Enumerated item is supported/enforced: required backend verification for docs-to-AC mapping passed.', 'target': 'required backend verification for docs-to-AC mapping passed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_intake_status_effect_creates_draft', 'statement': 'Table row is implemented: Action/outcome: `work.intake`; Status effect: creates `draft`', 'target': 'Action/outcome: `work.intake`; Status effect: creates `draft`', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_intent_draft_with_at_least_one_ac_and_require', 'statement': 'Table row is implemented: Action/outcome: `work.intent.draft` with at least one AC and required draft intent fields present; Status effect: `pending_ac_approval`', 'target': 'Action/outcome: `work.intent.draft` with at least one AC and required draft intent fields present; Status effect: `pending_ac_approval`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_intent_draft_without_acs_or_with_missing_requ', 'statement': 'Table row is implemented: Action/outcome: `work.intent.draft` without ACs or with missing required draft intent fields; Status effect: `draft`', 'target': 'Action/outcome: `work.intent.draft` without ACs or with missing required draft intent fields; Status effect: `draft`', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_ac_approve_yes_status_effect_pending_packet_a', 'statement': 'Table row is implemented: Action/outcome: `work.ac.approve` Yes; Status effect: `pending_packet_approval` unless packet approval is already batch-recorded', 'target': 'Action/outcome: `work.ac.approve` Yes; Status effect: `pending_packet_approval` unless packet approval is already batch-recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_ac_approve_no_status_effect_blocked_with_decl', 'statement': 'Table row is implemented: Action/outcome: `work.ac.approve` No; Status effect: `blocked` with decline diagnostics', 'target': 'Action/outcome: `work.ac.approve` No; Status effect: `blocked` with decline diagnostics', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_approve_yes_status_effect_approved', 'statement': 'Table row is implemented: Action/outcome: `work.approve` Yes; Status effect: `approved`', 'target': 'Action/outcome: `work.approve` Yes; Status effect: `approved`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_approve_no_status_effect_blocked_with_decline', 'statement': 'Table row is implemented: Action/outcome: `work.approve` No; Status effect: `blocked` with decline diagnostics', 'target': 'Action/outcome: `work.approve` No; Status effect: `blocked` with decline diagnostics', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_authorize_yes_and_baseline_capture_succeeds_s', 'statement': 'Table row is implemented: Action/outcome: `work.authorize` Yes and baseline capture succeeds; Status effect: `authorized`', 'target': 'Action/outcome: `work.authorize` Yes and baseline capture succeeds; Status effect: `authorized`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_authorize_no_status_effect_remains_approved_w', 'statement': 'Table row is implemented: Action/outcome: `work.authorize` No; Status effect: remains `approved` with authorization-declined diagnostics', 'target': 'Action/outcome: `work.authorize` No; Status effect: remains `approved` with authorization-declined diagnostics', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_authorize_failed_packetchangebaseline_capture', 'statement': 'Table row is implemented: Action/outcome: `work.authorize` failed PacketChangeBaseline capture; Status effect: remains `approved` with baseline-capture diagnostics and no authorization decision', 'target': 'Action/outcome: `work.authorize` failed PacketChangeBaseline capture; Status effect: remains `approved` with baseline-capture diagnostics and no authorization d', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_work_preimplementation_validate_success_status_eff', 'statement': 'Table row is implemented: Action/outcome: `work.preimplementation.validate` success; Status effect: `preimplementation_validated`', 'target': 'Action/outcome: `work.preimplementation.validate` success; Status effect: `preimplementation_validated`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_implementation_start_after_preimplementation', 'statement': 'Table row is implemented: Action/outcome: `work.implementation.start` after preimplementation validation; Status effect: `implementation_active`', 'target': 'Action/outcome: `work.implementation.start` after preimplementation validation; Status effect: `implementation_active`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_implementation_complete_after_implementation', 'statement': 'Table row is implemented: Action/outcome: `work.implementation.complete` after implementation evidence is recorded; Status effect: `implemented` until `work.review.complete`', 'target': 'Action/outcome: `work.implementation.complete` after implementation evidence is recorded; Status effect: `implemented` until `work.review.complete`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_work_review_complete_success_status_effect_review', 'statement': 'Table row is implemented: Action/outcome: `work.review.complete` success; Status effect: `review_complete`', 'target': 'Action/outcome: `work.review.complete` success; Status effect: `review_complete`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_archive_action_status_effect_archived', 'statement': 'Table row is implemented: Action/outcome: archive action; Status effect: `archived`', 'target': 'Action/outcome: archive action; Status effect: `archived`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_plan_approve_yes_status_effect_creates_plan_with_a', 'statement': 'Table row is implemented: Action/outcome: `plan.approve` Yes; Status effect: creates Plan with `approved`', 'target': 'Action/outcome: `plan.approve` Yes; Status effect: creates Plan with `approved`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_plan_approve_no_status_effect_creates_no_plan_stor', 'statement': 'Table row is implemented: Action/outcome: `plan.approve` No; Status effect: creates no Plan; stores standalone decline decision/audit', 'target': 'Action/outcome: `plan.approve` No; Status effect: creates no Plan; stores standalone decline decision/audit', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_plan_child_create_creates_first_child_status_effec', 'statement': 'Table row is implemented: Action/outcome: `plan.child.create` creates first child; Status effect: `children_created`; created child starts `pending_ac_approval` when ACs exist and no batch approvals are recorded, otherwise `draft`', 'target': 'Action/outcome: `plan.child.create` creates first child; Status effect: `children_created`; created child starts `pending_ac_approval` when ACs exist and no bat', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_plan_batch_proceed_option_2_3_4_creates_one_or_mor', 'statement': 'Table row is implemented: Action/outcome: `plan.batch_proceed` option 2/3/4 creates one or more children; Status effect: `children_created` or `in_progress` when any child is authorized/active', 'target': 'Action/outcome: `plan.batch_proceed` option 2/3/4 creates one or more children; Status effect: `children_created` or `in_progress` when any child is authorized/', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_child_work_packet_starts_implementation_status_eff', 'statement': 'Table row is implemented: Action/outcome: child Work Packet starts implementation; Status effect: `in_progress`', 'target': 'Action/outcome: child Work Packet starts implementation; Status effect: `in_progress`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_all_non_archived_child_work_packets_reach_review_c', 'statement': 'Table row is implemented: Action/outcome: all non-archived child Work Packets reach `review_complete`; Status effect: `complete`', 'target': 'Action/outcome: all non-archived child Work Packets reach `review_complete`; Status effect: `complete`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_action_outcome_blocking_diagnostics_prevent_child_creation_or_pro', 'statement': 'Table row is implemented: Action/outcome: blocking diagnostics prevent child creation or progress; Status effect: `blocked`', 'target': 'Action/outcome: blocking diagnostics prevent child creation or progress; Status effect: `blocked`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'table_row_is_implemented_action_outcome_plan_archive_status_effect_archived', 'statement': 'Table row is implemented: Action/outcome: `plan.archive`; Status effect: `archived`', 'target': 'Action/outcome: `plan.archive`; Status effect: `archived`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
