"""Executable specification for US-09: Intent, source-derived ACs, and AC approval."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'for_any_prompt_requiring_repository_mutation_the_frontend_agent_should_draft', 'statement': 'For any prompt requiring repository mutation, the frontend agent should draft:', 'target': 'For any prompt requiring repository mutation, the frontend agent should draft:', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'required_fields_for_moving_from_draft_to_pending_ac_approval_are_exactly_non_empty_title_n', 'statement': 'Required fields for moving from `draft` to `pending_ac_approval` are exactly: non-empty `title`, non-empty `intent.goal`, and at least one AcceptanceCriterion.', 'target': 'Required fields for moving from `draft` to `pending_ac_approval` are exactly: non-empty `title`, non-empty `intent.goal`, and at least one AcceptanceCriterion', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_should_not_prompt_separately_for_every_non_ac_intent_field_by_default', 'statement': 'Spec Guard should not prompt separately for every non-AC intent field by default.', 'target': 'Spec Guard should not prompt separately for every non-AC intent field by default', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'generated_fields_must_not_contain_placeholders_undefined_or_process_boilerplate', 'statement': 'Generated fields must not contain placeholders, `undefined`, or process boilerplate.', 'target': 'Generated fields must not contain placeholders, `undefined`, or process boilerplate', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'when_acs_are_derived_from_source_mockup_design_screenshot_pdf_ui_artifact_user_story_or_ot', 'statement': 'When ACs are derived from source, mockup, design, screenshot, PDF, UI artifact, user story, or other interpreted material:', 'target': 'When ACs are derived from source, mockup, design, screenshot, PDF, UI artifact, user story, or other interpreted material:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'they_must_be_included_in_the_displayed_ac_list', 'statement': 'they must be included in the displayed AC list,', 'target': 'they must be included in the displayed AC list', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'each_source_derived_ac_must_show_source_evidence', 'statement': 'each source-derived AC must show source/evidence,', 'target': 'each source-derived AC must show source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_review_surface_must_clearly_mark_which_acs_are_source_derived', 'statement': 'the review surface must clearly mark which ACs are source-derived,', 'target': 'the review surface must clearly mark which ACs are source-derived', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'source_derived_acs_are_never_batch_approved_or_batch_authorized', 'statement': 'source-derived ACs are never batch-approved or batch-authorized,', 'target': 'source-derived ACs are never batch-approved or batch-authorized', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'any_packet_containing_source_derived_acs_may_be_batch_created_only', 'statement': 'any packet containing source-derived ACs may be batch-created only', 'target': 'any packet containing source-derived ACs may be batch-created only', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'must_then_use_normal_per_child_ac_approval_work_packet_approval_and_authorization_gates', 'statement': 'must then use normal per-child AC approval, Work Packet approval, and authorization gates,', 'target': 'must then use normal per-child AC approval, Work Packet approval, and authorization gates', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'there_is_no_separate_one_ac_at_a_time_source_derived_approval_flow', 'statement': 'there is no separate one-AC-at-a-time source-derived approval flow,', 'target': 'there is no separate one-AC-at-a-time source-derived approval flow', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'yes_on_ac_approval_approves_the_displayed_ac_list_including_displayed_source_derived_acs_a', 'statement': 'Yes on AC approval approves the displayed AC list, including displayed source-derived ACs and their source/evidence.', 'target': 'Yes on AC approval approves the displayed AC list, including displayed source-derived ACs and their source/evidence', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'spec_guard_must_not_infer_canonical_source_derived_acs_without_human_approval', 'statement': 'Spec Guard must not infer canonical source-derived ACs without human approval.', 'target': 'Spec Guard must not infer canonical source-derived ACs without human approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'source_material_used_for_source_derived_acs_must_be_represented_by_a_resolvable_sourcearti', 'statement': 'Source material used for source-derived ACs must be represented by a resolvable SourceArtifactRef.', 'target': 'Source material used for source-derived ACs must be represented by a resolvable SourceArtifactRef', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'spec_guard_must_not_maintain_a_closed_list_of_acceptable_source_kinds', 'statement': 'Spec Guard must not maintain a closed list of acceptable source kinds.', 'target': 'Spec Guard must not maintain a closed list of acceptable source kinds', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'a_sourceartifact_revision_must_be_immutable_and_content_addressed', 'statement': 'A SourceArtifact revision must be immutable and content-addressed.', 'target': 'A SourceArtifact revision must be immutable and content-addressed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'sourceartifact_registration_must_capture_bytes_or_a_deterministic_descriptor_plus_content', 'statement': 'SourceArtifact registration must capture bytes or a deterministic descriptor plus content hash sufficient to identify and review the material later.', 'target': 'SourceArtifact registration must capture bytes or a deterministic descriptor plus content hash sufficient to identify and review the material later', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'hash_only_registration_is_invalid_unless_the_descriptor_includes_a_deterministic_retrieval', 'statement': 'Hash-only registration is invalid unless the descriptor includes a deterministic retrieval mechanism and enough metadata for the reviewed material to be presented again.', 'target': 'Hash-only registration is invalid unless the descriptor includes a deterministic retrieval mechanism and enough metadata for the reviewed material to be present', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'every_sourceartifact_revision_must_include_an_immutable_content_ref_or_descriptor_retrieva', 'statement': 'Every SourceArtifact revision must include an immutable `content_ref` or descriptor retrieval mechanism that allows the reviewed material or deterministic descriptor to be re-presented.', 'target': 'Every SourceArtifact revision must include an immutable `content_ref` or descriptor retrieval mechanism that allows the reviewed material or deterministic descr', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_source_that_cannot_be_assigned_a_stable_id_immutable_revision_and_content_hash_cannot_sa', 'statement': 'A source that cannot be assigned a stable id, immutable revision, and content hash cannot satisfy source-derived AC evidence.', 'target': 'A source that cannot be assigned a stable id, immutable revision, and content hash cannot satisfy source-derived AC evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'source_artifact_register_creates_revision_1_for_new_source_material', 'statement': '`source_artifact.register` creates revision 1 for new source material.', 'target': '`source_artifact.register` creates revision 1 for new source material', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'source_artifact_update_creates_a_new_immutable_revision', 'statement': '`source_artifact.update` creates a new immutable revision', 'target': '`source_artifact.update` creates a new immutable revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'must_not_alter_prior_revisions', 'statement': 'must not alter prior revisions.', 'target': 'must not alter prior revisions', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'sourceartifactrefs_used_in_approved_source_derived_acs_must_resolve_at_review_time_and_at', 'statement': 'SourceArtifactRefs used in approved source-derived ACs must resolve at review time and at later staleness checks.', 'target': 'SourceArtifactRefs used in approved source-derived ACs must resolve at review time and at later staleness checks', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'built_in_artifact_refs_must_use_the_exact_artifact_type_stored_on_the_artifact', 'statement': 'Built-in artifact refs must use the exact `artifact_type` stored on the artifact.', 'target': 'Built-in artifact refs must use the exact `artifact_type` stored on the artifact', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'source_artifact_register_and_source_artifact_update_accept_exactly_one_of_captured_bytes_o', 'statement': '`source_artifact.register` and `source_artifact.update` accept exactly one of captured bytes or descriptor input.', 'target': '`source_artifact.register` and `source_artifact.update` accept exactly one of captured bytes or descriptor input', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_captured_bytes_callers_provide_content_bytes_base64', 'statement': 'For captured bytes, callers provide `content_bytes_base64`', 'target': 'For captured bytes, callers provide `content_bytes_base64`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'spec_guard_decodes_base64_computes_sha_256_over_the_decoded_bytes_stores_the_bytes_in_immu', 'statement': 'Spec Guard decodes base64, computes SHA-256 over the decoded bytes, stores the bytes in immutable blob storage, sets `content_ref` to that blob reference,', 'target': 'Spec Guard decodes base64, computes SHA-256 over the decoded bytes, stores the bytes in immutable blob storage, sets `content_ref` to that blob reference', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'stores_descriptor_null', 'statement': 'stores `descriptor: null`.', 'target': 'stores `descriptor: null`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'spec_guard_canonicalizes_the_descriptor_json_computes_sha_256_over_the_canonical_descripto', 'statement': 'Spec Guard canonicalizes the descriptor JSON, computes SHA-256 over the canonical descriptor bytes unless `content_hash` is supplied and matches that canonical hash, stores the descriptor as immutable content,', 'target': 'Spec Guard canonicalizes the descriptor JSON, computes SHA-256 over the canonical descriptor bytes unless `content_hash` is supplied and matches that canonical ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'sets_content_ref_to_the_descriptor_record', 'statement': 'sets `content_ref` to the descriptor record.', 'target': 'sets `content_ref` to the descriptor record', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'hash_only_input_without_bytes_or_descriptor_is_invalid', 'statement': 'Hash-only input without bytes or descriptor is invalid.', 'target': 'Hash-only input without bytes or descriptor is invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'on_update_absent_metadata_fields_inherit_the_prior_revision', 'statement': 'On update, absent metadata fields inherit the prior revision', 'target': 'On update, absent metadata fields inherit the prior revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'locator_null_explicitly_clears_the_locator', 'statement': '`locator: null` explicitly clears the locator', 'target': '`locator: null` explicitly clears the locator', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_snapshot_includes_the_complete_ac_payload_being_reviewed_source_evidence_for_source_de', 'statement': 'The snapshot includes the complete AC payload being reviewed, source/evidence for source-derived ACs, snapshot hash, and snapshot revision.', 'target': 'The snapshot includes the complete AC payload being reviewed, source/evidence for source-derived ACs, snapshot hash, and snapshot revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'work_ac_approve_must_validate_the_supplied_review_snapshot_hash_against_acreviewsnapshotpa', 'statement': '`work.ac.approve` must validate the supplied review snapshot hash against `AcReviewSnapshotPayload`, not against the raw AC array alone.', 'target': '`work.ac.approve` must validate the supplied review snapshot hash against `AcReviewSnapshotPayload`, not against the raw AC array alone', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'compares_that_hash_to_review_snapshot_hash', 'statement': 'compares that hash to `review_snapshot_hash`.', 'target': 'compares that hash to `review_snapshot_hash`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'records_ac_approval', 'statement': 'records AC approval.', 'target': 'records AC approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'on_numbered_no_spec_guard_records_decline_or_blocks_as_appropriate_without_approving_the_a', 'statement': 'On numbered No, Spec Guard records decline or blocks as appropriate without approving the AC payload.', 'target': 'On numbered No, Spec Guard records decline or blocks as appropriate without approving the AC payload', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'on_discuss_the_action_records_no_mutation_and_should_not_be_called_to_persist_refinements', 'statement': 'On Discuss, the action records no mutation and should not be called to persist refinements.', 'target': 'On Discuss, the action records no mutation and should not be called to persist refinements', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'yes_records_ac_approval_bound_to_the_displayed_ac_review_snapshot_hash', 'statement': 'Yes records AC approval bound to the displayed AC review snapshot hash.', 'target': 'Yes records AC approval bound to the displayed AC review snapshot hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_records_decline_or_blocks_as_appropriate', 'statement': 'No records decline or blocks as appropriate.', 'target': 'No records decline or blocks as appropriate', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'discuss_records_no_mutation', 'statement': 'Discuss records no mutation.', 'target': 'Discuss records no mutation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'during_discuss_the_frontend_agent_may_refine_acs_in_the_agent_session_only', 'statement': 'During Discuss, the frontend agent may refine ACs in the agent session only.', 'target': 'During Discuss, the frontend agent may refine ACs in the agent session only', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'intermediate_ac_refinements_during_discuss_must_not_mutate_canonical_acs_approval_state_de', 'statement': 'Intermediate AC refinements during Discuss must not mutate canonical ACs, approval state, decline state, or artifact hashes.', 'target': 'Intermediate AC refinements during Discuss must not mutate canonical ACs, approval state, decline state, or artifact hashes', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'after_refinement_the_frontend_agent_must_re_present_the_current_proposed_acs_through_the_s', 'statement': 'After refinement, the frontend agent must re-present the current proposed ACs through the same Yes/No/Discuss gate.', 'target': 'After refinement, the frontend agent must re-present the current proposed ACs through the same Yes/No/Discuss gate', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_loop_resolves_only_through_numbered_yes_or_numbered_no', 'statement': 'The loop resolves only through numbered Yes or numbered No.', 'target': 'The loop resolves only through numbered Yes or numbered No', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_backend_verifier_must_not_judge_whether_approved_acs_are_correct_or_complete', 'statement': 'The backend verifier must not judge whether approved ACs are correct or complete.', 'target': 'The backend verifier must not judge whether approved ACs are correct or complete', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_goal', 'statement': 'Enumerated item is supported/enforced: goal,', 'target': 'goal', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_desired_outcomes', 'statement': 'Enumerated item is supported/enforced: desired outcomes,', 'target': 'desired outcomes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_in_scope', 'statement': 'Enumerated item is supported/enforced: in scope,', 'target': 'in scope', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_out_of_scope', 'statement': 'Enumerated item is supported/enforced: out of scope,', 'target': 'out of scope', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_users_actors_if_relevant', 'statement': 'Enumerated item is supported/enforced: users/actors if relevant,', 'target': 'users/actors if relevant', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_edge_cases_if_relevant', 'statement': 'Enumerated item is supported/enforced: edge cases if relevant,', 'target': 'edge cases if relevant', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_open_questions_if_any', 'statement': 'Enumerated item is supported/enforced: open questions if any,', 'target': 'open questions if any', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acs', 'statement': 'Enumerated item is supported/enforced: ACs.', 'target': 'ACs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_they_must_be_included_in_the_displayed_ac_list', 'statement': 'Enumerated item is supported/enforced: they must be included in the displayed AC list,', 'target': 'they must be included in the displayed AC list', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_each_source_derived_ac_must_show_source_evidence', 'statement': 'Enumerated item is supported/enforced: each source-derived AC must show source/evidence,', 'target': 'each source-derived AC must show source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_review_surface_must_clearly_mark_which_acs_are_s', 'statement': 'Enumerated item is supported/enforced: the review surface must clearly mark which ACs are source-derived,', 'target': 'the review surface must clearly mark which ACs are source-derived', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_human_approves_them_through_the_same_ac_approval', 'statement': 'Enumerated item is supported/enforced: the human approves them through the same AC approval gate as all other ACs,', 'target': 'the human approves them through the same AC approval gate as all other ACs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_derived_acs_are_never_batch_approved_or_batch', 'statement': 'Enumerated item is supported/enforced: source-derived ACs are never batch-approved or batch-authorized,', 'target': 'source-derived ACs are never batch-approved or batch-authorized', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_any_packet_containing_source_derived_acs_may_be_batc', 'statement': 'Enumerated item is supported/enforced: any packet containing source-derived ACs may be batch-created only and must then use normal per-child AC approval, Work Packet approval, and authorization gates,', 'target': 'any packet containing source-derived ACs may be batch-created only and must then use normal per-child AC approval, Work Packet approval, and authorization gates', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_there_is_no_separate_one_ac_at_a_time_source_derived', 'statement': 'Enumerated item is supported/enforced: there is no separate one-AC-at-a-time source-derived approval flow,', 'target': 'there is no separate one-AC-at-a-time source-derived approval flow', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_there_is_no_custom_feature_status_prompt', 'statement': 'Enumerated item is supported/enforced: there is no custom feature-status prompt.', 'target': 'there is no custom feature-status prompt', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_yes', 'statement': 'Ordered requirement is supported/enforced: Yes', 'target': 'Ordered requirement is supported/enforced: Yes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_no', 'statement': 'Ordered requirement is supported/enforced: No', 'target': 'Ordered requirement is supported/enforced: No', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_discuss', 'statement': 'Ordered requirement is supported/enforced: Discuss', 'target': 'Ordered requirement is supported/enforced: Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_yes_records_ac_approval_bound_to_the_displayed_ac_re', 'statement': 'Enumerated item is supported/enforced: Yes records AC approval bound to the displayed AC review snapshot hash.', 'target': 'Yes records AC approval bound to the displayed AC review snapshot hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_records_decline_or_blocks_as_appropriate', 'statement': 'Enumerated item is supported/enforced: No records decline or blocks as appropriate.', 'target': 'No records decline or blocks as appropriate', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_discuss_records_no_mutation', 'statement': 'Enumerated item is supported/enforced: Discuss records no mutation.', 'target': 'Discuss records no mutation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_during_discuss_the_frontend_agent_may_refine_acs_in', 'statement': 'Enumerated item is supported/enforced: During Discuss, the frontend agent may refine ACs in the agent session only.', 'target': 'During Discuss, the frontend agent may refine ACs in the agent session only', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_intermediate_ac_refinements_during_discuss_must_not', 'statement': 'Enumerated item is supported/enforced: Intermediate AC refinements during Discuss must not mutate canonical ACs, approval state, decline state, or artifact hashes.', 'target': 'Intermediate AC refinements during Discuss must not mutate canonical ACs, approval state, decline state, or artifact hashes', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_after_refinement_the_frontend_agent_must_re_present', 'statement': 'Enumerated item is supported/enforced: After refinement, the frontend agent must re-present the current proposed ACs through the same Yes/No/Discuss gate.', 'target': 'After refinement, the frontend agent must re-present the current proposed ACs through the same Yes/No/Discuss gate', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_loop_resolves_only_through_numbered_yes_or_numbe', 'statement': 'Enumerated item is supported/enforced: The loop resolves only through numbered Yes or numbered No.', 'target': 'The loop resolves only through numbered Yes or numbered No', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
