"""Executable specification for US-12: Implementation boundary and pre-implementation validation."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'spec_guard_must_classify_changed_paths_into_the_canonical_changefilecategory_enum_using_co', 'statement': 'Spec Guard must classify changed paths into the canonical `ChangeFileCategory` enum using `Config.path_policy`.', 'target': 'Spec Guard must classify changed paths into the canonical `ChangeFileCategory` enum using `Config.path_policy`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_deterministic_classifier_normalizes_each_repository_relative_path_rejects_paths_outsid', 'statement': 'The deterministic classifier normalizes each repository-relative path, rejects paths outside the project, ignores paths matching `ignored_paths`, then assigns the first matching category in this fixed precedence: `spec_guard_artifact_evidence`, `docs`, `tests`, `runtime_product_configuration`, `implementation_source`, `generated_build_output`.', 'target': 'The deterministic classifier normalizes each repository-relative path, rejects paths outside the project, ignores paths matching `ignored_paths`, then assigns t', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'use_the_same_glob_engine_as_allowed_globs_validation', 'statement': 'use the same glob engine as allowed-globs validation.', 'target': 'use the same glob engine as allowed-globs validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'implementation_source_includes_files_that_affect_product_behavior_public_api_runtime_behav', 'statement': 'Implementation source includes files that affect product behavior, public API, runtime behavior, UI behavior, business logic, persistence, integration behavior, or shipped assets.', 'target': 'Implementation source includes files that affect product behavior, public API, runtime behavior, UI behavior, business logic, persistence, integration behavior,', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_ordering_gates_runtime_product_configuration_is_always_treated_as_implementation_like', 'statement': 'For ordering gates, `runtime_product_configuration` is always treated as implementation-like and pre-failure changes to it block pre-implementation validation', 'target': 'For ordering gates, `runtime_product_configuration` is always treated as implementation-like and pre-failure changes to it block pre-implementation validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'before_implementation_ready_state_allowed_changes_are_limited_to', 'statement': 'Before implementation-ready state, allowed changes are limited to:', 'target': 'Before implementation-ready state, allowed changes are limited to:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_docs', 'statement': 'required docs,', 'target': 'required docs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_governed_docs_tests_and_failure_first_evidence_for_a_packet_must_be_recorded_afte', 'statement': "Required governed docs, tests, and failure-first evidence for a packet must be recorded after packet change baseline capture to count for that packet's validation chain.", 'target': "Required governed docs, tests, and failure-first evidence for a packet must be recorded after packet change baseline capture to count for that packet's validati", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'pre_authorization_docs_tests_may_exist_but_they_are_treated_as_pre_existing_project_state', 'statement': 'Pre-authorization docs/tests may exist, but they are treated as pre-existing project state unless re-recorded with evidence after authorization', 'target': 'Pre-authorization docs/tests may exist, but they are treated as pre-existing project state unless re-recorded with evidence after authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'they_must_not_disappear_from_review_traceability_by_being_silently_absorbed_into_the_packe', 'statement': 'they must not disappear from review traceability by being silently absorbed into the packet baseline.', 'target': 'they must not disappear from review traceability by being silently absorbed into the packet baseline', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'implementation_source_changes_before_proven_failure_first_evidence_must_block_pre_implemen', 'statement': 'Implementation source changes before proven failure-first evidence must block pre-implementation validation.', 'target': 'Implementation source changes before proven failure-first evidence must block pre-implementation validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'docs_test_failure_test_pass_and_runtime_evidence_records_must_include_a_file_state_snapsho', 'statement': 'Docs, test failure, test pass, and runtime evidence records must include a file state snapshot captured by Spec Guard during the evidence action.', 'target': 'Docs, test failure, test pass, and runtime evidence records must include a file state snapshot captured by Spec Guard during the evidence action', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_snapshot_must_be_sufficient_to_compare_changed_files_against_the_packet_change_baselin', 'statement': 'The snapshot must be sufficient to compare changed files against the packet change baseline and prove whether implementation source had changed before failure-first evidence.', 'target': 'The snapshot must be sufficient to compare changed files against the packet change baseline and prove whether implementation source had changed before failure-f', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'evidence_without_the_required_file_state_snapshot_cannot_satisfy_pre_implementation_or_rev', 'statement': 'Evidence without the required file state snapshot cannot satisfy pre-implementation or review gates.', 'target': 'Evidence without the required file state snapshot cannot satisfy pre-implementation or review gates', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'command_backed_evidence_must_reference_a_kernel_created_commandresult_from_command_run', 'statement': 'Command-backed evidence must reference a kernel-created CommandResult from `command.run`.', 'target': 'Command-backed evidence must reference a kernel-created CommandResult from `command.run`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'frontend_agents_must_not_supply_exit_codes_command_status_command_timestamps_or_command_ou', 'statement': 'Frontend agents must not supply exit codes, command status, command timestamps, or command output as trusted facts.', 'target': 'Frontend agents must not supply exit codes, command status, command timestamps, or command output as trusted facts', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'evidence_actions_may_accept_paths_related_acceptance_item_refs_summaries_and_claim_text_from_the_fronten', 'statement': 'Evidence actions may accept paths, related AC IDs, summaries, and claim text from the frontend agent, but command, exit code, timing, status, and output references used as governed evidence must come from the deterministic kernel.', 'target': 'Evidence actions may accept paths, related AC IDs, summaries, and claim text from the frontend agent, but command, exit code, timing, status, and output referen', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'and_skipped_may_be_recorded_only_for_a_deterministic_precondition_skip_requested_by_comman', 'statement': 'and `skipped` may be recorded only for a deterministic precondition skip requested by `command.run`.', 'target': 'and `skipped` may be recorded only for a deterministic precondition skip requested by `command.run`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'evidence_status_is_derived_from_commandresult_status_as_follows_passed_maps_to_evidence_pa', 'statement': 'Evidence status is derived from CommandResult status as follows: `passed` maps to evidence `passed`', 'target': 'Evidence status is derived from CommandResult status as follows: `passed` maps to evidence `passed`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'commandresults_with_exit_code_null_spawn_errors_missing_executables_permission_errors_sign', 'statement': 'CommandResults with `exit_code: null`, spawn errors, missing executables, permission errors, signal termination, `timed_out`, or `skipped` cannot satisfy required failure-first, passing-test, or runtime evidence gates.', 'target': 'CommandResults with `exit_code: null`, spawn errors, missing executables, permission errors, signal termination, `timed_out`, or `skipped` cannot satisfy requir', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'mode_production_requires_commandresult_purpose_runtime_production', 'statement': 'Mode `production` requires CommandResult purpose `runtime_production`', 'target': 'Mode `production` requires CommandResult purpose `runtime_production`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'creates_evidencerecord_type_runtime_production', 'statement': 'creates EvidenceRecord type `runtime_production`.', 'target': 'creates EvidenceRecord type `runtime_production`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'mode_development_requires_commandresult_purpose_runtime_development', 'statement': 'Mode `development` requires CommandResult purpose `runtime_development`', 'target': 'Mode `development` requires CommandResult purpose `runtime_development`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'creates_evidencerecord_type_runtime_development', 'statement': 'creates EvidenceRecord type `runtime_development`.', 'target': 'creates EvidenceRecord type `runtime_development`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'evidence_actions_must_reject_a_commandresult_whose_purpose_is_incompatible_with_the_eviden', 'statement': 'Evidence actions must reject a CommandResult whose purpose is incompatible with the evidence type.', 'target': 'Evidence actions must reject a CommandResult whose purpose is incompatible with the evidence type', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'build_commands_may_be_recorded_as_commandresults_for_baseline_or_review_context_but_they_d', 'statement': 'Build commands may be recorded as CommandResults for baseline or review context, but they do not satisfy behavior test failure/pass evidence unless separately paired with compatible test evidence.', 'target': 'Build commands may be recorded as CommandResults for baseline or review context, but they do not satisfy behavior test failure/pass evidence unless separately p', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'frontend_agents_must_not_supply_file_state_snapshots_as_trusted_inputs', 'statement': 'Frontend agents must not supply file state snapshots as trusted inputs.', 'target': 'Frontend agents must not supply file state snapshots as trusted inputs', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'they_may_supply_paths_and_summaries_but_spec_guard_must_capture_vcs_or_manifest_state_itse', 'statement': 'They may supply paths and summaries, but Spec Guard must capture VCS or manifest state itself before committing the evidence record.', 'target': 'They may supply paths and summaries, but Spec Guard must capture VCS or manifest state itself before committing the evidence record', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'work_implementation_complete_must_register_at_least_one_implementation_summary_claim_from', 'statement': '`work.implementation.complete` must register at least one `implementation_summary` claim from its submitted summary and implementation file list.', 'target': '`work.implementation.complete` must register at least one `implementation_summary` claim from its submitted summary and implementation file list', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'review_completion_cannot_pass_until_that_claim_is_validated_or_superseded_through_work_cla', 'statement': 'Review completion cannot pass until that claim is validated or superseded through `work.claims.create`/`work.claims.validate` with evidence-backed final claims.', 'target': 'Review completion cannot pass until that claim is validated or superseded through `work.claims.create`/`work.claims.validate` with evidence-backed final claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'tests_must_be_cleanup_safe', 'statement': 'Tests must be cleanup-safe.', 'target': 'Tests must be cleanup-safe', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'retained_tests_must_not_test_documentation_text_documentation_formatting_documentation_fil', 'statement': 'Retained tests must not test documentation text, documentation formatting, documentation files, headings, examples, or links.', 'target': 'Retained tests must not test documentation text, documentation formatting, documentation files, headings, examples, or links', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'documentation_itself_is_never_governed_by_retained_tests', 'statement': 'Documentation itself is never governed by retained tests.', 'target': 'Documentation itself is never governed by retained tests', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'deterministic_retained_doc_test_detection_is_byte_string_based_and_language_independent_a', 'statement': 'Deterministic retained-doc-test detection is byte/string based and language-independent: a retained test is flagged when its path also matches a docs glob, when its path matches `Config.path_policy.docs_test_manifests`, or when its UTF-8-decoded content contains an exact normalized docs/content path token from docs evidence/path policy together with one of these case-sensitive operation tokens in the same file: `readFile`, `readFileSync`, `open`, `openSync`, `import`, `require`, `fetch`, `assert`, `expect`, `should`, `toContain`, `toMatch`.', 'target': 'Deterministic retained-doc-test detection is byte/string based and language-independent: a retained test is flagged when its path also matches a docs glob, when', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_retained_test_is_also_flagged_when_it_contains_exact_known_docs_heading_link_example_tok', 'statement': 'A retained test is also flagged when it contains exact known docs heading/link/example tokens captured in docs EvidenceRecords and any assertion token from the list above.', 'target': 'A retained test is also flagged when it contains exact known docs heading/link/example tokens captured in docs EvidenceRecords and any assertion token from the ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'non_utf_8_test_files_or_suspected_documentation_targeting_behavior_not_caught_by_these_det', 'statement': 'Non-UTF-8 test files or suspected documentation-targeting behavior not caught by these deterministic rules require backend verification of a `retained_test_not_docs` claim before review completion.', 'target': 'Non-UTF-8 test files or suspected documentation-targeting behavior not caught by these deterministic rules require backend verification of a `retained_test_not_', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'passing_or_failing_test_evidence_must_not_leave_persistent_artifacts_generated_files_datab', 'statement': 'Passing or failing test evidence must not leave persistent artifacts, generated files, database tables, database rows, external resources, orphan processes, modified runtime state, or other side effects unless those changes are explicitly approved as part of the product change.', 'target': 'Passing or failing test evidence must not leave persistent artifacts, generated files, database tables, database rows, external resources, orphan processes, mod', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'any_temporary_artifacts_resources_created_during_tests_must_be_cleaned_up_by_the_test_or_t', 'statement': 'Any temporary artifacts/resources created during tests must be cleaned up by the test or test harness.', 'target': 'Any temporary artifacts/resources created during tests must be cleaned up by the test or test harness', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'database_backed_tests_must_isolate_state_and_clean_up_records_tables_rows_indexes_queues_b', 'statement': 'Database-backed tests must isolate state and clean up records, tables, rows, indexes, queues, buckets, messages, or external resources they create unless the approved AC explicitly requires persistent seed/schema changes.', 'target': 'Database-backed tests must isolate state and clean up records, tables, rows, indexes, queues, buckets, messages, or external resources they create unless the ap', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'cleanup_verification_is_recorded_through_work_evidence_cleanup', 'statement': 'Cleanup verification is recorded through `work.evidence.cleanup`.', 'target': 'Cleanup verification is recorded through `work.evidence.cleanup`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_test_runtime_commands_with_non_empty_resource_categories_command_run_must_capture_conf', 'statement': 'For test/runtime commands with non-empty `resource_categories`, `command.run` must capture configured cleanup observer before-observations immediately before spawning the command and after-observations immediately after command completion/timeout/termination,', 'target': 'For test/runtime commands with non-empty `resource_categories`, `command.run` must capture configured cleanup observer before-observations immediately before sp', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'store_them_on_the_commandresult', 'statement': 'store them on the CommandResult.', 'target': 'store them on the CommandResult', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'checked_resource_categories_may_be_requested_by_the_caller_but_before_after_observations_a', 'statement': 'Checked resource categories may be requested by the caller, but before/after observations and side-effect status must be kernel-captured, command-backed, or derived from deterministic evidence records.', 'target': 'Checked resource categories may be requested by the caller, but before/after observations and side-effect status must be kernel-captured, command-backed, or der', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'caller_supplied_cleanup_summaries_are_claims_only_and_cannot_establish_cleanup_truth', 'statement': 'Caller-supplied cleanup summaries are claims only and cannot establish cleanup truth.', 'target': 'Caller-supplied cleanup summaries are claims only and cannot establish cleanup truth', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'cleanup_records_must_store_checked_resource_categories_kernel_captured_before_after_observ', 'statement': 'Cleanup records must store checked resource categories, kernel-captured before/after observations or CommandResult refs, side-effect status derived by the kernel, related command/evidence refs, and any remaining cleanup actions.', 'target': 'Cleanup records must store checked resource categories, kernel-captured before/after observations or CommandResult refs, side-effect status derived by the kerne', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_files_observer_records_a_manifest_of_project_relative_paths_sizes_mtimes_and_content_h', 'statement': 'The `files` observer records a manifest of project-relative paths, sizes, mtimes, and content hashes under allowed temp/output/resource paths before and after the command', 'target': 'The `files` observer records a manifest of project-relative paths, sizes, mtimes, and content hashes under allowed temp/output/resource paths before and after t', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'comparison_rule_no_new_resources_passes_only_when_no_unapproved_new_or_modified_paths_rema', 'statement': 'comparison rule `no_new_resources` passes only when no unapproved new or modified paths remain.', 'target': 'comparison rule `no_new_resources` passes only when no unapproved new or modified paths remain', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_processes_observer_records_child_process_ids_command_lines', 'statement': 'The `processes` observer records child process ids, command lines,', 'target': 'The `processes` observer records child process ids, command lines', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'start_times_for_processes_spawned_by_the_command_process_tree', 'statement': 'start times for processes spawned by the command process tree', 'target': 'start times for processes spawned by the command process tree', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_passes_only_when_no_spawned_process_remains_alive_after_cleanup', 'statement': 'it passes only when no spawned process remains alive after cleanup.', 'target': 'it passes only when no spawned process remains alive after cleanup', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'other_resource_categories_such_as_databases_queues_buckets_services_or_external_resources', 'statement': 'Other resource categories such as databases, queues, buckets, services, or external resources require configured command-backed observers in `Config.cleanup_observers`.', 'target': 'Other resource categories such as databases, queues, buckets, services, or external resources require configured command-backed observers in `Config.cleanup_obs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_cleanup_observer_must_define_resource_category_identity_fields_before_command_or_determi', 'statement': 'A cleanup observer must define resource category, identity fields, before command or deterministic capture method, after command or deterministic capture method, and comparison rule.', 'target': 'A cleanup observer must define resource category, identity fields, before command or deterministic capture method, after command or deterministic capture method', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'cleanup_applicability_is_determined_only_from_structured_resource_categories_fields_on_cle', 'statement': 'Cleanup applicability is determined only from structured `resource_categories` fields on CleanupEvidence, NotApplicableEvidence, EvidenceRecord cleanup records, failure/pass/runtime evidence records, and final claims', 'target': 'Cleanup applicability is determined only from structured `resource_categories` fields on CleanupEvidence, NotApplicableEvidence, EvidenceRecord cleanup records,', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'spec_guard_stores_them_as_structured_claims', 'statement': 'Spec Guard stores them as structured claims', 'target': 'Spec Guard stores them as structured claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'uses_exact_string_equality_for_cleanup_applicability', 'statement': 'uses exact string equality for cleanup applicability.', 'target': 'uses exact string equality for cleanup applicability', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'cleanup_evidence_must_provide_the_checked_resource_categories_explicitly_and_configured_ob', 'statement': 'Cleanup evidence must provide the checked `resource_categories` explicitly, and configured observers decide whether those categories are clean.', 'target': 'Cleanup evidence must provide the checked `resource_categories` explicitly, and configured observers decide whether those categories are clean', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'without_a_configured_observer_a_non_file_process_resource_category_can_be_marked_cleanup_n', 'statement': 'Without a configured observer, a non-file/process resource category can be marked cleanup not applicable only when no structured record lists that exact resource category string.', 'target': 'Without a configured observer, a non-file/process resource category can be marked cleanup not applicable only when no structured record lists that exact resourc', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'if_any_approved_or_deterministic_record_lists_the_category_and_no_observer_exists_cleanup', 'statement': 'If any approved or deterministic record lists the category and no observer exists, cleanup is blocked with diagnostics requiring observer configuration or human-approved scope change.', 'target': 'If any approved or deterministic record lists the category and no observer exists, cleanup is blocked with diagnostics requiring observer configuration or human', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'when_tests_or_failure_first_evidence_are_not_applicable_the_not_applicable_decision_is_rec', 'statement': 'When tests or failure-first evidence are not applicable, the not-applicable decision is recorded through `work.evidence.not_applicable`.', 'target': 'When tests or failure-first evidence are not applicable, the not-applicable decision is recorded through `work.evidence.not_applicable`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_must_identify_the_evidence_type_being_marked_not_applicable_the_reason_the_classificati', 'statement': 'It must identify the evidence type being marked not applicable, the reason, the classification/policy that permits it, and the approved ACs or scope it applies to.', 'target': 'It must identify the evidence type being marked not applicable, the reason, the classification/policy that permits it, and the approved ACs or scope it applies ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'evidence_type_tests_is_a_single_deterministic_not_applicable_record_that_covers_both_retai', 'statement': 'Evidence type `tests` is a single deterministic not-applicable record that covers both retained passing tests and failure-first test evidence', 'target': 'Evidence type `tests` is a single deterministic not-applicable record that covers both retained passing tests and failure-first test evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'otherwise_implementations_may_record_separate_test_failure_and_test_pass_not_applicable_re', 'statement': 'otherwise implementations may record separate `test_failure` and `test_pass` not-applicable records.', 'target': 'otherwise implementations may record separate `test_failure` and `test_pass` not-applicable records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'work_evidence_not_applicable_must_not_bypass_evidence_gates_by_assertion_alone', 'statement': '`work.evidence.not_applicable` must not bypass evidence gates by assertion alone.', 'target': '`work.evidence.not_applicable` must not bypass evidence gates by assertion alone', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'it_can_record_tests_or_failure_first_not_applicable_only_when_deterministic_eligibility_is', 'statement': 'It can record tests or failure-first not applicable only when deterministic eligibility is established by classification, approved docs/content policy, and the validation chain in this specification.', 'target': 'It can record tests or failure-first not applicable only when deterministic eligibility is established by classification, approved docs/content policy, and the ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_can_record_implementation_files_not_applicable_only_when_changed_file_classification_si', 'statement': 'It can record `implementation_files` not applicable only when changed-file classification since PacketChangeBaseline contains no `implementation_source` or `runtime_product_configuration` files and the packet classification/policy is documentation/content-only.', 'target': 'It can record `implementation_files` not applicable only when changed-file classification since PacketChangeBaseline contains no `implementation_source` or `run', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'human_confirmation_alone_must_not_make_tests_or_failure_first_evidence_not_applicable_for', 'statement': 'Human confirmation alone must not make tests or failure-first evidence not applicable for product/API/runtime behavior packets.', 'target': 'Human confirmation alone must not make tests or failure-first evidence not applicable for product/API/runtime behavior packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'human_confirmation_may_be_required_to_record_awareness_of_an_eligible_not_applicable_decis', 'statement': 'Human confirmation may be required to record awareness of an eligible not-applicable decision, but it cannot override deterministic ineligibility.', 'target': 'Human confirmation may be required to record awareness of an eligible not-applicable decision, but it cannot override deterministic ineligibility', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'review_completion_must_block_when_tests_leave_behind_unapproved_files_data_processes_exter', 'statement': 'Review completion must block when tests leave behind unapproved files, data, processes, external resources, or runtime state.', 'target': 'Review completion must block when tests leave behind unapproved files, data, processes, external resources, or runtime state', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'allowed_globs_apply_to_product_scope_changed_files', 'statement': 'Allowed globs apply to product-scope changed files:', 'target': 'Allowed globs apply to product-scope changed files:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'spec_guard_artifact_evidence_paths_are_exempt_from_allowed_globs_blocking_but_they_must_st', 'statement': 'Spec Guard artifact/evidence paths are exempt from allowed-globs blocking, but they must still be tracked and audited.', 'target': 'Spec Guard artifact/evidence paths are exempt from allowed-globs blocking, but they must still be tracked and audited', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'changes_through_symlinks_are_attributed_to_the_resolved_repository_relative_path_when_insi', 'statement': 'changes through symlinks are attributed to the resolved repository-relative path when inside the project, and rejected when they resolve outside the project.', 'target': 'changes through symlinks are attributed to the resolved repository-relative path when inside the project, and rejected when they resolve outside the project', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'case_sensitivity_follows_the_packet_change_baseline_mode_vcs_mode_uses_the_vcs_reported_pa', 'statement': 'Case sensitivity follows the packet change baseline mode: VCS mode uses the VCS-reported path identity', 'target': 'Case sensitivity follows the packet change baseline mode: VCS mode uses the VCS-reported path identity', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'manifest_mode_records_exact_path_strings_and_treats_them_as_case_sensitive', 'statement': 'manifest mode records exact path strings and treats them as case-sensitive.', 'target': 'manifest mode records exact path strings and treats them as case-sensitive', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'glob_matching_uses_separators_for_a_single_path_segment_fragment_for_zero_or_more_path_seg', 'statement': 'Glob matching uses `/` separators, `*` for a single path segment fragment, `**` for zero or more path segments, and `?` for one character within a segment.', 'target': 'Glob matching uses `/` separators, `*` for a single path segment fragment, `**` for zero or more path segments, and `?` for one character within a segment', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'negated_globs_are_not_supported_unless_a_future_schema_explicitly_adds_them', 'statement': 'Negated globs are not supported unless a future schema explicitly adds them.', 'target': 'Negated globs are not supported unless a future schema explicitly adds them', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'must_not_be_absolute_or_contain_after_normalization', 'statement': 'must not be absolute or contain `..` after normalization.', 'target': 'must not be absolute or contain `..` after normalization', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'other_unexpected_files_are_never_silently_allowed', 'statement': 'Other/unexpected files are never silently allowed.', 'target': 'Other/unexpected files are never silently allowed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'they_require_diagnostics_and_explicit_resolution', 'statement': 'They require diagnostics and explicit resolution.', 'target': 'They require diagnostics and explicit resolution', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'deterministic_checks_must_validate', 'statement': 'Deterministic checks must validate:', 'target': 'Deterministic checks must validate:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_were_recorded_before_behavior_tests_that_claim_to_validate_the_documented_contract', 'statement': 'docs were recorded before behavior tests that claim to validate the documented contract,', 'target': 'docs were recorded before behavior tests that claim to validate the documented contract', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'retained_tests_do_not_test_documentation_files_or_documentation_text', 'statement': 'retained tests do not test documentation files or documentation text,', 'target': 'retained tests do not test documentation files or documentation text', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'command_result_is_recorded', 'statement': 'command result is recorded,', 'target': 'command result is recorded', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'product_scope_changed_files_are_within_allowed_globs', 'statement': 'product-scope changed files are within allowed globs.', 'target': 'product-scope changed files are within allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'required_backend_verification_for_the_full_api_contract_surface_chain_must_pass_for', 'statement': 'Required backend verification for the full API/contract-surface chain must pass for:', 'target': 'Required backend verification for the full API/contract-surface chain must pass for:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_updated_semantic_claim_when_docs_are_added_changed_or_required_by_policy', 'statement': 'docs-updated semantic claim when docs are added, changed, or required by policy,', 'target': 'docs-updated semantic claim when docs are added, changed, or required by policy', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'failure_evidence_semantic_claim_when_the_failure_is_used_to_prove_missing_approved_behavio', 'statement': 'failure evidence semantic claim when the failure is used to prove missing approved behavior.', 'target': 'failure evidence semantic claim when the failure is used to prove missing approved behavior', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_pre_implementation_validation_docs_existence_docs_to_ac_mapping_behavior_test_mapping', 'statement': 'For pre-implementation validation, docs existence, docs-to-AC mapping, behavior-test mapping, and failure-evidence requirements above must already be satisfied, but `docs_updated` follows section 12.8 and may remain pending until review completion.', 'target': 'For pre-implementation validation, docs existence, docs-to-AC mapping, behavior-test mapping, and failure-evidence requirements above must already be satisfied,', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_non_api_packets_with_docs_policy_required', 'statement': 'For non-API packets with docs policy `required`:', 'target': 'For non-API packets with docs policy `required`:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_non_api_packets_without_required_docs', 'statement': 'For non-API packets without required docs:', 'target': 'For non-API packets without required docs:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_docs_exist_when_docs_policy_is_required', 'statement': 'required docs exist when docs policy is `required`,', 'target': 'required docs exist when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_docs_are_linked_to_approved_acceptance_item_refs_when_docs_policy_is_required', 'statement': 'required docs are linked to approved AC IDs when docs policy is `required`,', 'target': 'required docs are linked to approved AC IDs when docs policy is `required`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_docs_were_recorded_before_behavior_tests_that_claim_to_validate_the_documented_co', 'statement': 'required docs were recorded before behavior tests that claim to validate the documented contract,', 'target': 'required docs were recorded before behavior tests that claim to validate the documented contract', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_backend_verification_for_the_full_non_api_chain_must_pass_for', 'statement': 'Required backend verification for the full non-API chain must pass for:', 'target': 'Required backend verification for the full non-API chain must pass for:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_to_ac_mapping_when_docs_policy_is_required', 'statement': 'docs-to-AC mapping when docs policy is `required`,', 'target': 'docs-to-AC mapping when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_updated_semantic_claim_when_docs_policy_is_required_docs_policy_is_changed_docs_polic', 'statement': 'docs-updated semantic claim when docs policy is `required`, docs policy is `changed`, docs policy changed during the packet lifecycle, or docs files changed,', 'target': 'docs-updated semantic claim when docs policy is `required`, docs policy is `changed`, docs policy changed during the packet lifecycle, or docs files changed', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'behavior_tests_to_documented_contract_mapping_when_docs_policy_is_required', 'statement': 'behavior-tests-to-documented-contract mapping when docs policy is `required`,', 'target': 'behavior-tests-to-documented-contract mapping when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_pre_implementation_validation_docs_existence_docs_to_ac_mapping_when_required_behavior', 'statement': 'For pre-implementation validation, docs existence, docs-to-AC mapping when required, behavior-test mapping when required, tests-to-AC mapping, and failure-evidence requirements above must already be satisfied, but `docs_updated` follows section 12.8 and may remain pending until review completion.', 'target': 'For pre-implementation validation, docs existence, docs-to-AC mapping when required, behavior-test mapping when required, tests-to-AC mapping, and failure-evide', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'test_failure_first_not_applicable_reason_is_recorded', 'statement': 'test/failure-first not-applicable reason is recorded,', 'target': 'test/failure-first not-applicable reason is recorded', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'no_retained_tests_were_added_for_documentation_text_files', 'statement': 'no retained tests were added for documentation text/files,', 'target': 'no retained tests were added for documentation text/files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'required_backend_verification_must_pass_for', 'statement': 'Required backend verification must pass for:', 'target': 'Required backend verification must pass for:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_updated_semantic_claim', 'statement': 'docs-updated semantic claim.', 'target': 'docs-updated semantic claim', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'if_an_operational_document_packet_changes_product_behavior_runtime_behavior_api_behavior_s', 'statement': 'If an operational-document packet changes product behavior, runtime behavior, API behavior, schema, persistence, or shipped application code, this documentation-only chain is invalid.', 'target': 'If an operational-document packet changes product behavior, runtime behavior, API behavior, schema, persistence, or shipped application code, this documentation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'spec_guard_must_require_a_registered_docs_updated_claim_and_passed_backend_verification_be', 'statement': 'Spec Guard must require a registered `docs_updated` claim and passed backend verification before review completion when any of these conditions are true:', 'target': 'Spec Guard must require a registered `docs_updated` claim and passed backend verification before review completion when any of these conditions are true:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_policy_is_required', 'statement': 'docs policy is `required`,', 'target': 'docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_evidence_was_added_or_updated', 'statement': 'docs evidence was added or updated.', 'target': 'docs evidence was added or updated', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_docs_policy_required_pre_implementation_validation_must_also_require_docs_existence_do', 'statement': 'For docs policy `required`, pre-implementation validation must also require docs existence, docs-to-AC traceability, and any required docs-to-AC backend verification before implementation source changes.', 'target': 'For docs policy `required`, pre-implementation validation must also require docs existence, docs-to-AC traceability, and any required docs-to-AC backend verific', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_docs_updated_claim_may_pass_at_pre_implementation_time_or_later_but_review_completion', 'statement': 'The `docs_updated` claim may pass at pre-implementation time or later, but review completion must block until it passes.', 'target': 'The `docs_updated` claim may pass at pre-implementation time or later, but review completion must block until it passes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'for_docs_policy_changed_docs_evidence_identifying_the_updated_docs_content_paths_must_exis', 'statement': 'For docs policy `changed`, docs evidence identifying the updated docs/content paths must exist before review completion.', 'target': 'For docs policy `changed`, docs evidence identifying the updated docs/content paths must exist before review completion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_docs_do_not_need_to_precede_tests_unless_another_rule_requires_that_ordering_but_the_d', 'statement': 'The docs do not need to precede tests unless another rule requires that ordering, but the `docs_updated` claim must pass before review completion.', 'target': 'The docs do not need to precede tests unless another rule requires that ordering, but the `docs_updated` claim must pass before review completion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_spec_guard_artifacts_evidence', 'statement': 'Enumerated item is supported/enforced: Spec Guard artifacts/evidence,', 'target': 'Spec Guard artifacts/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_docs', 'statement': 'Enumerated item is supported/enforced: required docs,', 'target': 'required docs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests_intended_to_fail_against_missing_approved_beha', 'statement': 'Enumerated item is supported/enforced: tests intended to fail against missing approved behavior.', 'target': 'tests intended to fail against missing approved behavior', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs', 'statement': 'Enumerated item is supported/enforced: docs,', 'target': 'docs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests', 'statement': 'Enumerated item is supported/enforced: tests,', 'target': 'tests', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_source', 'statement': 'Enumerated item is supported/enforced: implementation source,', 'target': 'implementation source', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_product_configuration', 'statement': 'Enumerated item is supported/enforced: runtime/product configuration,', 'target': 'runtime/product configuration', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_generated_build_output_when_tracked_or_submitted_as', 'statement': 'Enumerated item is supported/enforced: generated build output when tracked or submitted as evidence.', 'target': 'generated build output when tracked or submitted as evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_paths_are_normalized_to_repository_relative_posix_st', 'statement': 'Enumerated item is supported/enforced: Paths are normalized to repository-relative POSIX-style paths using `/` separators.', 'target': 'Paths are normalized to repository-relative POSIX-style paths using `/` separators', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_absolute_paths_and_paths_containing_after_normalizat', 'statement': 'Enumerated item is supported/enforced: Absolute paths and paths containing `..` after normalization are invalid as governed paths.', 'target': 'Absolute paths and paths containing `..` after normalization are invalid as governed paths', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_symlink_paths_are_resolved_for_classification_change', 'statement': 'Enumerated item is supported/enforced: Symlink paths are resolved for classification; changes through symlinks are attributed to the resolved repository-relative path when inside the project, and rejected when they resolve outside the project.', 'target': 'Symlink paths are resolved for classification; changes through symlinks are attributed to the resolved repository-relative path when inside the project, and rej', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_case_sensitivity_follows_the_packet_change_baseline', 'statement': 'Enumerated item is supported/enforced: Case sensitivity follows the packet change baseline mode: VCS mode uses the VCS-reported path identity; manifest mode records exact path strings and treats them as case-sensitive.', 'target': 'Case sensitivity follows the packet change baseline mode: VCS mode uses the VCS-reported path identity; manifest mode records exact path strings and treats them', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_glob_matching_uses_separators_for_a_single_path_segm', 'statement': 'Enumerated item is supported/enforced: Glob matching uses `/` separators, `*` for a single path segment fragment, `**` for zero or more path segments, and `?` for one character within a segment.', 'target': 'Glob matching uses `/` separators, `*` for a single path segment fragment, `**` for zero or more path segments, and `?` for one character within a segment', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_negated_globs_are_not_supported_unless_a_future_sche', 'statement': 'Enumerated item is supported/enforced: Negated globs are not supported unless a future schema explicitly adds them.', 'target': 'Negated globs are not supported unless a future schema explicitly adds them', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_glob_patterns_are_repository_relative_and_must_not_b', 'statement': 'Enumerated item is supported/enforced: Glob patterns are repository-relative and must not be absolute or contain `..` after normalization.', 'target': 'Glob patterns are repository-relative and must not be absolute or contain `..` after normalization', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_approval_exists', 'statement': 'Enumerated item is supported/enforced: AC approval exists,', 'target': 'AC approval exists', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_exist_and_are_linked_to_approved_acceptance_item_refs', 'statement': 'Enumerated item is supported/enforced: docs exist and are linked to approved AC IDs,', 'target': 'docs exist and are linked to approved AC IDs', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_were_recorded_before_behavior_tests_that_claim', 'statement': 'Enumerated item is supported/enforced: docs were recorded before behavior tests that claim to validate the documented contract,', 'target': 'docs were recorded before behavior tests that claim to validate the documented contract', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests_exist_and_are_real_test_paths', 'statement': 'Enumerated item is supported/enforced: tests exist and are real test paths,', 'target': 'tests exist and are real test paths', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_retained_tests_do_not_test_documentation_files_or_do', 'statement': 'Enumerated item is supported/enforced: retained tests do not test documentation files or documentation text,', 'target': 'retained tests do not test documentation files or documentation text', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failure_evidence_exists', 'statement': 'Enumerated item is supported/enforced: failure evidence exists,', 'target': 'failure evidence exists', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command_result_is_recorded', 'statement': 'Enumerated item is supported/enforced: command result is recorded,', 'target': 'command result is recorded', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_source_did_not_change_before_failure', 'statement': 'Enumerated item is supported/enforced: implementation source did not change before failure-first evidence,', 'target': 'implementation source did not change before failure-first evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_product_scope_changed_files_are_within_allowed_globs', 'statement': 'Enumerated item is supported/enforced: product-scope changed files are within allowed globs.', 'target': 'product-scope changed files are within allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_to_ac_mapping', 'statement': 'Enumerated item is supported/enforced: docs-to-AC mapping,', 'target': 'docs-to-AC mapping', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_updated_semantic_claim_when_docs_are_added_chan', 'statement': 'Enumerated item is supported/enforced: docs-updated semantic claim when docs are added, changed, or required by policy,', 'target': 'docs-updated semantic claim when docs are added, changed, or required by policy', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_behavior_tests_to_documented_contract_mapping', 'statement': 'Enumerated item is supported/enforced: behavior-tests-to-documented-contract mapping,', 'target': 'behavior-tests-to-documented-contract mapping', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failure_evidence_semantic_claim_when_the_failure_is', 'statement': 'Enumerated item is supported/enforced: failure evidence semantic claim when the failure is used to prove missing approved behavior.', 'target': 'failure evidence semantic claim when the failure is used to prove missing approved behavior', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_docs_exist_when_docs_policy_is_required', 'statement': 'Enumerated item is supported/enforced: required docs exist when docs policy is `required`,', 'target': 'required docs exist when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_docs_are_linked_to_approved_acceptance_item_refs_when_doc', 'statement': 'Enumerated item is supported/enforced: required docs are linked to approved AC IDs when docs policy is `required`,', 'target': 'required docs are linked to approved AC IDs when docs policy is `required`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_docs_were_recorded_before_behavior_tests_th', 'statement': 'Enumerated item is supported/enforced: required docs were recorded before behavior tests that claim to validate the documented contract,', 'target': 'required docs were recorded before behavior tests that claim to validate the documented contract', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_to_ac_mapping_when_docs_policy_is_required', 'statement': 'Enumerated item is supported/enforced: docs-to-AC mapping when docs policy is `required`,', 'target': 'docs-to-AC mapping when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_updated_semantic_claim_when_docs_policy_is_requ', 'statement': 'Enumerated item is supported/enforced: docs-updated semantic claim when docs policy is `required`, docs policy is `changed`, docs policy changed during the packet lifecycle, or docs files changed,', 'target': 'docs-updated semantic claim when docs policy is `required`, docs policy is `changed`, docs policy changed during the packet lifecycle, or docs files changed', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_behavior_tests_to_documented_contract_mapping_when_d', 'statement': 'Enumerated item is supported/enforced: behavior-tests-to-documented-contract mapping when docs policy is `required`,', 'target': 'behavior-tests-to-documented-contract mapping when docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests_to_ac_mapping', 'statement': 'Enumerated item is supported/enforced: tests-to-AC mapping,', 'target': 'tests-to-AC mapping', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_content_paths_are_inside_project', 'statement': 'Enumerated item is supported/enforced: docs/content paths are inside project,', 'target': 'docs/content paths are inside project', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_content_files_exist', 'statement': 'Enumerated item is supported/enforced: docs/content files exist,', 'target': 'docs/content files exist', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_changed_files_are_limited_to_approved_docs_content_p', 'statement': 'Enumerated item is supported/enforced: changed files are limited to approved docs/content paths and Spec Guard artifacts/evidence,', 'target': 'changed files are limited to approved docs/content paths and Spec Guard artifacts/evidence', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_test_failure_first_not_applicable_reason_is_recorded', 'statement': 'Enumerated item is supported/enforced: test/failure-first not-applicable reason is recorded,', 'target': 'test/failure-first not-applicable reason is recorded', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_retained_tests_were_added_for_documentation_text', 'statement': 'Enumerated item is supported/enforced: no retained tests were added for documentation text/files,', 'target': 'no retained tests were added for documentation text/files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_no_implementation_source_changed', 'statement': 'Enumerated item is supported/enforced: no implementation source changed.', 'target': 'no implementation source changed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_content_to_ac_mapping', 'statement': 'Enumerated item is supported/enforced: docs/content-to-AC mapping,', 'target': 'docs/content-to-AC mapping', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_updated_semantic_claim', 'statement': 'Enumerated item is supported/enforced: docs-updated semantic claim.', 'target': 'docs-updated semantic claim', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy_is_required', 'statement': 'Enumerated item is supported/enforced: docs policy is `required`,', 'target': 'docs policy is `required`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy_is_changed', 'statement': 'Enumerated item is supported/enforced: docs policy is `changed`,', 'target': 'docs policy is `changed`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy_changed_after_work_packet_approval', 'statement': 'Enumerated item is supported/enforced: docs policy changed after Work Packet approval,', 'target': 'docs policy changed after Work Packet approval', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_content_files_changed_in_the_packet_diff', 'statement': 'Enumerated item is supported/enforced: docs/content files changed in the packet diff,', 'target': 'docs/content files changed in the packet diff', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_evidence_was_added_or_updated', 'statement': 'Enumerated item is supported/enforced: docs evidence was added or updated.', 'target': 'docs evidence was added or updated', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'table_row_is_implemented_evidence_action_type_work_evidence_failure_with_failure_first_rol', 'statement': 'Table row is implemented: Evidence action/type: `work.evidence.failure` with failure-first role; Allowed CommandResult purpose: `test`', 'target': 'Evidence action/type: `work.evidence.failure` with failure-first role; Allowed CommandResult purpose: `test`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_evidence_action_type_work_evidence_pass_with_passing_test_role_al', 'statement': 'Table row is implemented: Evidence action/type: `work.evidence.pass` with passing-test role; Allowed CommandResult purpose: `test`', 'target': 'Evidence action/type: `work.evidence.pass` with passing-test role; Allowed CommandResult purpose: `test`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_evidence_action_type_work_evidence_runtime_production_allowed_com', 'statement': 'Table row is implemented: Evidence action/type: `work.evidence.runtime` production; Allowed CommandResult purpose: `runtime_production`', 'target': 'Evidence action/type: `work.evidence.runtime` production; Allowed CommandResult purpose: `runtime_production`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_evidence_action_type_work_evidence_runtime_development_allowed_co', 'statement': 'Table row is implemented: Evidence action/type: `work.evidence.runtime` development; Allowed CommandResult purpose: `runtime_development`', 'target': 'Evidence action/type: `work.evidence.runtime` development; Allowed CommandResult purpose: `runtime_development`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'table_row_is_implemented_evidence_action_type_runtime_baseline_validation_evidence_allowed', 'statement': 'Table row is implemented: Evidence action/type: Runtime baseline validation evidence; Allowed CommandResult purpose: `test`, `build`, `runtime_production`, `runtime_development` as applicable', 'target': 'Evidence action/type: Runtime baseline validation evidence; Allowed CommandResult purpose: `test`, `build`, `runtime_production`, `runtime_development` as appli', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
