"""Executable specification for US-17: Viewer requirements."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'the_viewer_must_be_a_real_web_application_for_artifact_review_and_governance_insight', 'statement': 'The viewer must be a real web application for artifact review and governance insight.', 'target': 'The viewer must be a real web application for artifact review and governance insight', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_viewer_must_use_mantine_for_styling_layout_and_interaction_states', 'statement': 'The viewer must use Mantine for styling, layout, and interaction states.', 'target': 'The viewer must use Mantine for styling, layout, and interaction states', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_primary_dashboard_and_review_pages_must_be_built_from_mantine_components_or_project_lo', 'statement': 'The primary dashboard and review pages must be built from Mantine components or project-local wrappers around Mantine components, including dashboard shell/layout, metric cards, badges, tables/lists, buttons/links, and status colors.', 'target': 'The primary dashboard and review pages must be built from Mantine components or project-local wrappers around Mantine components, including dashboard shell/layo', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_viewer_must_not_be_an_unstyled_plain_html_surface', 'statement': 'The viewer must not be an unstyled/plain HTML surface.', 'target': 'The viewer must not be an unstyled/plain HTML surface', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_viewer_must_be_modeled_after_industry_standard_dashboard_patterns_an_overview_first_da', 'statement': 'The viewer must be modeled after industry-standard dashboard patterns: an overview-first dashboard, a responsive metric-card grid, clear hierarchy, scannable labels and numbers, consistent spacing and typography, status badges, action-oriented visual emphasis, and drill-down navigation from summary metrics to the underlying records.', 'target': 'The viewer must be modeled after industry-standard dashboard patterns: an overview-first dashboard, a responsive metric-card grid, clear hierarchy, scannable la', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_create_an_actual_http_server_bound_to_the_requested_host_and_port_serve_viewer_rou', 'statement': 'It must create an actual HTTP server bound to the requested host and port, serve viewer routes over HTTP,', 'target': 'It must create an actual HTTP server bound to the requested host and port, serve viewer routes over HTTP', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'keep_the_cli_process_alive_until_the_server_is_explicitly_closed_or_the_process_receives_a', 'statement': 'keep the CLI process alive until the server is explicitly closed or the process receives a termination signal such as Ctrl-C/SIGINT/SIGTERM.', 'target': 'keep the CLI process alive until the server is explicitly closed or the process receives a termination signal such as Ctrl-C/SIGINT/SIGTERM', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_must_not_print_viewer_running_at_unless_the_server_is_listening_successfully', 'statement': 'It must not print `Viewer running at ...` unless the server is listening successfully.', 'target': 'It must not print `Viewer running at ...` unless the server is listening successfully', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'if_binding_fails_it_must_return_or_print_diagnostics_and_exit_non_zero', 'statement': 'If binding fails, it must return or print diagnostics and exit non-zero.', 'target': 'If binding fails, it must return or print diagnostics and exit non-zero', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implementations_may_return_a_server_handle_from_the_internal_viewer_serve_api_but_the_cli', 'statement': 'Implementations may return a server handle from the internal `viewer.serve()` API, but the CLI command must await or otherwise retain that handle so the process does not exit immediately.', 'target': 'Implementations may return a server handle from the internal `viewer.serve()` API, but the CLI command must await or otherwise retain that handle so the process', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_viewer_must_read_through_the_same_shared_core_artifact_store_used_by_cli_mcp_and_pi', 'statement': 'The viewer must read through the same shared core/artifact store used by CLI, MCP, and Pi.', 'target': 'The viewer must read through the same shared core/artifact store used by CLI, MCP, and Pi', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'viewer_data_must_be_derived_from_persisted_spec_guard_artifacts_under_the_configured_artif', 'statement': 'Viewer data must be derived from persisted Spec Guard artifacts under the configured artifact root, not from viewer-only fixtures, hard-coded empty objects, generated labels, or fake in-memory state except in explicitly isolated unit tests.', 'target': 'Viewer data must be derived from persisted Spec Guard artifacts under the configured artifact root, not from viewer-only fixtures, hard-coded empty objects, gen', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'after_a_workflow_action_persists_or_mutates_an_artifact_refreshing_the_viewer_or_calling_t', 'statement': 'After a workflow action persists or mutates an artifact, refreshing the viewer or calling the viewer summary action must reflect the persisted state.', 'target': 'After a workflow action persists or mutates an artifact, refreshing the viewer or calling the viewer summary action must reflect the persisted state', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_dashboard_must_show_persisted_artifact_derived_metric_cards_for', 'statement': 'The dashboard must show persisted artifact-derived metric cards for:', 'target': 'The dashboard must show persisted artifact-derived metric cards for:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'blocked_packets', 'statement': 'blocked packets,', 'target': 'blocked packets', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'final_claim_support_status', 'statement': 'final claim support status.', 'target': 'final claim support status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'each_dashboard_metric_card_that_displays_a_count_must_be_clickable', 'statement': 'Each dashboard metric card that displays a count must be clickable.', 'target': 'Each dashboard metric card that displays a count must be clickable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'activating_a_card_must_open_or_navigate_to_a_filtered_list_of_the_exact_artifacts_represen', 'statement': 'Activating a card must open or navigate to a filtered list of the exact artifacts represented by that count.', 'target': 'Activating a card must open or navigate to a filtered list of the exact artifacts represented by that count', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_filtered_list_must_show_artifact_identifiers_artifact_type_lifecycle_status_pending_ac', 'statement': 'The filtered list must show artifact identifiers, artifact type, lifecycle/status, pending action if any, last updated/revision where available, and a link to the artifact detail/review page.', 'target': 'The filtered list must show artifact identifiers, artifact type, lifecycle/status, pending action if any, last updated/revision where available, and a link to t', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_number_of_rows_in_the_filtered_list_must_reconcile_with_the_clicked_card_count_subject', 'statement': 'The number of rows in the filtered list must reconcile with the clicked card count, subject only to explicit pagination with a visible total count.', 'target': 'The number of rows in the filtered list must reconcile with the clicked card count, subject only to explicit pagination with a visible total count', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'metric_cards_for_artifacts_or_states_requiring_user_action_including_pending_human_gates_b', 'statement': 'Metric cards for artifacts or states requiring user action, including pending human gates, blocked packets, stale approvals, verifier failures, validation failures, missing evidence, or review-ready items, must be visually distinct from passive informational cards.', 'target': 'Metric cards for artifacts or states requiring user action, including pending human gates, blocked packets, stale approvals, verifier failures, validation failu', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_distinction_must_use_mantine_supported_styling_such_as_color_variant_icon_badge_border', 'statement': 'The distinction must use Mantine-supported styling such as color, variant, icon, badge, border, or callout treatment,', 'target': 'The distinction must use Mantine-supported styling such as color, variant, icon, badge, border, or callout treatment', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'must_remain_visible_without_relying_on_color_alone', 'statement': 'must remain visible without relying on color alone.', 'target': 'must remain visible without relying on color alone', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_dashboard_summary_data_used_by_the_viewer_must_also_be_available_through_a_shared_core', 'statement': 'The dashboard summary data used by the viewer must also be available through a shared-core read path suitable for tests and agents.', 'target': 'The dashboard summary data used by the viewer must also be available through a shared-core read path suitable for tests and agents', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'config_check_must_return_more_than_artifact_root_ok_it_must_include_a_persisted_artifact_g', 'statement': '`config.check` must return more than `{ artifact_root, ok }`: it must include a persisted-artifact governance summary with at least total artifacts, artifact counts by type/status, lifecycle distribution, workflow-stage distribution, pending gates, blocked packets, baseline status, verifier health, validation failures, runtime evidence status, and final claim support status.', 'target': '`config.check` must return more than `{ artifact_root, ok }`: it must include a persisted-artifact governance summary with at least total artifacts, artifact co', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'these_fields_must_be_computed_from_real_persisted_artifacts', 'statement': 'These fields must be computed from real persisted artifacts.', 'target': 'These fields must be computed from real persisted artifacts', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'for_example_after_work_intake_creates_a_draft_work_packet_config_check_and_the_viewer_dash', 'statement': 'For example, after `work.intake` creates a draft Work Packet, `config.check` and the viewer dashboard must report the Work Packet in total artifacts, artifact counts, and lifecycle/workflow-stage distribution without requiring a fake viewer core.', 'target': 'For example, after `work.intake` creates a draft Work Packet, `config.check` and the viewer dashboard must report the Work Packet in total artifacts, artifact c', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'artifacts_awaiting_human_gates_must_have_human_readable_review_pages', 'statement': 'Artifacts awaiting human gates must have human-readable review pages.', 'target': 'Artifacts awaiting human gates must have human-readable review pages', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'formatted_json_must_not_be_the_primary_review_surface', 'statement': 'Formatted JSON must not be the primary review surface.', 'target': 'Formatted JSON must not be the primary review surface', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'work_packet_pages_must_show', 'statement': 'Work Packet pages must show:', 'target': 'Work Packet pages must show:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'allowed_globs', 'statement': 'allowed globs,', 'target': 'allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'plan_pages_must_show', 'statement': 'Plan pages must show:', 'target': 'Plan pages must show:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'approval_must_bind_to_the_hash_shown_in_the_viewer', 'statement': 'Approval must bind to the hash shown in the viewer.', 'target': 'Approval must bind to the hash shown in the viewer', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_viewer_must_clearly_distinguish', 'statement': 'The viewer must clearly distinguish:', 'target': 'The viewer must clearly distinguish:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_total_artifacts', 'statement': 'Enumerated item is supported/enforced: total artifacts,', 'target': 'total artifacts', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_total_artifacts_by_artifact_type', 'statement': 'Enumerated item is supported/enforced: total artifacts by artifact type,', 'target': 'total artifacts by artifact type', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_artifact_counts_by_type_status', 'statement': 'Enumerated item is supported/enforced: artifact counts by type/status,', 'target': 'artifact counts by type/status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_the_number_of_artifacts_in_each_workflow_lifecycle_s', 'statement': 'Enumerated item is supported/enforced: the number of artifacts in each workflow/lifecycle stage,', 'target': 'the number of artifacts in each workflow/lifecycle stage', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pending_human_gates', 'statement': 'Enumerated item is supported/enforced: pending human gates,', 'target': 'pending human gates', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_blocked_packets', 'statement': 'Enumerated item is supported/enforced: blocked packets,', 'target': 'blocked packets', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_status', 'statement': 'Enumerated item is supported/enforced: runtime baseline status,', 'target': 'runtime baseline status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_health', 'statement': 'Enumerated item is supported/enforced: verifier health,', 'target': 'verifier health', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_validation_failures', 'statement': 'Enumerated item is supported/enforced: validation failures,', 'target': 'validation failures', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_evidence_status', 'statement': 'Enumerated item is supported/enforced: runtime evidence status,', 'target': 'runtime evidence status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_final_claim_support_status', 'statement': 'Enumerated item is supported/enforced: final claim support status.', 'target': 'final claim support status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_status_and_lifecycle', 'statement': 'Enumerated item is supported/enforced: status and lifecycle,', 'target': 'status and lifecycle', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_goal_and_intent_fields', 'statement': 'Enumerated item is supported/enforced: goal and intent fields,', 'target': 'goal and intent fields', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acs_with_source_evidence_markers', 'statement': 'Enumerated item is supported/enforced: ACs with source/evidence markers,', 'target': 'ACs with source/evidence markers', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_approval_state', 'statement': 'Enumerated item is supported/enforced: AC approval state,', 'target': 'AC approval state', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_platform_choice', 'statement': 'Enumerated item is supported/enforced: platform choice,', 'target': 'platform choice', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_architecture_decisions', 'statement': 'Enumerated item is supported/enforced: architecture decisions,', 'target': 'architecture decisions', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_classification_and_docs_policy', 'statement': 'Enumerated item is supported/enforced: classification and docs policy,', 'target': 'classification and docs policy', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_globs', 'statement': 'Enumerated item is supported/enforced: allowed globs,', 'target': 'allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline', 'statement': 'Enumerated item is supported/enforced: packet change baseline,', 'target': 'packet change baseline', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_requirements', 'statement': 'Enumerated item is supported/enforced: docs requirements,', 'target': 'docs requirements', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_backend_verification_status_findings', 'statement': 'Enumerated item is supported/enforced: backend verification status/findings,', 'target': 'backend verification status/findings', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pre_implementation_validation_status', 'statement': 'Enumerated item is supported/enforced: pre-implementation validation status,', 'target': 'pre-implementation validation status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failure_pass_runtime_evidence', 'statement': 'Enumerated item is supported/enforced: failure/pass/runtime evidence,', 'target': 'failure/pass/runtime evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_test_files', 'statement': 'Enumerated item is supported/enforced: implementation/test files,', 'target': 'implementation/test files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_changed_files', 'statement': 'Enumerated item is supported/enforced: changed files,', 'target': 'changed files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_final_claim_validation', 'statement': 'Enumerated item is supported/enforced: final claim validation,', 'target': 'final claim validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_diagnostics', 'statement': 'Enumerated item is supported/enforced: diagnostics,', 'target': 'diagnostics', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_next_human_decision', 'statement': 'Enumerated item is supported/enforced: next human decision,', 'target': 'next human decision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_snapshot_hash', 'statement': 'Enumerated item is supported/enforced: review snapshot hash.', 'target': 'review snapshot hash', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_status', 'statement': 'Enumerated item is supported/enforced: Plan status,', 'target': 'Plan status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approved_plan_proposal', 'statement': 'Enumerated item is supported/enforced: approved Plan proposal,', 'target': 'approved Plan proposal', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_child_creation_status', 'statement': 'Enumerated item is supported/enforced: child creation status,', 'target': 'child creation status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_review_snapshot_when_pending', 'statement': 'Enumerated item is supported/enforced: batch review snapshot when pending,', 'target': 'batch review snapshot when pending', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_per_child_readiness', 'statement': 'Enumerated item is supported/enforced: per-child readiness,', 'target': 'per-child readiness', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_per_child_approval_authorization_binding', 'statement': 'Enumerated item is supported/enforced: per-child approval/authorization binding.', 'target': 'per-child approval/authorization binding', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_human_approved_intent', 'statement': 'Enumerated item is supported/enforced: human-approved intent,', 'target': 'human-approved intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_frontend_agent_proposals', 'statement': 'Enumerated item is supported/enforced: frontend-agent proposals,', 'target': 'frontend-agent proposals', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_backend_verified_claims', 'statement': 'Enumerated item is supported/enforced: backend-verified claims,', 'target': 'backend-verified claims', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_deterministic_evidence', 'statement': 'Enumerated item is supported/enforced: deterministic evidence.', 'target': 'deterministic evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
