"""Executable specification for US-16: Agent harness configuration."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'spec_guard_init_must_generate_best_effort_agent_and_mcp_configuration_files_in_the_project', 'statement': '`spec-guard init` must generate best-effort agent and MCP configuration files in the project, not only in an internal artifact directory.', 'target': '`spec-guard init` must generate best-effort agent and MCP configuration files in the project, not only in an internal artifact directory', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_generated_files_must_make_mcp_pi_use_obvious_to_agents_and_humans_immediately_after_np', 'statement': 'The generated files must make MCP/Pi use obvious to agents and humans immediately after `npx spec-guard init`.', 'target': 'The generated files must make MCP/Pi use obvious to agents and humans immediately after `npx spec-guard init`', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_generated_support_artifacts', 'statement': 'Required generated/support artifacts:', 'target': 'Required generated/support artifacts:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'vs_code_config_at_vscode_mcp_json_where_supported', 'statement': 'VS Code config at `.vscode/mcp.json` where supported,', 'target': 'VS Code config at `.vscode/mcp.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'cline_config_at_cline_mcp_json_and_cline_cline_mcp_settings_json_where_supported', 'statement': 'Cline config at `.cline/mcp.json` and `.cline/cline_mcp_settings.json` where supported,', 'target': 'Cline config at `.cline/mcp.json` and `.cline/cline_mcp_settings.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'roo_config_at_roo_mcp_json_and_roo_roo_mcp_settings_json_where_supported', 'statement': 'Roo config at `.roo/mcp.json` and `.roo/roo_mcp_settings.json` where supported,', 'target': 'Roo config at `.roo/mcp.json` and `.roo/roo_mcp_settings.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'windsurf_config_at_windsurf_mcp_json_and_windsurf_mcp_config_json_where_supported', 'statement': 'Windsurf config at `.windsurf/mcp.json` and `.windsurf/mcp_config.json` where supported,', 'target': 'Windsurf config at `.windsurf/mcp.json` and `.windsurf/mcp_config.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'generic_stdio_snippets_for_other_mcp_clients_where_supported', 'statement': 'generic stdio snippets for other MCP clients where supported,', 'target': 'generic stdio snippets for other MCP clients where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'client_support_matrix', 'statement': 'client support matrix.', 'target': 'client support matrix', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_project_local_pi_extension_is_required', 'statement': 'The project-local Pi extension is required.', 'target': 'The project-local Pi extension is required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_be_placed_at_pi_extensions_spec_guard_ts_so_pi_auto_discovers_it_on_startup_or_rel', 'statement': 'It must be placed at `.pi/extensions/spec-guard.ts` so Pi auto-discovers it on startup or `/reload`.', 'target': 'It must be placed at `.pi/extensions/spec-guard.ts` so Pi auto-discovers it on startup or `/reload`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_register_direct_spec_guard_tools_for_the_shared_workflow_actions', 'statement': 'It must register direct `spec_guard_*` tools for the shared workflow actions', 'target': 'It must register direct `spec_guard_*` tools for the shared workflow actions', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'must_call_the_shared_core_action_registry_directly_rather_than_shelling_out_to_cli', 'statement': 'must call the shared core/action registry directly rather than shelling out to CLI.', 'target': 'must call the shared core/action registry directly rather than shelling out to CLI', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'its_tool_descriptions_or_prompt_guidelines_must_direct_agents_to_use_spec_guard_tools_dire', 'statement': 'Its tool descriptions or prompt guidelines must direct agents to use Spec Guard tools directly, call status/quickstart first, and provide actual human confirmation fields for human-gated actions.', 'target': 'Its tool descriptions or prompt guidelines must direct agents to use Spec Guard tools directly, call status/quickstart first, and provide actual human confirmat', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_generated_pi_extension_must_satisfy_pi_s_actual_extension_module_contract', 'statement': "The generated Pi extension must satisfy Pi's actual extension module contract.", 'target': "The generated Pi extension must satisfy Pi's actual extension module contract", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_must_default_export_a_synchronous_or_asynchronous_factory_function_accepting_pi_s_exten', 'statement': "It must default-export a synchronous or asynchronous factory function accepting Pi's `ExtensionAPI` object, for example `export default function (pi: ExtensionAPI) { ...", 'target': "It must default-export a synchronous or asynchronous factory function accepting Pi's `ExtensionAPI` object, for example `export default function (pi: ExtensionA", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_module_must_not_be_a_tools_only_export_a_named_export_only_module_or_a_file_that_requi', 'statement': 'The module must not be a tools-only export, a named-export-only module, or a file that requires an undocumented wrapper to load.', 'target': 'The module must not be a tools-only export, a named-export-only module, or a file that requires an undocumented wrapper to load', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'tool_registration_must_happen_from_inside_the_default_factory_by_calling_pi_registertool_f', 'statement': 'Tool registration must happen from inside the default factory by calling `pi.registerTool(...)` for each direct `spec_guard_*` tool.', 'target': 'Tool registration must happen from inside the default factory by calling `pi.registerTool(...)` for each direct `spec_guard_*` tool', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_generated_file_must_be_loadable_from_pi_extensions_spec_guard_ts_by_pi_s_normal_projec', 'statement': "The generated file must be loadable from `.pi/extensions/spec-guard.ts` by Pi's normal project-local extension discovery and reload path without a separate build step beyond Pi's documented TypeScript extension loading.", 'target': "The generated file must be loadable from `.pi/extensions/spec-guard.ts` by Pi's normal project-local extension discovery and reload path without a separate buil", 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'init_tests_must_prove_generated_pi_extension_loadability_not_only_text_content', 'statement': '`init` tests must prove generated Pi extension loadability, not only text content.', 'target': '`init` tests must prove generated Pi extension loadability, not only text content', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'at_minimum_tests_must_generate_pi_extensions_spec_guard_ts_load_or_import_it_through_the_s', 'statement': "At minimum, tests must generate `.pi/extensions/spec-guard.ts`, load or import it through the same TypeScript execution path used for Pi extensions or an equivalent test loader, assert that the module's default export is a function, invoke that function with a minimal mock `ExtensionAPI`, and assert that expected `spec_guard_*` tools are registered.", 'target': 'At minimum, tests must generate `.pi/extensions/spec-guard.ts`, load or import it through the same TypeScript execution path used for Pi extensions or an equiva', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'must_assert_that_pi_does_not_report_extension_does_not_export_a_valid_factory_function', 'statement': 'must assert that Pi does not report `Extension does not export a valid factory function`.', 'target': 'must assert that Pi does not report `Extension does not export a valid factory function`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'generated_guidance_must_state', 'statement': 'Generated guidance must state:', 'target': 'Generated guidance must state:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'use_spec_guard_tools_directly', 'statement': 'use Spec Guard tools directly,', 'target': 'use Spec Guard tools directly', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'human_confirmed_fields_require_actual_human_responses', 'statement': 'human-confirmed fields require actual human responses,', 'target': 'human-confirmed fields require actual human responses', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'fixed_binary_decisions_record_option_1_or_2_only', 'statement': 'fixed binary decisions record option 1 or 2 only,', 'target': 'fixed binary decisions record option 1 or 2 only', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'non_binary_custom_choices_require_numbered_confirmation', 'statement': 'non-binary custom choices require numbered confirmation,', 'target': 'non-binary custom choices require numbered confirmation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'single_packets_use_sequential_ac_packet_approval_and_authorization_gates', 'statement': 'single packets use sequential AC, packet approval, and authorization gates,', 'target': 'single packets use sequential AC, packet approval, and authorization gates', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'plan_batch_approval_applies_only_to_eligible_child_packets', 'statement': 'Plan batch approval applies only to eligible child packets,', 'target': 'Plan batch approval applies only to eligible child packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'documentation_itself_is_never_tested_and_retained_docs_tests_must_be_removed', 'statement': 'documentation itself is never tested and retained docs tests must be removed,', 'target': 'documentation itself is never tested and retained docs tests must be removed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'tests_must_clean_up_files_data_processes_external_resources_and_runtime_state', 'statement': 'tests must clean up files, data, processes, external resources, and runtime state,', 'target': 'tests must clean up files, data, processes, external resources, and runtime state', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'semantic_agent_claims_require_backend_verification_as_specified', 'statement': 'semantic agent claims require backend verification as specified.', 'target': 'semantic agent claims require backend verification as specified', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_generic_project_mcp_config_at_mcp_json', 'statement': 'Enumerated item is supported/enforced: generic project MCP config at `.mcp.json`,', 'target': 'generic project MCP config at `.mcp.json`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_claude_code_project_config_snippet_compatible_with_m', 'statement': 'Enumerated item is supported/enforced: Claude Code project config/snippet compatible with `.mcp.json`,', 'target': 'Claude Code project config/snippet compatible with `.mcp.json`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_claude_desktop_snippet_in_the_artifact_harness_direc', 'statement': 'Enumerated item is supported/enforced: Claude Desktop snippet in the artifact harness directory for copy/paste when project-local config is unsupported,', 'target': 'Claude Desktop snippet in the artifact harness directory for copy/paste when project-local config is unsupported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_cursor_project_config_at_cursor_mcp_json', 'statement': 'Enumerated item is supported/enforced: Cursor project config at `.cursor/mcp.json`,', 'target': 'Cursor project config at `.cursor/mcp.json`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_vs_code_config_at_vscode_mcp_json_where_supported', 'statement': 'Enumerated item is supported/enforced: VS Code config at `.vscode/mcp.json` where supported,', 'target': 'VS Code config at `.vscode/mcp.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_cline_config_at_cline_mcp_json_and_cline_cline_mcp_s', 'statement': 'Enumerated item is supported/enforced: Cline config at `.cline/mcp.json` and `.cline/cline_mcp_settings.json` where supported,', 'target': 'Cline config at `.cline/mcp.json` and `.cline/cline_mcp_settings.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_roo_config_at_roo_mcp_json_and_roo_roo_mcp_settings', 'statement': 'Enumerated item is supported/enforced: Roo config at `.roo/mcp.json` and `.roo/roo_mcp_settings.json` where supported,', 'target': 'Roo config at `.roo/mcp.json` and `.roo/roo_mcp_settings.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_windsurf_config_at_windsurf_mcp_json_and_windsurf_mc', 'statement': 'Enumerated item is supported/enforced: Windsurf config at `.windsurf/mcp.json` and `.windsurf/mcp_config.json` where supported,', 'target': 'Windsurf config at `.windsurf/mcp.json` and `.windsurf/mcp_config.json` where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_generic_stdio_snippets_for_other_mcp_clients_where_s', 'statement': 'Enumerated item is supported/enforced: generic stdio snippets for other MCP clients where supported,', 'target': 'generic stdio snippets for other MCP clients where supported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_project_local_pi_extension_at_pi_extensions_spec_gua', 'statement': 'Enumerated item is supported/enforced: project-local Pi extension at `.pi/extensions/spec-guard.ts`,', 'target': 'project-local Pi extension at `.pi/extensions/spec-guard.ts`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pi_extension_descriptor_or_snippet_in_the_artifact_h', 'statement': 'Enumerated item is supported/enforced: Pi extension descriptor or snippet in the artifact harness directory,', 'target': 'Pi extension descriptor or snippet in the artifact harness directory', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_project_visible_agent_guide_such_as_spec_guard_agent', 'statement': 'Enumerated item is supported/enforced: project-visible agent guide such as `SPEC_GUARD_AGENT_GUIDE.md`,', 'target': 'project-visible agent guide such as `SPEC_GUARD_AGENT_GUIDE.md`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_mcp_readme_quickstart', 'statement': 'Enumerated item is supported/enforced: MCP README/quickstart,', 'target': 'MCP README/quickstart', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_client_support_matrix', 'statement': 'Enumerated item is supported/enforced: client support matrix.', 'target': 'client support matrix', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_use_spec_guard_tools_directly', 'statement': 'Enumerated item is supported/enforced: use Spec Guard tools directly,', 'target': 'use Spec Guard tools directly', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_do_not_substitute_cli_for_mcp_except_bootstrap_init', 'statement': 'Enumerated item is supported/enforced: do not substitute CLI for MCP except bootstrap/init guidance,', 'target': 'do not substitute CLI for MCP except bootstrap/init guidance', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_do_not_inspect_spec_guard_package_source_internals_f', 'statement': 'Enumerated item is supported/enforced: do not inspect Spec Guard package/source internals for workflow parameters,', 'target': 'do not inspect Spec Guard package/source internals for workflow parameters', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_human_confirmed_fields_require_actual_human_response', 'statement': 'Enumerated item is supported/enforced: human-confirmed fields require actual human responses,', 'target': 'human-confirmed fields require actual human responses', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_human_approved_content_is_canonical_intent', 'statement': 'Enumerated item is supported/enforced: human-approved content is canonical intent,', 'target': 'human-approved content is canonical intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_discuss_is_non_mutating', 'statement': 'Enumerated item is supported/enforced: Discuss is non-mutating,', 'target': 'Discuss is non-mutating', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_binary_gates_remain_yes_no_discuss_after_discussion', 'statement': 'Enumerated item is supported/enforced: binary gates remain Yes/No/Discuss after discussion,', 'target': 'binary gates remain Yes/No/Discuss after discussion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_fixed_binary_decisions_record_option_1_or_2_only', 'statement': 'Enumerated item is supported/enforced: fixed binary decisions record option 1 or 2 only,', 'target': 'fixed binary decisions record option 1 or 2 only', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_non_binary_custom_choices_require_numbered_confirmat', 'statement': 'Enumerated item is supported/enforced: non-binary custom choices require numbered confirmation,', 'target': 'non-binary custom choices require numbered confirmation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_single_packets_use_sequential_ac_packet_approval_and', 'statement': 'Enumerated item is supported/enforced: single packets use sequential AC, packet approval, and authorization gates,', 'target': 'single packets use sequential AC, packet approval, and authorization gates', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_batch_approval_applies_only_to_eligible_child_p', 'statement': 'Enumerated item is supported/enforced: Plan batch approval applies only to eligible child packets,', 'target': 'Plan batch approval applies only to eligible child packets', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_documentation_itself_is_never_tested_and_retained_do', 'statement': 'Enumerated item is supported/enforced: documentation itself is never tested and retained docs tests must be removed,', 'target': 'documentation itself is never tested and retained docs tests must be removed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests_must_clean_up_files_data_processes_external_re', 'statement': 'Enumerated item is supported/enforced: tests must clean up files, data, processes, external resources, and runtime state,', 'target': 'tests must clean up files, data, processes, external resources, and runtime state', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_semantic_agent_claims_require_backend_verification_a', 'statement': 'Enumerated item is supported/enforced: semantic agent claims require backend verification as specified.', 'target': 'semantic agent claims require backend verification as specified', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
