"""Executable specification for US-05: Artifact and record model."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'spec_guard_distinguishes_top_level_artifacts_from_embedded_records', 'statement': 'Spec Guard distinguishes top-level artifacts from embedded records.', 'target': 'Spec Guard distinguishes top-level artifacts from embedded records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'top_level_artifacts_are_independently_stored_json_documents', 'statement': 'Top-level artifacts are independently stored JSON documents.', 'target': 'Top-level artifacts are independently stored JSON documents', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'they_must_include', 'statement': 'They must include:', 'target': 'They must include:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'top_level_artifacts_include', 'statement': 'Top-level artifacts include:', 'target': 'Top-level artifacts include:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'sourceartifact_records', 'statement': 'SourceArtifact records,', 'target': 'SourceArtifact records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'standalone_decision_artifacts_when_used', 'statement': 'standalone decision artifacts when used,', 'target': 'standalone decision artifacts when used', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'commandresult_records_when_stored_separately', 'statement': 'CommandResult records when stored separately,', 'target': 'CommandResult records when stored separately', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'verifier_configuration_when_stored_separately', 'statement': 'verifier configuration when stored separately.', 'target': 'verifier configuration when stored separately', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'a_newly_created_top_level_artifact_starts_at_governed_revision_1', 'statement': 'A newly created top-level artifact starts at governed `revision: 1`.', 'target': 'A newly created top-level artifact starts at governed `revision: 1`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'a_governed_mutating_write_to_a_top_level_artifact_increments_revision', 'statement': 'A governed mutating write to a top-level artifact increments `revision`', 'target': 'A governed mutating write to a top-level artifact increments `revision`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'updates_governed_updated_at', 'statement': 'updates governed `updated_at`.', 'target': 'updates governed `updated_at`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'audit_only_writes_including_persisted_review_snapshots_and_prompt_audit_records_must_not_i', 'statement': 'Audit-only writes, including persisted review snapshots and prompt audit records, must not increment the governed `revision` or governed `updated_at` used for approval staleness.', 'target': 'Audit-only writes, including persisted review snapshots and prompt audit records, must not increment the governed `revision` or governed `updated_at` used for a', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'audit_only_records_have_their_own_created_at_audit_sequencing', 'statement': 'Audit-only records have their own `created_at`/audit sequencing.', 'target': 'Audit-only records have their own `created_at`/audit sequencing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'if_an_implementation_stores_audit_records_physically_inside_a_top_level_artifact_file_it_m', 'statement': 'If an implementation stores audit records physically inside a top-level artifact file, it must maintain separate audit sequencing', 'target': 'If an implementation stores audit records physically inside a top-level artifact file, it must maintain separate audit sequencing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'must_not_make_the_governed_artifact_revision_stale_solely_because_an_audit_record_was_appe', 'statement': 'must not make the governed artifact revision stale solely because an audit record was appended.', 'target': 'must not make the governed artifact revision stale solely because an audit record was appended', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_governed_projection_is_the_artifact_json_at_that_revision_after_removing_audit_only_ap', 'statement': "The governed projection is the artifact JSON at that revision after removing audit-only appendices, physical-storage metadata, and fields whose schema explicitly says they are excluded from that artifact's hash, but retaining governed timestamps, revision, status, decisions, lifecycle, evidence, and diagnostics unless a named snapshot payload excludes them.", 'target': 'The governed projection is the artifact JSON at that revision after removing audit-only appendices, physical-storage metadata, and fields whose schema explicitl', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'revision_storage_must_persist_this_hash_with_the_immutable_revision_record', 'statement': 'Revision storage must persist this hash with the immutable revision record.', 'target': 'Revision storage must persist this hash with the immutable revision record', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'any_artifact_revision_referenced_by_sourceartifactref_review_snapshot_source_refs_approval', 'statement': 'Any artifact revision referenced by SourceArtifactRef, review snapshot source refs, approval records, or staleness checks must be revision-addressable after later writes.', 'target': 'Any artifact revision referenced by SourceArtifactRef, review snapshot source refs, approval records, or staleness checks must be revision-addressable after lat', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'implementations_may_store_full_historical_snapshots_or_immutable_content_addressed_revisio', 'statement': 'Implementations may store full historical snapshots or immutable content-addressed revision records, but they must be able to resolve the exact referenced revision and its hash-relevant canonical content.', 'target': 'Implementations may store full historical snapshots or immutable content-addressed revision records, but they must be able to resolve the exact referenced revis', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'when_audit_only_records_are_physically_stored_inside_an_artifact_file_the_governed_artifac', 'statement': 'When audit-only records are physically stored inside an artifact file, the governed artifact content hash/projection must exclude those audit appendices', 'target': 'When audit-only records are physically stored inside an artifact file, the governed artifact content hash/projection must exclude those audit appendices', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'physical_file_hashes_must_not_be_used_as_governed_revision_hashes_unless_the_storage_forma', 'statement': 'physical file hashes must not be used as governed revision hashes unless the storage format separates audit data.', 'target': 'physical file hashes must not be used as governed revision hashes unless the storage format separates audit data', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'embedded_records_live_inside_top_level_artifacts_unless_an_implementation_explicitly_store', 'statement': 'Embedded records live inside top-level artifacts unless an implementation explicitly stores them as top-level artifacts too.', 'target': 'Embedded records live inside top-level artifacts unless an implementation explicitly stores them as top-level artifacts too', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'embedded_records_do_not_need_top_level_artifact_common_fields_unless_persisted_independent', 'statement': 'Embedded records do not need top-level artifact common fields unless persisted independently.', 'target': 'Embedded records do not need top-level artifact common fields unless persisted independently', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'every_humandecision_must_be_retained_in_a_durable_append_only_decision_log', 'statement': 'Every HumanDecision must be retained in a durable append-only decision log.', 'target': 'Every HumanDecision must be retained in a durable append-only decision log', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'the_decision_log_may_be_embedded_in_the_owning_artifact_or_stored_as_standalone_decision_a', 'statement': 'The decision log may be embedded in the owning artifact or stored as standalone decision artifacts.', 'target': 'The decision log may be embedded in the owning artifact or stored as standalone decision artifacts', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'decisions_that_do_not_yet_have_an_owning_artifact_such_as_declined_plan_approvals_that_cre', 'statement': 'Decisions that do not yet have an owning artifact, such as declined Plan approvals that create no Plan, must be stored as standalone decision artifacts or in a project-level decision log.', 'target': 'Decisions that do not yet have an owning artifact, such as declined Plan approvals that create no Plan, must be stored as standalone decision artifacts or in a ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'changing_an_active_slot_must_not_delete_or_overwrite_prior_decisions_in_the_decision_log', 'statement': 'Changing an active slot must not delete or overwrite prior decisions in the decision log.', 'target': 'Changing an active slot must not delete or overwrite prior decisions in the decision log', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'every_commandresult_must_be_retained_in_durable_storage_addressable_by_command_result_ref', 'statement': 'Every CommandResult must be retained in durable storage addressable by `command_result_ref`.', 'target': 'Every CommandResult must be retained in durable storage addressable by `command_result_ref`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'commandresults_may_be_embedded_in_the_related_work_packet_embedded_in_the_runtime_baseline', 'statement': 'CommandResults may be embedded in the related Work Packet, embedded in the runtime baseline for baseline validation commands, or stored as standalone CommandResult records.', 'target': 'CommandResults may be embedded in the related Work Packet, embedded in the runtime baseline for baseline validation commands, or stored as standalone CommandRes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'evidence_records_reference_commandresults', 'statement': 'Evidence records reference CommandResults', 'target': 'Evidence records reference CommandResults', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'embedded_records_include', 'statement': 'Embedded records include:', 'target': 'Embedded records include:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'embedded_record_schemas_are_defined_in_appendix_a', 'statement': 'Embedded record schemas are defined in Appendix A.', 'target': 'Embedded record schemas are defined in Appendix A', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'enumerated_item_is_supported_enforced_artifact_type', 'statement': 'Enumerated item is supported/enforced: `artifact_type`,', 'target': '`artifact_type`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_schema_version', 'statement': 'Enumerated item is supported/enforced: `schema_version`,', 'target': '`schema_version`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_id_except_singletons', 'statement': 'Enumerated item is supported/enforced: `id` except singletons,', 'target': '`id` except singletons', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_revision', 'statement': 'Enumerated item is supported/enforced: `revision`,', 'target': '`revision`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_created_at', 'statement': 'Enumerated item is supported/enforced: `created_at`,', 'target': '`created_at`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_updated_at', 'statement': 'Enumerated item is supported/enforced: `updated_at`,', 'target': '`updated_at`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_diagnostics_where_applicable', 'statement': 'Enumerated item is supported/enforced: diagnostics where applicable.', 'target': 'diagnostics where applicable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_config', 'statement': 'Enumerated item is supported/enforced: config,', 'target': 'config', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline', 'statement': 'Enumerated item is supported/enforced: runtime baseline,', 'target': 'runtime baseline', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_work_packet', 'statement': 'Enumerated item is supported/enforced: Work Packet,', 'target': 'Work Packet', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan', 'statement': 'Enumerated item is supported/enforced: Plan,', 'target': 'Plan', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_sourceartifact_records', 'statement': 'Enumerated item is supported/enforced: SourceArtifact records,', 'target': 'SourceArtifact records', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_standalone_decision_artifacts_when_used', 'statement': 'Enumerated item is supported/enforced: standalone decision artifacts when used,', 'target': 'standalone decision artifacts when used', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_commandresult_records_when_stored_separately', 'statement': 'Enumerated item is supported/enforced: CommandResult records when stored separately,', 'target': 'CommandResult records when stored separately', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_configuration_when_stored_separately', 'statement': 'Enumerated item is supported/enforced: verifier configuration when stored separately.', 'target': 'verifier configuration when stored separately', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_humandecision', 'statement': 'Enumerated item is supported/enforced: HumanDecision,', 'target': 'HumanDecision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_evidencerecord', 'statement': 'Enumerated item is supported/enforced: EvidenceRecord,', 'target': 'EvidenceRecord', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packetchangebaseline', 'statement': 'Enumerated item is supported/enforced: PacketChangeBaseline,', 'target': 'PacketChangeBaseline', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_backendverification', 'statement': 'Enumerated item is supported/enforced: BackendVerification,', 'target': 'BackendVerification', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batchreviewsnapshot', 'statement': 'Enumerated item is supported/enforced: BatchReviewSnapshot,', 'target': 'BatchReviewSnapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batchproceedrecord', 'statement': 'Enumerated item is supported/enforced: BatchProceedRecord,', 'target': 'BatchProceedRecord', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_reviewsnapshot', 'statement': 'Enumerated item is supported/enforced: ReviewSnapshot,', 'target': 'ReviewSnapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_choiceprompt', 'statement': 'Enumerated item is supported/enforced: ChoicePrompt,', 'target': 'ChoicePrompt', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_choiceanswer', 'statement': 'Enumerated item is supported/enforced: ChoiceAnswer,', 'target': 'ChoiceAnswer', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_productcontext', 'statement': 'Enumerated item is supported/enforced: ProductContext,', 'target': 'ProductContext', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_commandresult', 'statement': 'Enumerated item is supported/enforced: CommandResult,', 'target': 'CommandResult', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docsrequirement', 'statement': 'Enumerated item is supported/enforced: DocsRequirement,', 'target': 'DocsRequirement', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acceptancecriterion', 'statement': 'Enumerated item is supported/enforced: AcceptanceCriterion,', 'target': 'AcceptanceCriterion', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_lifecycleevent', 'statement': 'Enumerated item is supported/enforced: LifecycleEvent,', 'target': 'LifecycleEvent', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_claim', 'statement': 'Enumerated item is supported/enforced: Claim,', 'target': 'Claim', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifierfinding', 'statement': 'Enumerated item is supported/enforced: VerifierFinding.', 'target': 'VerifierFinding', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
