"""Executable specification for US-18: Diagnostics."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'required_diagnostic_categories', 'statement': 'Required diagnostic categories:', 'target': 'Required diagnostic categories:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'binary_gate_discussion_must_re_prompt_yes_no_discuss', 'statement': 'binary gate discussion must re-prompt Yes/No/Discuss,', 'target': 'binary gate discussion must re-prompt Yes/No/Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'fixed_binary_decision_includes_something_else_custom_option', 'statement': 'fixed binary decision includes Something else/custom option,', 'target': 'fixed binary decision includes Something else/custom option', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'ac_approval_required', 'statement': 'AC approval required,', 'target': 'AC approval required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'source_derived_ac_missing_source_evidence', 'statement': 'source-derived AC missing source/evidence,', 'target': 'source-derived AC missing source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'batch_attempted_to_approve_source_derived_ac', 'statement': 'batch attempted to approve source-derived AC,', 'target': 'batch attempted to approve source-derived AC', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'changed_files_outside_allowed_globs', 'statement': 'changed files outside allowed globs,', 'target': 'changed files outside allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'update_touched_approved_fields_and_invalidated_approvals', 'statement': 'update touched approved fields and invalidated approvals,', 'target': 'update touched approved fields and invalidated approvals', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'protected_approved_field_update_rejected', 'statement': 'protected approved-field update rejected,', 'target': 'protected approved-field update rejected', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'api_contract_surface_docs_policy_not_required', 'statement': 'API/contract-surface docs policy not required,', 'target': 'API/contract-surface docs policy not required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_required_but_missing', 'statement': 'docs required but missing,', 'target': 'docs required but missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_to_ac_verification_required', 'statement': 'docs-to-AC verification required,', 'target': 'docs-to-AC verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'docs_updated_verification_required', 'statement': 'docs-updated verification required,', 'target': 'docs-updated verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'behavior_tests_to_documented_contract_verification_required', 'statement': 'behavior-tests-to-documented-contract verification required,', 'target': 'behavior-tests-to-documented-contract verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'tests_to_ac_verification_required', 'statement': 'tests-to-AC verification required,', 'target': 'tests-to-AC verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'retained_docs_test_detected', 'statement': 'retained docs test detected,', 'target': 'retained docs test detected', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'failure_evidence_semantic_verification_required', 'statement': 'failure evidence semantic verification required,', 'target': 'failure evidence semantic verification required', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'required_backend_verification_claim_missing_or_unregistered', 'statement': 'required backend verification claim missing or unregistered,', 'target': 'required backend verification claim missing or unregistered', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_vs_single_choice_required', 'statement': 'Plan-vs-single choice required,', 'target': 'Plan-vs-single choice required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_approval_required', 'statement': 'Plan approval required,', 'target': 'Plan approval required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'plan_approval_attempted_to_create_children_directly', 'statement': 'Plan approval attempted to create children directly,', 'target': 'Plan approval attempted to create children directly', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'batch_child_created_payload_mismatch', 'statement': 'batch child created payload mismatch,', 'target': 'batch child created payload mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'source_derived_ac_sourceevidence_refs_missing', 'statement': 'source-derived AC SourceEvidence refs missing,', 'target': 'source-derived AC SourceEvidence refs missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'batch_child_change_baseline_capture_failed', 'statement': 'batch child change baseline capture failed,', 'target': 'batch child change baseline capture failed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'plan_approved_field_update_rejected', 'statement': 'Plan approved-field update rejected,', 'target': 'Plan approved-field update rejected', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'pre_implementation_validation_required', 'statement': 'pre-implementation validation required,', 'target': 'pre-implementation validation required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'caller_supplied_command_status_rejected', 'statement': 'caller-supplied command status rejected,', 'target': 'caller-supplied command status rejected', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_missing_something_else_for_non_binary_semantic_choic', 'statement': 'Enumerated item is supported/enforced: missing Something else for non-binary semantic choice,', 'target': 'missing Something else for non-binary semantic choice', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_missing_discuss_option', 'statement': 'Enumerated item is supported/enforced: missing Discuss option,', 'target': 'missing Discuss option', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_custom_non_binary_choice_awaiting_numbered_confirmat', 'statement': 'Enumerated item is supported/enforced: custom non-binary choice awaiting numbered confirmation,', 'target': 'custom non-binary choice awaiting numbered confirmation', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_binary_gate_discussion_must_re_prompt_yes_no_discuss', 'statement': 'Enumerated item is supported/enforced: binary gate discussion must re-prompt Yes/No/Discuss,', 'target': 'binary gate discussion must re-prompt Yes/No/Discuss', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_fixed_binary_decision_includes_something_else_custom', 'statement': 'Enumerated item is supported/enforced: fixed binary decision includes Something else/custom option,', 'target': 'fixed binary decision includes Something else/custom option', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_approval_required', 'statement': 'Enumerated item is supported/enforced: AC approval required,', 'target': 'AC approval required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_review_snapshot_missing_or_stale', 'statement': 'Enumerated item is supported/enforced: AC review snapshot missing or stale,', 'target': 'AC review snapshot missing or stale', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_reviewed_payload_hash_mismatch', 'statement': 'Enumerated item is supported/enforced: AC reviewed payload hash mismatch,', 'target': 'AC reviewed payload hash mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ac_refinement_attempted_artifact_mutation', 'statement': 'Enumerated item is supported/enforced: AC refinement attempted artifact mutation,', 'target': 'AC refinement attempted artifact mutation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_derived_ac_missing_source_evidence', 'statement': 'Enumerated item is supported/enforced: source-derived AC missing source/evidence,', 'target': 'source-derived AC missing source/evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_attempted_to_approve_source_derived_ac', 'statement': 'Enumerated item is supported/enforced: batch attempted to approve source-derived AC,', 'target': 'batch attempted to approve source-derived AC', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_missing', 'statement': 'Enumerated item is supported/enforced: runtime baseline missing,', 'target': 'runtime baseline missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_not_accepted', 'statement': 'Enumerated item is supported/enforced: runtime baseline not accepted,', 'target': 'runtime baseline not accepted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_validation_failed', 'statement': 'Enumerated item is supported/enforced: runtime baseline validation failed,', 'target': 'runtime baseline validation failed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_runtime_baseline_acceptance_stale', 'statement': 'Enumerated item is supported/enforced: runtime baseline acceptance stale,', 'target': 'runtime baseline acceptance stale', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_packet_change_baseline_missing', 'statement': 'Enumerated item is supported/enforced: packet change baseline missing,', 'target': 'packet change baseline missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_dirty_implementation_source_at_authorization', 'statement': 'Enumerated item is supported/enforced: dirty implementation source at authorization,', 'target': 'dirty implementation source at authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_changed_files_outside_allowed_globs', 'statement': 'Enumerated item is supported/enforced: changed files outside allowed globs,', 'target': 'changed files outside allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_source_changed_before_failure_first_e', 'statement': 'Enumerated item is supported/enforced: implementation source changed before failure-first evidence,', 'target': 'implementation source changed before failure-first evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_classification_invalid', 'statement': 'Enumerated item is supported/enforced: classification invalid,', 'target': 'classification invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_policy_invalid', 'statement': 'Enumerated item is supported/enforced: docs policy invalid,', 'target': 'docs policy invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_update_touched_approved_fields_and_invalidated_appro', 'statement': 'Enumerated item is supported/enforced: update touched approved fields and invalidated approvals,', 'target': 'update touched approved fields and invalidated approvals', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_protected_approved_field_update_rejected', 'statement': 'Enumerated item is supported/enforced: protected approved-field update rejected,', 'target': 'protected approved-field update rejected', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_api_contract_surface_docs_policy_not_required', 'statement': 'Enumerated item is supported/enforced: API/contract-surface docs policy not required,', 'target': 'API/contract-surface docs policy not required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_required_but_missing', 'statement': 'Enumerated item is supported/enforced: docs required but missing,', 'target': 'docs required but missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_to_ac_verification_required', 'statement': 'Enumerated item is supported/enforced: docs-to-AC verification required,', 'target': 'docs-to-AC verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_docs_updated_verification_required', 'statement': 'Enumerated item is supported/enforced: docs-updated verification required,', 'target': 'docs-updated verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_behavior_tests_to_documented_contract_verification_r', 'statement': 'Enumerated item is supported/enforced: behavior-tests-to-documented-contract verification required,', 'target': 'behavior-tests-to-documented-contract verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_tests_to_ac_verification_required', 'statement': 'Enumerated item is supported/enforced: tests-to-AC verification required,', 'target': 'tests-to-AC verification required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_retained_docs_test_detected', 'statement': 'Enumerated item is supported/enforced: retained docs test detected,', 'target': 'retained docs test detected', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_test_cleanup_side_effect_detected', 'statement': 'Enumerated item is supported/enforced: test cleanup side effect detected,', 'target': 'test cleanup side effect detected', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_operational_document_not_applicable_validation_missi', 'statement': 'Enumerated item is supported/enforced: operational-document not-applicable validation missing,', 'target': 'operational-document not-applicable validation missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_not_applicable_evidence_lacks_deterministic_eligibil', 'statement': 'Enumerated item is supported/enforced: not-applicable evidence lacks deterministic eligibility,', 'target': 'not-applicable evidence lacks deterministic eligibility', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_operational_document_docs_policy_invalid', 'statement': 'Enumerated item is supported/enforced: operational-document docs policy invalid,', 'target': 'operational-document docs policy invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_failure_evidence_semantic_verification_required', 'statement': 'Enumerated item is supported/enforced: failure evidence semantic verification required,', 'target': 'failure evidence semantic verification required', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_disabled', 'statement': 'Enumerated item is supported/enforced: verifier disabled,', 'target': 'verifier disabled', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_adapter_unavailable', 'statement': 'Enumerated item is supported/enforced: verifier adapter unavailable,', 'target': 'verifier adapter unavailable', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_misconfigured', 'statement': 'Enumerated item is supported/enforced: verifier misconfigured,', 'target': 'verifier misconfigured', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_health_check_failed', 'statement': 'Enumerated item is supported/enforced: verifier health check failed,', 'target': 'verifier health check failed', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_response_invalid', 'statement': 'Enumerated item is supported/enforced: verifier response invalid,', 'target': 'verifier response invalid', 'authority': 'Authority.BACKEND_VERIFIER', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_verifier_attempted_to_judge_human_approved_intent', 'statement': 'Enumerated item is supported/enforced: verifier attempted to judge human-approved intent,', 'target': 'verifier attempted to judge human-approved intent', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_required_backend_verification_claim_missing_or_unreg', 'statement': 'Enumerated item is supported/enforced: required backend verification claim missing or unregistered,', 'target': 'required backend verification claim missing or unregistered', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_vs_single_choice_required', 'statement': 'Enumerated item is supported/enforced: Plan-vs-single choice required,', 'target': 'Plan-vs-single choice required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_approval_required', 'statement': 'Enumerated item is supported/enforced: Plan approval required,', 'target': 'Plan approval required', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_proposal_payload_hash_mismatch', 'statement': 'Enumerated item is supported/enforced: Plan proposal payload hash mismatch,', 'target': 'Plan proposal payload hash mismatch', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_approval_attempted_to_create_children_directly', 'statement': 'Enumerated item is supported/enforced: Plan approval attempted to create children directly,', 'target': 'Plan approval attempted to create children directly', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_snapshot_producer_output_missing', 'statement': 'Enumerated item is supported/enforced: review snapshot producer output missing,', 'target': 'review snapshot producer output missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_snapshot_payload_mismatch', 'statement': 'Enumerated item is supported/enforced: snapshot payload mismatch,', 'target': 'snapshot payload mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_stale_source_revision_for_ephemeral_snapshot', 'statement': 'Enumerated item is supported/enforced: stale source revision for ephemeral snapshot,', 'target': 'stale source revision for ephemeral snapshot', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_review_snapshot_missing_or_stale', 'statement': 'Enumerated item is supported/enforced: batch review snapshot missing or stale,', 'target': 'batch review snapshot missing or stale', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_source_artifact_refs_missing_or_not_derivable', 'statement': 'Enumerated item is supported/enforced: batch source artifact refs missing or not derivable,', 'target': 'batch source artifact refs missing or not derivable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_audit_revision_missing', 'statement': 'Enumerated item is supported/enforced: batch audit revision missing,', 'target': 'batch audit revision missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_proposed_children_payload_mismatch', 'statement': 'Enumerated item is supported/enforced: batch proposed children payload mismatch,', 'target': 'batch proposed children payload mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_snapshot_binding_missing', 'statement': 'Enumerated item is supported/enforced: batch child snapshot binding missing,', 'target': 'batch child snapshot binding missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_snapshot_revision_invalid', 'statement': 'Enumerated item is supported/enforced: batch child snapshot revision invalid,', 'target': 'batch child snapshot revision invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_proceed_approved_post_action_result_field', 'statement': 'Enumerated item is supported/enforced: batch proceed approved post-action result field,', 'target': 'batch proceed approved post-action result field', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_proceed_approved_payload_reference_missing', 'statement': 'Enumerated item is supported/enforced: batch proceed approved payload reference missing,', 'target': 'batch proceed approved payload reference missing', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ambiguous_proposed_child_id_in_batch_snapshot_revisi', 'statement': 'Enumerated item is supported/enforced: ambiguous proposed child id in batch snapshot revision,', 'target': 'ambiguous proposed child id in batch snapshot revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_created_payload_mismatch', 'statement': 'Enumerated item is supported/enforced: batch child created payload mismatch,', 'target': 'batch child created payload mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_approval_relevant_payload_mismatch', 'statement': 'Enumerated item is supported/enforced: batch child approval-relevant payload mismatch,', 'target': 'batch child approval-relevant payload mismatch', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_expected_revision_missing', 'statement': 'Enumerated item is supported/enforced: batch child expected revision missing,', 'target': 'batch child expected revision missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_proposed_child_id_invalid_for_batch_snapshot_re', 'statement': 'Enumerated item is supported/enforced: Plan proposed child id invalid for batch snapshot revision,', 'target': 'Plan proposed child id invalid for batch snapshot revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_plan_slice_mapping_missing_or_invalid', 'statement': 'Enumerated item is supported/enforced: batch child Plan slice mapping missing or invalid,', 'target': 'batch child Plan slice mapping missing or invalid', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_plan_slice_correspondence_mismatch', 'statement': 'Enumerated item is supported/enforced: batch child Plan slice correspondence mismatch,', 'target': 'batch child Plan slice correspondence mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_title_correspondence_mismatch', 'statement': 'Enumerated item is supported/enforced: batch child title correspondence mismatch,', 'target': 'batch child title correspondence mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_source_evidence_summary_mismatch', 'statement': 'Enumerated item is supported/enforced: batch child source evidence summary mismatch,', 'target': 'batch child source evidence summary mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_source_artifact_refs_missing_or_inconsis', 'statement': 'Enumerated item is supported/enforced: batch child source artifact refs missing or inconsistent,', 'target': 'batch child source artifact refs missing or inconsistent', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_artifact_refs_not_in_canonical_order', 'statement': 'Enumerated item is supported/enforced: source artifact refs not in canonical order,', 'target': 'source artifact refs not in canonical order', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_artifact_ref_unresolved', 'statement': 'Enumerated item is supported/enforced: source artifact ref unresolved,', 'target': 'source artifact ref unresolved', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_artifact_content_hash_mismatch', 'statement': 'Enumerated item is supported/enforced: source artifact content hash mismatch,', 'target': 'source artifact content hash mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_derived_ac_sourceevidence_refs_missing', 'statement': 'Enumerated item is supported/enforced: source-derived AC SourceEvidence refs missing,', 'target': 'source-derived AC SourceEvidence refs missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_source_evidence_hash_mismatch', 'statement': 'Enumerated item is supported/enforced: source evidence hash mismatch,', 'target': 'source evidence hash mismatch', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_proposed_workpacket_payload_missing', 'statement': 'Enumerated item is supported/enforced: batch child proposed WorkPacket payload missing,', 'target': 'batch child proposed WorkPacket payload missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_batch_child_change_baseline_capture_failed', 'statement': 'Enumerated item is supported/enforced: batch child change baseline capture failed,', 'target': 'batch child change baseline capture failed', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_proposed_authorization_snapshot_payload_invalid', 'statement': 'Enumerated item is supported/enforced: proposed authorization snapshot payload invalid,', 'target': 'proposed authorization snapshot payload invalid', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_authorization_snapshot_missing_approved_packet_hash', 'statement': 'Enumerated item is supported/enforced: authorization snapshot missing approved packet hash,', 'target': 'authorization snapshot missing approved packet hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approved_fields_missing', 'statement': 'Enumerated item is supported/enforced: approved fields missing,', 'target': 'approved fields missing', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approved_payload_missing_for_registered_decision_typ', 'statement': 'Enumerated item is supported/enforced: approved payload missing for registered decision type,', 'target': 'approved payload missing for registered decision type', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_declined_decision_incorrectly_supplied_approved_payl', 'statement': 'Enumerated item is supported/enforced: declined decision incorrectly supplied approved payload,', 'target': 'declined decision incorrectly supplied approved payload', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_decision_mutation_prohibited', 'statement': 'Enumerated item is supported/enforced: decision mutation prohibited,', 'target': 'decision mutation prohibited', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_plan_approved_field_update_rejected', 'statement': 'Enumerated item is supported/enforced: Plan approved-field update rejected,', 'target': 'Plan approved-field update rejected', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ready_child_packet_preconditions_missing', 'statement': 'Enumerated item is supported/enforced: ready child packet preconditions missing,', 'target': 'ready child packet preconditions missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_work_packet_approval_missing', 'statement': 'Enumerated item is supported/enforced: Work Packet approval missing,', 'target': 'Work Packet approval missing', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_implementation_authorization_missing', 'statement': 'Enumerated item is supported/enforced: implementation authorization missing,', 'target': 'implementation authorization missing', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_pre_implementation_validation_required', 'statement': 'Enumerated item is supported/enforced: pre-implementation validation required,', 'target': 'pre-implementation validation required', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_review_traceability_missing', 'statement': 'Enumerated item is supported/enforced: review traceability missing,', 'target': 'review traceability missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command_result_missing_for_command_backed_evidence', 'statement': 'Enumerated item is supported/enforced: command result missing for command-backed evidence,', 'target': 'command result missing for command-backed evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command_result_execution_context_missing', 'statement': 'Enumerated item is supported/enforced: command result execution context missing,', 'target': 'command result execution context missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command_result_status_incompatible_with_evidence_typ', 'statement': 'Enumerated item is supported/enforced: command result status incompatible with evidence type,', 'target': 'command result status incompatible with evidence type', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_command_result_purpose_incompatible_with_evidence_ty', 'statement': 'Enumerated item is supported/enforced: command result purpose incompatible with evidence type,', 'target': 'command result purpose incompatible with evidence type', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_caller_supplied_command_status_rejected', 'statement': 'Enumerated item is supported/enforced: caller-supplied command status rejected,', 'target': 'caller-supplied command status rejected', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_final_claim_unsupported', 'statement': 'Enumerated item is supported/enforced: final claim unsupported,', 'target': 'final claim unsupported', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_approval_hash_stale', 'statement': 'Enumerated item is supported/enforced: approval hash stale,', 'target': 'approval hash stale', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_cli_mcp_parity_missing', 'statement': 'Enumerated item is supported/enforced: CLI/MCP parity missing.', 'target': 'CLI/MCP parity missing', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
