"""Executable specification for US-06: Runtime and packet change baselines."""

import pytest

from spec_guard.contracts import GovernanceContract, GovernanceControl
from spec_guard.enums import Authority, EnforcementLevel, MutationMode


AUTHORITY_VALUES = {
    "Authority.HUMAN": Authority.HUMAN,
    "Authority.BACKEND_VERIFIER": Authority.BACKEND_VERIFIER,
    "Authority.FRONTEND_AGENT": Authority.FRONTEND_AGENT,
    "Authority.DETERMINISTIC_KERNEL": Authority.DETERMINISTIC_KERNEL,
}

MUTATION_VALUES = {
    "MutationMode.YES": MutationMode.YES,
    "MutationMode.NO": MutationMode.NO,
    "MutationMode.AUDIT_ONLY": MutationMode.AUDIT_ONLY,
}

ENFORCEMENT_VALUES = {
    "EnforcementLevel.BLOCKING": EnforcementLevel.BLOCKING,
    "EnforcementLevel.REQUIRED": EnforcementLevel.REQUIRED,
    "EnforcementLevel.OBSERVABLE": EnforcementLevel.OBSERVABLE,
}

CONTROLS = [
    {'name': 'prevent_fake_or_placeholder_project_commands', 'statement': 'prevent fake or placeholder project commands,', 'target': 'prevent fake or placeholder project commands', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'ensure_plan_batch_acceleration_is_not_blocked_by_missing_environment_readiness', 'statement': 'ensure Plan batch acceleration is not blocked by missing environment readiness.', 'target': 'ensure Plan batch acceleration is not blocked by missing environment readiness', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'blocked', 'statement': '`blocked`.', 'target': '`blocked`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'the_runtime_baseline_must_capture', 'statement': 'The runtime baseline must capture:', 'target': 'The runtime baseline must capture:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'acceptance_record_when_accepted', 'statement': 'acceptance record when accepted,', 'target': 'acceptance record when accepted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'blocker_record_when_blocked', 'statement': 'blocker record when blocked.', 'target': 'blocker record when blocked', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'commands_must_distinguish_when_applicable', 'statement': 'Commands must distinguish, when applicable:', 'target': 'Commands must distinguish, when applicable:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_a_project_requires_both_frontend_and_backend_for_development_the_development_command_mu', 'statement': 'If a project requires both frontend and backend for development, the development command must be one documented command or orchestrated entry point that starts the required full development runtime, or a concrete not-applicable reason must be recorded.', 'target': 'If a project requires both frontend and backend for development, the development command must be one documented command or orchestrated entry point that starts ', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'baseline_acceptance_requires', 'statement': 'Baseline acceptance requires:', 'target': 'Baseline acceptance requires:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_runtime_baseline_review_snapshot_hash_and_revision_shown_to_the_human', 'statement': 'a runtime baseline review snapshot hash and revision shown to the human,', 'target': 'a runtime baseline review snapshot hash and revision shown to the human', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'required_commands_or_concrete_not_applicable_reasons', 'statement': 'required commands or concrete not-applicable reasons,', 'target': 'required commands or concrete not-applicable reasons', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'no_placeholder_version_only_or_spec_guard_self_check_command_used_as_project_validation', 'statement': 'no placeholder, version-only, or Spec Guard self-check command used as project validation.', 'target': 'no placeholder, version-only, or Spec Guard self-check command used as project validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'deterministic_runtime_baseline_validation_requires_every_non_null_configured_command_in_co', 'statement': 'Deterministic runtime baseline validation requires every non-null configured command in `commands.test`, `commands.build`, `commands.runtime_production`, and `commands.runtime_development` to be a CommandSpec and to have a current RuntimeBaseline `validation.command_results` entry whose `command_spec` is canonically equal, whose purpose matches (`test`, `build`, `runtime_production`, or `runtime_development`), whose `related_runtime_baseline_ref` is null during draft validation, and whose status is `passed`.', 'target': 'Deterministic runtime baseline validation requires every non-null configured command in `commands.test`, `commands.build`, `commands.runtime_production`, and `c', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'a_null_command_is_valid_only_when_the_corresponding_concrete_not_applicable_reason_field_i', 'statement': 'A null command is valid only when the corresponding concrete not-applicable reason field is non-empty.', 'target': 'A null command is valid only when the corresponding concrete not-applicable reason field is non-empty', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'commandresults_with_status_failed_timed_out_or_skipped_placeholder_version_only_self_check', 'statement': 'CommandResults with status `failed`, `timed_out`, or `skipped`, placeholder/version-only/self-check command specs, missing command results, command purpose mismatches, stale command specs, or null commands without not-applicable reasons block baseline acceptance.', 'target': 'CommandResults with status `failed`, `timed_out`, or `skipped`, placeholder/version-only/self-check command specs, missing command results, command purpose mism', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'if_deterministic_validation_fails_after_human_yes_acceptance_is_not_recorded', 'statement': 'If deterministic validation fails after human Yes, acceptance is not recorded.', 'target': 'If deterministic validation fails after human Yes, acceptance is not recorded', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'the_baseline_remains_draft_or_blocked_with_diagnostics', 'statement': 'The baseline remains draft or blocked with diagnostics.', 'target': 'The baseline remains draft or blocked with diagnostics', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'if_the_human_selects_numbered_no_on_the_runtime_baseline_acceptance_gate_baseline_accept_r', 'statement': 'If the human selects numbered No on the runtime baseline acceptance gate, `baseline.accept` records a `runtime_baseline_acceptance` HumanDecision with `approved_fields: []`, no approved payload, the reviewed snapshot hash, revision, and source refs required by the action contract, and normalized decision `no`.', 'target': 'If the human selects numbered No on the runtime baseline acceptance gate, `baseline.accept` records a `runtime_baseline_acceptance` HumanDecision with `approved', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'it_appends_that_decision_to_runtime_baseline_decision_history_sets_baseline_status_to_bloc', 'statement': 'It appends that decision to runtime baseline decision history, sets baseline status to `blocked`, records a Blocker with reason `human_declined_baseline_acceptance`,', 'target': 'It appends that decision to runtime baseline decision history, sets baseline status to `blocked`, records a Blocker with reason `human_declined_baseline_accepta', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'does_not_create_a_runtimebaselineref', 'statement': 'does not create a RuntimeBaselineRef.', 'target': 'does not create a RuntimeBaselineRef', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'discuss_records_no_humandecision_and_no_status_change', 'statement': 'Discuss records no HumanDecision and no status change.', 'target': 'Discuss records no HumanDecision and no status change', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'require_the_same_yes_no_discuss_acceptance_gate_again', 'statement': 'require the same Yes/No/Discuss acceptance gate again.', 'target': 'require the same Yes/No/Discuss acceptance gate again', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'when_baseline_update_changes_any_accepted_approved_path_spec_guard_sets_runtimebaseline_st', 'statement': 'When `baseline.update` changes any accepted approved path, Spec Guard sets RuntimeBaseline status to `draft`, clears the current `acceptance` convenience slot, keeps decision history append-only, records invalidation diagnostics,', 'target': 'When `baseline.update` changes any accepted approved path, Spec Guard sets RuntimeBaseline status to `draft`, clears the current `acceptance` convenience slot, ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'marks_every_runtimebaselineref_to_the_prior_accepted_revision_stale_for_dependent_packet_a', 'statement': 'marks every RuntimeBaselineRef to the prior accepted revision stale for dependent packet approval/authorization checks.', 'target': 'marks every RuntimeBaselineRef to the prior accepted revision stale for dependent packet approval/authorization checks', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'baseline_accept_validates_the_reviewed_pre_acceptance_payload_against_the_submitted_snapsh', 'statement': '`baseline.accept` validates the reviewed pre-acceptance payload against the submitted snapshot hash, records the acceptance HumanDecision with that snapshot hash, writes acceptance state, increments the RuntimeBaseline revision,', 'target': '`baseline.accept` validates the reviewed pre-acceptance payload against the submitted snapshot hash, records the acceptance HumanDecision with that snapshot has', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'returns_the_accepted_revision_for_references', 'statement': 'returns the accepted revision for references.', 'target': 'returns the accepted revision for references', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'later_staleness_checks_compare_packet_refs_against_this_accepted_revision_and_acceptance_d', 'statement': 'Later staleness checks compare packet refs against this accepted revision and acceptance decision.', 'target': 'Later staleness checks compare packet refs against this accepted revision and acceptance decision', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'runtime_baseline_acceptance_must_not_be_batch_approved', 'statement': 'Runtime baseline acceptance must not be batch-approved.', 'target': 'Runtime baseline acceptance must not be batch-approved', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'it_is_captured_at_implementation_authorization_time', 'statement': 'It is captured at implementation authorization time', 'target': 'It is captured at implementation authorization time', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'is_used_to', 'statement': 'is used to:', 'target': 'is used to:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'compute_changed_files', 'statement': 'compute changed files,', 'target': 'compute changed files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'enforce_allowed_globs', 'statement': 'enforce allowed globs,', 'target': 'enforce allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'support_review_traceability', 'statement': 'support review traceability.', 'target': 'support review traceability', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'vcs_record_commit_tree_identifier_and_working_tree_status', 'statement': '`vcs`: record commit/tree identifier and working tree status,', 'target': '`vcs`: record commit/tree identifier and working tree status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'manifest_record_a_file_manifest_when_vcs_metadata_is_unavailable', 'statement': '`manifest`: record a file manifest when VCS metadata is unavailable.', 'target': '`manifest`: record a file manifest when VCS metadata is unavailable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'vcs_requires_supported_vcs_metadata', 'statement': '`vcs` requires supported VCS metadata', 'target': '`vcs` requires supported VCS metadata', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'blocks_if_unavailable', 'statement': 'blocks if unavailable.', 'target': 'blocks if unavailable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'manifest_always_uses_manifest_capture', 'statement': '`manifest` always uses manifest capture.', 'target': '`manifest` always uses manifest capture', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'auto_uses_vcs_when_supported_vcs_metadata_is_present_at_or_above_the_project_root_and_othe', 'statement': '`auto` uses `vcs` when supported VCS metadata is present at or above the project root and otherwise uses `manifest`.', 'target': '`auto` uses `vcs` when supported VCS metadata is present at or above the project root and otherwise uses `manifest`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_minimum_required_vcs_implementation_is_git', 'statement': 'The minimum required VCS implementation is Git.', 'target': 'The minimum required VCS implementation is Git', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'other_vcs_systems_are_optional_but_if_supported_they_must_provide_equivalent_commit_tree_d', 'statement': 'Other VCS systems are optional, but if supported they must provide equivalent commit/tree, dirty tracked path, and untracked path data.', 'target': 'Other VCS systems are optional, but if supported they must provide equivalent commit/tree, dirty tracked path, and untracked path data', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'they_use_this_selected_mode', 'statement': 'they use this selected mode.', 'target': 'they use this selected mode', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'at_authorization_spec_guard_must_capture', 'statement': 'At authorization, Spec Guard must capture:', 'target': 'At authorization, Spec Guard must capture:', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'captured_timestamp', 'statement': 'captured timestamp,', 'target': 'captured timestamp', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'allowed_globs', 'statement': 'allowed globs,', 'target': 'allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'the_captured_workpacket_artifact_hash_is_the_governed_content_hash_of_the_workpacket_at_th', 'statement': 'The captured WorkPacket artifact hash is the governed content hash of the WorkPacket at the recorded `artifact_revision`, excluding the `change_baseline.artifact_hash` field itself and excluding audit-only appendices.', 'target': 'The captured WorkPacket artifact hash is the governed content hash of the WorkPacket at the recorded `artifact_revision`, excluding the `change_baseline.artifac', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'it_includes_the_other_packetchangebaseline_fields_committed_atomically_with_authorization', 'statement': 'It includes the other PacketChangeBaseline fields committed atomically with authorization.', 'target': 'It includes the other PacketChangeBaseline fields committed atomically with authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'authorization_commit_uses_a_deterministic_prepare_commit_algorithm', 'statement': 'Authorization commit uses a deterministic prepare/commit algorithm.', 'target': 'Authorization commit uses a deterministic prepare/commit algorithm', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'it_computes_artifact_hash_over_that_projection_while_excluding_only_change_baseline_artifa', 'statement': 'It computes `artifact_hash` over that projection while excluding only `change_baseline.artifact_hash` and audit-only appendices, writes the computed hash into `change_baseline.artifact_hash`, then commits that exact projection as `artifact_revision = next_revision`.', 'target': 'It computes `artifact_hash` over that projection while excluding only `change_baseline.artifact_hash` and audit-only appendices, writes the computed hash into `', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.AUDIT_ONLY', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'if_the_final_committed_projection_excluding_artifact_hash_does_not_hash_to_the_stored_valu', 'statement': 'If the final committed projection excluding `artifact_hash` does not hash to the stored value, authorization is invalid', 'target': 'If the final committed projection excluding `artifact_hash` does not hash to the stored value, authorization is invalid', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'must_be_rolled_back_or_marked_failed_before_any_authorization_decision_is_exposed', 'statement': 'must be rolled back or marked failed before any authorization decision is exposed.', 'target': 'must be rolled back or marked failed before any authorization decision is exposed', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'if_vcs_exists_and_the_working_tree_has_uncommitted_implementation_source_runtime_product_c', 'statement': 'If VCS exists and the working tree has uncommitted `implementation_source`, `runtime_product_configuration`, or `other_unexpected` changes before authorization, authorization must block unless the human resolves the dirty state before authorization.', 'target': 'If VCS exists and the working tree has uncommitted `implementation_source`, `runtime_product_configuration`, or `other_unexpected` changes before authorization,', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'dirty_files_categorized_as_docs_tests_or_spec_guard_artifact_evidence_may_exist_before_aut', 'statement': 'Dirty files categorized as `docs`, `tests`, or `spec_guard_artifact_evidence` may exist before authorization, but their pre-authorization status and content hashes are captured into the packet baseline as pre-existing state', 'target': 'Dirty files categorized as `docs`, `tests`, or `spec_guard_artifact_evidence` may exist before authorization, but their pre-authorization status and content has', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'do_not_count_as_packet_evidence_unless_re_recorded_after_authorization', 'statement': 'do not count as packet evidence unless re-recorded after authorization.', 'target': 'do not count as packet evidence unless re-recorded after authorization', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'spec_guard_must_not_silently_absorb_pre_existing_product_source_runtime_configuration_chan', 'statement': 'Spec Guard must not silently absorb pre-existing product/source/runtime configuration changes into the packet.', 'target': 'Spec Guard must not silently absorb pre-existing product/source/runtime configuration changes into the packet', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'changed_files_are_computed_from_packet_change_baseline_to_current_state', 'statement': 'Changed files are computed from packet change baseline to current state:', 'target': 'Changed files are computed from packet change baseline to current state:', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'vcs_mode_diff_baseline_commit_tree_plus_working_tree_and_untracked_files_adjusted_by_store', 'statement': 'VCS mode: diff baseline commit/tree plus working tree and untracked files, adjusted by stored dirty/untracked baseline entries.', 'target': 'VCS mode: diff baseline commit/tree plus working tree and untracked files, adjusted by stored dirty/untracked baseline entries', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_git_capture_head_commit_head_tree_and_repository_relative_dirty_untracked_entries_from', 'statement': 'For Git, capture `HEAD` commit, `HEAD` tree, and repository-relative dirty/untracked entries from porcelain status with NUL separation.', 'target': 'For Git, capture `HEAD` commit, `HEAD` tree, and repository-relative dirty/untracked entries from porcelain status with NUL separation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'deleted_entries_keep_the_deleted_path', 'statement': 'Deleted entries keep the deleted path.', 'target': 'Deleted entries keep the deleted path', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'untracked_paths_are_captured_exactly_as_repository_relative_paths', 'statement': 'Untracked paths are captured exactly as repository-relative paths.', 'target': 'Untracked paths are captured exactly as repository-relative paths', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'for_every_allowed_pre_authorization_dirty_untracked_docs_tests_evidence_path_capture_size', 'statement': 'For every allowed pre-authorization dirty/untracked docs/tests/evidence path, capture size and content hash', 'target': 'For every allowed pre-authorization dirty/untracked docs/tests/evidence path, capture size and content hash', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'later_changed_file_computation_treats_that_captured_content_hash_as_the_baseline_for_that', 'statement': 'later changed-file computation treats that captured content hash as the baseline for that path so pre-existing dirty content is not counted as a packet change unless it changes after authorization.', 'target': 'later changed-file computation treats that captured content hash as the baseline for that path so pre-existing dirty content is not counted as a packet change u', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': True},
    {'name': 'manifest_mode_compare_current_manifest_to_captured_manifest', 'statement': 'Manifest mode: compare current manifest to captured manifest.', 'target': 'Manifest mode: compare current manifest to captured manifest', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.OBSERVABLE', 'blocking': False},
    {'name': 'changed_files_must_be_classified_by_the_canonical_changefilecategory_enum_in_appendix_c', 'statement': 'Changed files must be classified by the canonical `ChangeFileCategory` enum in Appendix C.', 'target': 'Changed files must be classified by the canonical `ChangeFileCategory` enum in Appendix C', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_make_environment_readiness_explicit', 'statement': 'Enumerated item is supported/enforced: make environment readiness explicit,', 'target': 'make environment readiness explicit', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_prevent_fake_or_placeholder_project_commands', 'statement': 'Enumerated item is supported/enforced: prevent fake or placeholder project commands,', 'target': 'prevent fake or placeholder project commands', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ensure_plan_batch_acceleration_is_not_blocked_by_mis', 'statement': 'Enumerated item is supported/enforced: ensure Plan batch acceleration is not blocked by missing environment readiness.', 'target': 'ensure Plan batch acceleration is not blocked by missing environment readiness', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_draft', 'statement': 'Enumerated item is supported/enforced: `draft`,', 'target': '`draft`', 'authority': 'Authority.FRONTEND_AGENT', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_accepted', 'statement': 'Enumerated item is supported/enforced: `accepted`,', 'target': '`accepted`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_blocked', 'statement': 'Enumerated item is supported/enforced: `blocked`.', 'target': '`blocked`', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_stack', 'statement': 'Enumerated item is supported/enforced: stack,', 'target': 'stack', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_commands', 'statement': 'Enumerated item is supported/enforced: commands,', 'target': 'commands', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_configuration_assumptions', 'statement': 'Enumerated item is supported/enforced: configuration assumptions,', 'target': 'configuration assumptions', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_dependency_modes', 'statement': 'Enumerated item is supported/enforced: dependency modes,', 'target': 'dependency modes', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_diff_policy', 'statement': 'Enumerated item is supported/enforced: diff policy,', 'target': 'diff policy', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_validation_results', 'statement': 'Enumerated item is supported/enforced: validation results,', 'target': 'validation results', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_acceptance_record_when_accepted', 'statement': 'Enumerated item is supported/enforced: acceptance record when accepted,', 'target': 'acceptance record when accepted', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_blocker_record_when_blocked', 'statement': 'Enumerated item is supported/enforced: blocker record when blocked.', 'target': 'blocker record when blocked', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.BLOCKING', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_test', 'statement': 'Enumerated item is supported/enforced: test,', 'target': 'test', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_build', 'statement': 'Enumerated item is supported/enforced: build,', 'target': 'build', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_production_runtime_smoke', 'statement': 'Enumerated item is supported/enforced: production runtime smoke,', 'target': 'production runtime smoke', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_development_runtime', 'statement': 'Enumerated item is supported/enforced: development runtime.', 'target': 'development runtime', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_numbered_human_yes_on_the_baseline_acceptance_ga', 'statement': 'Ordered requirement is supported/enforced: numbered human Yes on the baseline acceptance gate,', 'target': 'Ordered requirement is supported/enforced: numbered human Yes on the baseline acceptance gate', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_a_runtime_baseline_review_snapshot_hash_and_revi', 'statement': 'Ordered requirement is supported/enforced: a runtime baseline review snapshot hash and revision shown to the human,', 'target': 'Ordered requirement is supported/enforced: a runtime baseline review snapshot hash and revision shown to the human', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_deterministic_validation_success', 'statement': 'Ordered requirement is supported/enforced: deterministic validation success,', 'target': 'Ordered requirement is supported/enforced: deterministic validation success', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_required_commands_or_concrete_not_applicable_rea', 'statement': 'Ordered requirement is supported/enforced: required commands or concrete not-applicable reasons,', 'target': 'Ordered requirement is supported/enforced: required commands or concrete not-applicable reasons', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'ordered_requirement_is_supported_enforced_no_placeholder_version_only_or_spec_guard_self_c', 'statement': 'Ordered requirement is supported/enforced: no placeholder, version-only, or Spec Guard self-check command used as project validation.', 'target': 'Ordered requirement is supported/enforced: no placeholder, version-only, or Spec Guard self-check command used as project validation', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_compute_changed_files', 'statement': 'Enumerated item is supported/enforced: compute changed files,', 'target': 'compute changed files', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_enforce_allowed_globs', 'statement': 'Enumerated item is supported/enforced: enforce allowed globs,', 'target': 'enforce allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_prove_implementation_source_did_not_change_before_fa', 'statement': 'Enumerated item is supported/enforced: prove implementation source did not change before failure-first evidence,', 'target': 'prove implementation source did not change before failure-first evidence', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_support_review_traceability', 'statement': 'Enumerated item is supported/enforced: support review traceability.', 'target': 'support review traceability', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_vcs_record_commit_tree_identifier_and_working_tree_s', 'statement': 'Enumerated item is supported/enforced: `vcs`: record commit/tree identifier and working tree status,', 'target': '`vcs`: record commit/tree identifier and working tree status', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_manifest_record_a_file_manifest_when_vcs_metadata_is', 'statement': 'Enumerated item is supported/enforced: `manifest`: record a file manifest when VCS metadata is unavailable.', 'target': '`manifest`: record a file manifest when VCS metadata is unavailable', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_mode', 'statement': 'Enumerated item is supported/enforced: mode,', 'target': 'mode', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_captured_timestamp', 'statement': 'Enumerated item is supported/enforced: captured timestamp,', 'target': 'captured timestamp', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_workpacket_governed_content_hash_revision', 'statement': 'Enumerated item is supported/enforced: WorkPacket governed content hash/revision,', 'target': 'WorkPacket governed content hash/revision', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_allowed_globs', 'statement': 'Enumerated item is supported/enforced: allowed globs,', 'target': 'allowed globs', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_ignored_path_rules', 'statement': 'Enumerated item is supported/enforced: ignored path rules,', 'target': 'ignored path rules', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_vcs_commit_tree_and_dirty_state_or_manifest_hash_and', 'statement': 'Enumerated item is supported/enforced: VCS commit/tree and dirty state, or manifest hash and file entries.', 'target': 'VCS commit/tree and dirty state, or manifest hash and file entries', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.NO', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_vcs_mode_diff_baseline_commit_tree_plus_working_tree', 'statement': 'Enumerated item is supported/enforced: VCS mode: diff baseline commit/tree plus working tree and untracked files, adjusted by stored dirty/untracked baseline entries. For Git, capture `HEAD` commit, `HEAD` tree, and repository-relative dirty/untracked entries from porcelain status with NUL separation. Rename entries are normalized to the new repository-relative path with status `renamed`. Deleted entries keep the deleted path. Untracked paths are captured exactly as repository-relative paths. For every allowed pre-authorization dirty/untracked docs/tests/evidence path, capture size and content hash; later changed-file computation treats that captured content hash as the baseline for that path so pre-existing dirty content is not counted as a packet change unless it changes after authorization.', 'target': 'VCS mode: diff baseline commit/tree plus working tree and untracked files, adjusted by stored dirty/untracked baseline entries. For Git, capture `HEAD` commit, ', 'authority': 'Authority.HUMAN', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True},
    {'name': 'enumerated_item_is_supported_enforced_manifest_mode_compare_current_manifest_to_captured_m', 'statement': 'Enumerated item is supported/enforced: Manifest mode: compare current manifest to captured manifest.', 'target': 'Manifest mode: compare current manifest to captured manifest', 'authority': 'Authority.DETERMINISTIC_KERNEL', 'mutation': 'MutationMode.YES', 'level': 'EnforcementLevel.REQUIRED', 'blocking': True}
]


@pytest.mark.parametrize("expected", CONTROLS, ids=[item["name"] for item in CONTROLS])
def test_governance_control_is_registered_with_concrete_enforcement(expected):
    contract = GovernanceContract.default()

    actual = contract.control(expected["name"])

    assert isinstance(actual, GovernanceControl)
    assert actual.name == expected["name"]
    assert actual.statement == expected["statement"]
    assert actual.target == expected["target"]
    assert actual.authority is AUTHORITY_VALUES[expected["authority"]]
    assert actual.mutation_mode is MUTATION_VALUES[expected["mutation"]]
    assert actual.enforcement_level is ENFORCEMENT_VALUES[expected["level"]]
    assert actual.blocks_noncompliant_workflow is expected["blocking"]
    assert actual.enforced is True


def test_workflow_rejects_execution_when_any_registered_blocking_control_fails():
    contract = GovernanceContract.default()
    blocking_controls = [item["name"] for item in CONTROLS if item["blocking"]]

    result = contract.evaluate_workflow_controls(
        operation="implementation_source_change",
        actor="agent",
        satisfied_controls=[],
        candidate_controls=blocking_controls,
    )

    assert result.allowed is False
    assert result.blocked_control_names == blocking_controls
    assert all(diagnostic.severity == "error" for diagnostic in result.diagnostics)
